// SETUP: IR port — the intermediate-representation graph model (iFlowGraph) that every
// layer (parse, layout, paths, render) and every external agent depends on. Pure data:
// no React, no positions, no rendering concerns. This is the contract; the code proves it.

/** Semantic node kind. Drives shape, default icon, and status color. */
export type iNodeType =
  | 'start'
  | 'end'
  | 'action'
  | 'decision'
  | 'error'
  | 'warning'
  | 'link';

/** Semantic edge kind. Drives edge color/weight and feeds path typing. */
export type iEdgeType = 'happy' | 'warning' | 'error' | 'default';

/** Layout flow direction. TD=top-down, BT=bottom-top, LR=left-right, RL=right-left. */
export type iDirection = 'TD' | 'BT' | 'LR' | 'RL';

/** The complete set of legal node types, for runtime validation. */
export const NODE_TYPES: readonly iNodeType[] = [
  'start',
  'end',
  'action',
  'decision',
  'error',
  'warning',
  'link',
] as const;

/** The complete set of legal edge types, for runtime validation. */
export const EDGE_TYPES: readonly iEdgeType[] = ['happy', 'warning', 'error', 'default'] as const;

/** The complete set of legal directions, for runtime validation. */
export const DIRECTIONS: readonly iDirection[] = ['TD', 'BT', 'LR', 'RL'] as const;

/** A single node in the graph. */
export interface iFlowNode {
  /** Unique id within the graph; edges reference this. */
  id: string;
  /** Text shown in the node. */
  label: string;
  /** Semantic kind. */
  type: iNodeType;
  /** Optional secondary text shown in the rich node body. */
  description?: string;
  /** Arbitrary payload passed through to the (custom) node component. */
  data?: Record<string, unknown>;
}

/** A single directed edge in the graph. */
export interface iFlowEdge {
  /** Unique id within the graph. Generated by the parser if not authored. */
  id: string;
  /** Source node id. */
  from: string;
  /** Target node id. */
  to: string;
  /** Semantic kind. Defaults to 'default'. */
  type: iEdgeType;
  /** Optional edge label (e.g. 'yes' / 'no'). */
  label?: string;
}

/** The whole diagram. The single source of truth every layer consumes. */
export interface iFlowGraph {
  /** Stable id for the diagram. */
  id: string;
  /** Human-readable title. */
  name: string;
  /** Layout direction. */
  direction: iDirection;
  /** Every node. */
  nodes: iFlowNode[];
  /** Every edge. */
  edges: iFlowEdge[];
}

/** Narrowing helper: is `value` a legal node type? */
export function isNodeType(value: unknown): value is iNodeType {
  return typeof value === 'string' && (NODE_TYPES as readonly string[]).includes(value);
}

/** Narrowing helper: is `value` a legal edge type? */
export function isEdgeType(value: unknown): value is iEdgeType {
  return typeof value === 'string' && (EDGE_TYPES as readonly string[]).includes(value);
}

/** Narrowing helper: is `value` a legal direction? */
export function isDirection(value: unknown): value is iDirection {
  return typeof value === 'string' && (DIRECTIONS as readonly string[]).includes(value);
}
