#!/usr/bin/env node

// ────────────────────────────────────────────────────────────────
// DO NOT EDIT THIS FILE.
//
// COPY of source-of-truth at
//   ~/.claude/standards/scripts/ceremony-ship.mjs
//
// Local edits will be overwritten the next time
//   bash ~/.claude/standards/scripts/install-slice-gates.sh
// runs. Edit the ORIGINAL and re-install.
// ────────────────────────────────────────────────────────────────
/**
 * ceremony-ship.mjs — the whole ship ceremony in ONE command with
 * CAPPED output (CONTEXT_ECONOMY: the orchestrator gets step lines, never logs).
 *
 * @version 1
 *
 * Steps: verify chain -> stamp -> PR body (your draft + generated Standards
 * gates/compliance sections) -> draft gate -> push -> PR create -> CI poll
 * (when the standards-chain workflow exists) -> merge (MERGE COMMIT) -> pull main.
 *
 * Usage (from the web dir):
 *   node scripts/ceremony-ship.mjs --issue N --title "fix: ..." --body-file draft.md [--dry]
 * draft.md carries: ## Summary, ## Type of change, ## Test plan, ## Checklist.
 * Exit: 0 shipped (or dry-ok), 1 refused at any step (last lines quoted).
 */
import { spawnSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";

const arg = (n) => { const i = process.argv.indexOf(`--${n}`); return i === -1 ? null : process.argv[i + 1]; };
const DRY = process.argv.includes("--dry");
const issue = arg("issue"), title = arg("title"), bodyFile = arg("body-file");
if (!issue || !title || !bodyFile) { console.error("usage: ceremony-ship --issue N --title t --body-file f [--dry]"); process.exit(1); }
if (title.length > 65) { console.error(`x title is ${title.length} chars (max 65)`); process.exit(1); }

const sh = (cmd) => spawnSync("bash", ["-c", cmd], { encoding: "utf8" });
const step = (name, cmd) => {
  const r = sh(cmd);
  if (r.status !== 0) {
    const out = ((r.stderr || "") + (r.stdout || "")).trim().split("\n");
    console.error(`x ${name} FAILED - last lines:\n` + out.slice(-12).join("\n"));
    process.exit(1);
  }
  console.log(`+ ${name}`);
  return r;
};

const repo = sh("git rev-parse --show-toplevel").stdout.trim();
const branch = sh("git rev-parse --abbrev-ref HEAD").stdout.trim();
if (branch === "main") { console.error("x ship runs from a feat/fix branch, never main"); process.exit(1); }

step("chain (pnpm verify)", "pnpm verify");
step("stamp", "node scripts/verify/stamp-standards-met.mjs");
const block = step("standards block", "node scripts/generate/generate-pr-standards-block.mjs").stdout;

const draft = fs.readFileSync(path.resolve(bodyFile), "utf8");
const gates = "## Standards gates\n\n```\nverify-all: OK + pnpm verify EXIT 0 (chain re-run at push + in CI)\n```\n\n";
const marker = "## Test plan";
if (!draft.includes(marker)) { console.error("x draft missing ## Test plan"); process.exit(1); }
const body = draft.replace(marker, gates + block.trim() + "\n\n" + marker) + `\n\nCloses #${issue}\n`;
const bf = path.join(repo, ".git", "ship-body.md");
fs.writeFileSync(bf, body);
step("PR draft gate", `node "$(find scripts -name 'verify-pr-body-draft.mjs' | head -1)" ${bf}`);
if (DRY) { console.log("+ DRY RUN complete - stopped before push"); process.exit(0); }

step("push", `git push -u origin ${branch}`);
const pr = step("PR create", `gh pr create --title "${title.replace(/"/g, '\\"')}" --body-file ${bf} --base main --head ${branch}`).stdout.trim().split("\n").pop();
console.log(`  ${pr}`);

const hasCI = fs.existsSync(path.join(repo, ".github", "workflows", "standards-chain.yml"));
if (hasCI) {
  let ok = false;
  for (let i = 0; i < 20; i++) {
    spawnSync("sleep", ["45"]);
    const c = sh(`gh pr checks ${branch} 2>/dev/null | grep standards-chain | head -1`).stdout;
    if (/\bpass\b/.test(c)) { ok = true; break; }
    if (/\bfail\b/.test(c)) { console.error("x CI standards-chain FAILED - fix and re-ship"); process.exit(1); }
  }
  if (!ok) { console.error("x CI did not complete within 15 min - re-run ship after it finishes"); process.exit(1); }
  console.log("+ CI standards-chain green");
}
step("merge (merge commit)", `gh pr merge ${branch} --merge --delete-branch`);
step("sync main", "git checkout main && git pull origin main");
console.log("+ SHIPPED - stamp is on main; verify: git log --grep '100% standards met' -1");
