#!/usr/bin/env node

// ────────────────────────────────────────────────────────────────
// DO NOT EDIT THIS FILE.
//
// COPY of source-of-truth at
//   ~/.claude/standards/scripts/verify-all.mjs
//
// Local edits will be overwritten the next time
//   bash ~/.claude/standards/scripts/install-slice-gates.sh
// runs. Edit the ORIGINAL and re-install.
// ────────────────────────────────────────────────────────────────
// Aggregate runner for every verify-* gate. Exits 0 only when every
// individual gate exits 0. Used by `pnpm verify` (default fast chain;
// local iteration + pre-push hook) and `pnpm verify --full` (adds slower
// / live-API gates; CI gate + on-demand).
//
// Flags:
//   --full   include the heavy / live-API gates in SCRIPTS_FULL_ONLY.
//
// The "full" set runs every script in `SCRIPTS` plus every script in
// `SCRIPTS_FULL_ONLY`. The default set runs only `SCRIPTS`.
//
// Each entry is either a plain string (the script is plain `.mjs`,
// spawned with `node <script>`) OR an object `{ script, importTsx: true }`
// for scripts that dynamically import `.ts` modules — those need
// `node --import tsx` so tsx wires the TypeScript loader.

import { spawnSync } from "node:child_process";
import { join } from "node:path";

const ROOT = new URL("..", import.meta.url).pathname;
const FULL = process.argv.includes("--full");

/**
 * Default fast chain — every gate that runs in <1s, no network, no
 * heavy DB ops. Pre-push + every local invocation runs this.
 *
 * @type {Array<string | { script: string, importTsx: boolean }>}
 */
const SCRIPTS = [
  // 1. Presence + freshness lock (the standards-compliance.yaml gate).
  "scripts/verify/verify-standards-compliance.mjs",
  // 2–3, 6–10. Spec/doc/structure gate — consolidates seven sub-checks in
  //    one file (fail iff any fails; each keeps its own no-op-green
  //    short-circuit + exact exit codes / stderr): source-coverage (every
  //    src/ file owned by a __specs__/spec.yaml owns: list or exempt via
  //    .ignore.specs.yaml), no-padding-folders (no README-only padding
  //    folders in src/features/<name>/), flow-coverage (every exported
  //    behavior has a co-located flows/<kebab>.flow.{md,yaml}),
  //    no-stray-scaffolding (flows/ / specs/ / FLOWS.md / CODE_CONFIDENCE.md
  //    outside __specs__/ blocked), setup-headers (SETUP FILE. marker on
  //    architectural files, two-way), docs (spec.md shape, CODE_CONFIDENCE.md
  //    scorecard, flow-doc dual-shape policy), and manual-playbooks (every
  //    user-facing route/page folder ships a runnable __specs__/manual/*.md).
  "scripts/verify/verify-specs.mjs",
  // 11. Import / module boundaries — consolidates four boundary sub-checks
  //     (no-server-imports [G-CLIENT-SERVER-BOUNDARY], no-cross-feature-
  //     imports, no-undeclared-deps, firebase-boundary). Runs all by default
  //     (fail iff any fails); each preserves its own no-op-green short-circuit.
  "scripts/verify/verify-boundaries.mjs",
  // 12. RULE 0 Layer C — getDbSuperuser confined to migrate.ts + client.ts
  //     (G-RULE0-A). Activates in repos using Postgres + RLS.
  "scripts/verify-no-superuser-in-runtime/verify-no-superuser-in-runtime.mjs",
  // 14–15. Authz gate — consolidates two authz sub-checks (eslint-permission-
  //     rules [custom ESLint guards enforcing RULE 0 / permission-slug
  //     discipline at lint time] + tenant-indexes [every tenant-scoped table
  //     carries a tenant-leading index]). Runs both by default (fail iff any
  //     fails); each preserves its own no-op-green short-circuit + exit codes.
  "scripts/verify/verify-authz.mjs",
  // 18. Test-quality gate — consolidates five test-quality sub-checks
  //     (coverage-threshold, test-naming, e2e-db-safety, accessibility-
  //     wiring, no-theater-tests). Runs all by default (OR semantics);
  //     each preserves its own no-op-green short-circuit.
  "scripts/verify/verify-tests.mjs",
  // 4–5, 13, 19–34. Design-system UI-tier gate — one merged file collapsing the
  //     20 UI-tier sub-checks (fail iff any fails; each keeps its own no-op-green
  //     short-circuit + exact exit codes / output). Default run covers 19 sub-
  //     checks: ui-design-lock (Path 1), ui-components-compliance (folder shape +
  //     shade discipline), token discipline, state vocabulary, design-lock, spec
  //     completeness, research citation/depth, stakes honesty, storybook docs,
  //     composite composition + state propagation, page landmarks + state machine,
  //     cross-tier freshness, spec↔source drift, agent operability. No-op green
  //     until a repo grows src/components/ui / composites / pages. The heavy Path-2
  //     ui-screenshots-match-designs sub-check runs only under --full (see below).
  "scripts/verify/verify-component.mjs",
  // 35–38. Outside-in gate — one merged file collapsing the five outside-in
  //     sub-checks (fail iff any fails; each keeps its own no-op-green short-
  //     circuit + exact exit codes / output): journeys (outside-in journey
  //     catalog + bidirectional flow reconciliation + blind-traversal audit,
  //     USER_JOURNEYS.yaml), labs (flow<->labs reconciliation + open-feedback
  //     gate, LABS.yaml), requirements (user-locked requirements + derivation-
  //     cited assumption ledger, REQUIREMENTS_CONTRACT.yaml), site-blueprint
  //     (page-tier slices require the locked, airtight docs/site/ blueprint,
  //     SITE_BLUEPRINT.yaml), api-first (page-tier UI refused until every flow
  //     is E2E-mapped + mermaid-diagrammed in docs/site/MECHANICAL_COMPLETE.yaml,
  //     API_FIRST.yaml). No-op green until the repo grows the triggering shapes.
  "scripts/verify/verify-outside-in.mjs",
  // 41. Browser-validation receipt — a browser_validated stamp's manual-results
  //     record must be a real walk (ok:true + findings), not a stub
  //     (BROWSER_VALIDATION). No-op green when no stamps exist. Merged into the
  //     consolidated verify-stamps gate; invoked via --check to preserve the
  //     exact single-sub-check behavior the fast chain had before.
  { script: "scripts/verify/verify-stamps.mjs", args: ["--check", "browser-validation-receipt"] },
];

/**
 * Scripts that ONLY run in --full mode. Slower / live-API / git-history-
 * dependent checks the default chain skips to keep local iteration +
 * pre-push fast. CI + on-demand call `pnpm verify:full`.
 *
 * Reserved for: test-llm-fitness (LLM API), verify-migration-replay
 * (heavy pglite setup), future puppeteer walkthroughs.
 *
 * @type {Array<string | { script: string, importTsx: boolean }>}
 */
const SCRIPTS_FULL_ONLY = [
  // F1. Standards freshness — the deep git-history freshness pass, folded into
  //     verify-standards-compliance behind `--full`. One `git log` invocation
  //     per lock (slower than the mtime freshness in the default compliance
  //     run), so it runs only in --full mode to keep local iteration + pre-push
  //     fast. The default compliance run in SCRIPTS above still does shape +
  //     presence + mtime freshness.
  { script: "scripts/verify/verify-standards-compliance.mjs", args: ["--full"] },
  // F2. Runtime gate — two heavy live-runtime sub-checks in one file:
  //     migration-replay (applies every migration in order against a
  //     scratch database to prove the chain is replayable end-to-end) and
  //     dev-server-boots (spawns `pnpm dev`, asserts a 200/3xx on the dev
  //     URL within timeout + no error lines — catches "compiles fine, app
  //     doesn't start"). --full only because it hits a real DB + boots a
  //     real process.
  "scripts/verify/verify-runtime.mjs",
  // F3. UI screenshots match designs (Path 2) — Puppeteer drives each flow's
  //     manual.yaml steps to every declared state, screenshots, and asks the
  //     verifier agent to compare against the matching design PNG. BLOCKED
  //     (exit 2) when devDeps / design PNGs missing. A merged sub-check invoked
  //     via --check; --full only because it hits Puppeteer + the dev server.
  { script: "scripts/verify/verify-component.mjs", args: ["--check", "ui-screenshots-match-designs"] },
];

const TO_RUN = FULL ? [...SCRIPTS, ...SCRIPTS_FULL_ONLY] : SCRIPTS;

let failures = 0;
for (const entry of TO_RUN) {
  const rel = typeof entry === "string" ? entry : entry.script;
  const importTsx = typeof entry === "string" ? false : entry.importTsx;
  const extraArgs = typeof entry === "string" ? [] : (entry.args || []);
  const full = join(ROOT, rel);
  const args = [...(importTsx ? ["--import", "tsx"] : []), full, ...extraArgs];
  const res = spawnSync(process.execPath, args, {
    stdio: "inherit",
    cwd: ROOT,
  });
  if (res.status !== 0) failures += 1;
}

if (failures > 0) {
  process.stderr.write(`\nverify-all: ${failures} gate(s) failed\n`);
  process.exit(1);
}
const mode = FULL ? " (full)" : "";
process.stdout.write(
  `\nverify-all${mode}: OK (all ${String(TO_RUN.length)} gate(s) passed)\n`,
);

// Green receipt — the ONLY producer of the proof that "100% standards met" is
// real. stamp-standards-met.mjs and the commit-msg hook consume it; it is
// written exclusively here, exclusively on all-green.
try {
  const gitDir = spawnSync("git", ["rev-parse", "--git-dir"], { cwd: ROOT, encoding: "utf8" }).stdout?.trim();
  if (gitDir) {
    const { isAbsolute } = await import("node:path");
    const receiptPath = isAbsolute(gitDir) ? join(gitDir, "verify-receipt.json") : join(ROOT, gitDir, "verify-receipt.json");
    const { writeFileSync } = await import("node:fs");
    writeFileSync(receiptPath, JSON.stringify({ ts: new Date().toISOString(), gates: TO_RUN.length, full: FULL }));
    process.stdout.write(`verify-all: green receipt written (${String(TO_RUN.length)} gates)\n`);
  }
} catch { /* receipt is best-effort; gates already passed */ }
