#!/usr/bin/env node

// ────────────────────────────────────────────────────────────────
// DO NOT EDIT THIS FILE.
//
// COPY of source-of-truth at
//   ~/.claude/standards/scripts/verify-all.mjs
//
// Local edits will be overwritten the next time
//   bash ~/.claude/standards/scripts/install-slice-gates.sh
// runs. Edit the ORIGINAL and re-install.
// ────────────────────────────────────────────────────────────────
// Aggregate runner for every verify-* gate. Exits 0 only when every
// individual gate exits 0. Used by `pnpm verify` (default fast chain;
// local iteration + pre-push hook) and `pnpm verify --full` (adds slower
// / live-API gates; CI gate + on-demand).
//
// Flags:
//   --full   include the heavy / live-API gates in SCRIPTS_FULL_ONLY.
//
// The "full" set runs every script in `SCRIPTS` plus every script in
// `SCRIPTS_FULL_ONLY`. The default set runs only `SCRIPTS`.
//
// Each entry is either a plain string (the script is plain `.mjs`,
// spawned with `node <script>`) OR an object `{ script, importTsx: true }`
// for scripts that dynamically import `.ts` modules — those need
// `node --import tsx` so tsx wires the TypeScript loader.

import { spawnSync } from "node:child_process";
import { join } from "node:path";

const ROOT = new URL("..", import.meta.url).pathname;
const FULL = process.argv.includes("--full");

/**
 * Default fast chain — every gate that runs in <1s, no network, no
 * heavy DB ops. Pre-push + every local invocation runs this.
 *
 * @type {Array<string | { script: string, importTsx: boolean }>}
 */
const SCRIPTS = [
  // 1. Presence + freshness lock (the standards-compliance.yaml gate).
  "scripts/verify/verify-standards-compliance.mjs",
  // 2. Every src/ file owned by some __specs__/spec.yaml owns: list (or
  //    explicitly exempt via .ignore.specs.yaml).
  "scripts/verify/verify-source-coverage.mjs",
  // 3. No README-only padding folders inside src/features/<name>/.
  "scripts/verify/verify-no-padding-folders.mjs",
  // 4. UI design lock (Path 1) — every feature with invocation.type
  //    in (ui, server-action) (and not ui_design: not-applicable) has
  //    a __specs__/ui/<flow>.md per flow with the user-signed
  //    `<!-- ui-locked: YYYY-MM-DD -->` marker. "Design approved."
  "scripts/verify/verify-ui-design-locked.mjs",
  // 5. UI screenshots match designs (Path 2) — Puppeteer drives each
  //    flow's manual.yaml steps to every declared state, screenshots,
  //    and asks Claude vision API to compare against the matching
  //    design PNG. "Implementation matches the approved design."
  //    BLOCKED (exit 2) when ANTHROPIC_API_KEY missing or design PNG
  //    not yet exported.
  "scripts/verify-ui-screenshots-match-designs/verify-ui-screenshots-match-designs.mjs",
  // 6. Flow-doc coverage — every exported function/method has a
  //    co-located flows/<kebab>.flow.{md,yaml} doc.
  "scripts/verify-flow-coverage/verify-flow-coverage.mjs",
  // 7. Stray scaffolding — flows/, specs/, FLOWS.md, CODE_CONFIDENCE.md
  //    outside __specs__/ blocked.
  "scripts/verify-no-stray-scaffolding/verify-no-stray-scaffolding.mjs",
  // 8. Setup file headers — SETUP FILE. marker on architectural files
  //    (types.ts, schemas/, composition roots), two-way enforcement.
  "scripts/verify-setup-headers/verify-setup-headers.mjs",
  // 9. Unified docs validator — spec.md shape, CODE_CONFIDENCE.md
  //    scorecard, flow doc dual-shape policy.
  "scripts/verify-docs/verify-docs.mjs",
  // 10. Manual playbooks — every user-facing route folder has a manual
  //     playbook (3 shapes: __specs__/manual/<basename>.yaml,
  //     __manual__/<basename>.md, __manual__/<basename>.extension.md +
  //     <basename>.manual.md).
  "scripts/verify-manual-playbooks/verify-manual-playbooks.mjs",
  // 11. FE-never-imports-BE boundary (G-FRONTEND-BOUNDARY). Activates
  //     when frontend/+server/ workspace split is present.
  "scripts/verify-no-server-imports/verify-no-server-imports.mjs",
  // 12. RULE 0 Layer C — getDbSuperuser confined to migrate.ts + client.ts
  //     (G-RULE0-A). Activates in repos using Postgres + RLS.
  "scripts/verify-no-superuser-in-runtime/verify-no-superuser-in-runtime.mjs",
  // 13. UI components compliance — component folder shape + hardcoded
  //     Tailwind shade discipline + component location rules.
  "scripts/verify-ui-components-compliance/verify-ui-components-compliance.mjs",
  // 14. ESLint permission rules — custom ESLint plugin gates that enforce
  //     RULE 0 / permission-slug discipline at lint time.
  "scripts/verify-eslint-permission-rules/verify-eslint-permission-rules.mjs",
  // 15. Tenant indexes — every tenant-scoped table has the required
  //     composite indexes for fast per-tenant queries.
  "scripts/verify-tenant-indexes/verify-tenant-indexes.mjs",
  // 16. No undeclared deps — every import specifier traces to a
  //     declared dependency in the nearest package.json (deps /
  //     devDeps / peerDeps / Node built-in / workspace sibling /
  //     relative path / #imports alias). Hallucination defense.
  "scripts/verify-no-undeclared-deps/verify-no-undeclared-deps.mjs",
  // 17. No cross-feature imports — src/features/<A>/... can only
  //     reach src/features/<B>/ via B's public surface (index.ts).
  //     Feature-boundary discipline (G-FRONTEND-BOUNDARY's cousin).
  "scripts/verify-no-cross-feature-imports/verify-no-cross-feature-imports.mjs",
  // 18. No theater tests — detects trivial-true, empty-it, and
  //     negative-no-op test patterns that hit coverage without
  //     asserting behavior.
  "scripts/verify-no-theater-tests/verify-no-theater-tests.mjs",
  // 19–32. Design-system creation gates (COMPONENT / COMPOSITE / PAGE_CREATION).
  //     No-op cleanly until a repo grows src/components/ui / composites /
  //     pages; then enforce token discipline, state vocabulary, design-lock,
  //     spec completeness, research citation/depth, stakes honesty, composite
  //     composition + state propagation, page landmarks + state machine, and
  //     cross-tier freshness.
  "scripts/verify/verify-component-tokens.mjs",
  "scripts/verify/verify-component-state-vocab.mjs",
  "scripts/verify/verify-component-design-locked.mjs",
  "scripts/verify/verify-component-spec.mjs",
  "scripts/verify/verify-component-research-cited.mjs",
  "scripts/verify/verify-component-design-self-lock-eligible.mjs",
  "scripts/verify/verify-component-research-depth.mjs",
  "scripts/verify/verify-component-spec-matrix-completeness.mjs",
  "scripts/verify/verify-component-stakes-honest.mjs",
  "scripts/verify/verify-component-storybook-docs.mjs",
  "scripts/verify/verify-composite-composition.mjs",
  "scripts/verify/verify-composite-state-propagation.mjs",
  "scripts/verify/verify-page-landmarks.mjs",
  "scripts/verify/verify-page-state-machine.mjs",
  // Site blueprint gate — page-tier slices require the locked docs/site/
  // blueprint (SITE_BLUEPRINT.yaml). Green short-circuit when no page-tier
  // specs exist or ui_discipline: none.
  "scripts/verify/verify-site-blueprint.mjs",
  "scripts/verify/verify-cross-tier-freshness.mjs",
  // 33. Component spec ↔ source drift — refuses divergence between a
  //     component's spec.yaml and its source (tokens, classes, props).
  "scripts/verify/verify-component-spec-vs-source.mjs",
  // 34. Component agent operability — every component ships a
  //     browser-executable __specs__/manual/<flow>.md (debt-ledger aware).
  "scripts/verify/verify-component-agent-operability.mjs",
  // 35. E2E DB safety — e2e tests + seeds may only target local/e2e
  //     databases (E2E_TESTING.yaml.db_safety, mechanical).
  "scripts/verify/verify-e2e-db-safety.mjs",
  // 36. Test naming — path-derived test IDs: __tests__/ + __stories__/
  //     filename shapes, e2e scenario/flow folder contract (TEST_NAMING.yaml).
  "scripts/verify/verify-test-naming.mjs",
  // 37. API-first — page-tier UI refused until every flow is E2E-mapped +
  //     mermaid-diagrammed in docs/site/MECHANICAL_COMPLETE.yaml (API_FIRST.yaml).
  "scripts/verify/verify-api-first.mjs",
  // 38. Requirements contract — features require user-locked requirements +
  //     derivation-cited assumption ledger (REQUIREMENTS_CONTRACT.yaml).
  "scripts/verify/verify-requirements.mjs",
  // 38. Firebase boundary — server-only Admin SDK, banned client files,
  //     no NEXT_PUBLIC_ secrets, no email allowlists (GOOGLE_FIREBASE_STANDARDS).
  "scripts/verify/verify-firebase-boundary.mjs",
  // 39. Coverage threshold — the vitest config must gate coverage at 100%
  //     perFile (UNIT_COVERAGE); an unconfigured/lowered threshold is a defect.
  //     No-op green when the repo has no vitest config.
  "scripts/verify/verify-coverage-threshold.mjs",
  // 40. Accessibility wiring — a Storybook UI repo must wire the axe gate
  //     (verify:stories + .storybook/test-runner.ts) into pnpm verify
  //     (ACCESSIBILITY). No-op green when ui_discipline:none or no Storybook.
  "scripts/verify/verify-accessibility-wiring.mjs",
  // 41. Browser-validation receipt — a browser_validated stamp's manual-results
  //     record must be a real walk (ok:true + findings), not a stub
  //     (BROWSER_VALIDATION). No-op green when no stamps exist.
  "scripts/verify/verify-browser-validation-receipt.mjs",
];

/**
 * Scripts that ONLY run in --full mode. Slower / live-API / git-history-
 * dependent checks the default chain skips to keep local iteration +
 * pre-push fast. CI + on-demand call `pnpm verify:full`.
 *
 * Reserved for: test-llm-fitness (LLM API), verify-migration-replay
 * (heavy pglite setup), future puppeteer walkthroughs.
 *
 * @type {Array<string | { script: string, importTsx: boolean }>}
 */
const SCRIPTS_FULL_ONLY = [
  // F1. Standards freshness — git-history freshness check on every
  //     standards-compliance.yaml lock. One `git log` invocation per lock
  //     (slower than the shape-only verify-standards-compliance gate);
  //     runs only in --full mode to keep local iteration + pre-push fast.
  "scripts/verify-standards-freshness/verify-standards-freshness.mjs",
  // F2. Migration replay — applies every migration in order against a
  //     scratch database to prove the chain is replayable end-to-end.
  //     Heavy DB op; --full only.
  "scripts/verify-migration-replay/verify-migration-replay.mjs",
  // F3. Dev server boots — spawns `pnpm dev`, asserts a 200/3xx on the
  //     dev URL within timeout + no error lines in stdout. Catches
  //     "compiles fine, app doesn't start" (missing env vars, port
  //     collisions, broken composition roots). --full only because it
  //     boots a real process.
  "scripts/verify-dev-server-boots/verify-dev-server-boots.mjs",
];

const TO_RUN = FULL ? [...SCRIPTS, ...SCRIPTS_FULL_ONLY] : SCRIPTS;

let failures = 0;
for (const entry of TO_RUN) {
  const rel = typeof entry === "string" ? entry : entry.script;
  const importTsx = typeof entry === "string" ? false : entry.importTsx;
  const full = join(ROOT, rel);
  const args = importTsx ? ["--import", "tsx", full] : [full];
  const res = spawnSync(process.execPath, args, {
    stdio: "inherit",
    cwd: ROOT,
  });
  if (res.status !== 0) failures += 1;
}

if (failures > 0) {
  process.stderr.write(`\nverify-all: ${failures} gate(s) failed\n`);
  process.exit(1);
}
const mode = FULL ? " (full)" : "";
process.stdout.write(
  `\nverify-all${mode}: OK (all ${String(TO_RUN.length)} gate(s) passed)\n`,
);

// Green receipt — the ONLY producer of the proof that "100% standards met" is
// real. stamp-standards-met.mjs and the commit-msg hook consume it; it is
// written exclusively here, exclusively on all-green.
try {
  const gitDir = spawnSync("git", ["rev-parse", "--git-dir"], { cwd: ROOT, encoding: "utf8" }).stdout?.trim();
  if (gitDir) {
    const { isAbsolute } = await import("node:path");
    const receiptPath = isAbsolute(gitDir) ? join(gitDir, "verify-receipt.json") : join(ROOT, gitDir, "verify-receipt.json");
    const { writeFileSync } = await import("node:fs");
    writeFileSync(receiptPath, JSON.stringify({ ts: new Date().toISOString(), gates: TO_RUN.length, full: FULL }));
    process.stdout.write(`verify-all: green receipt written (${String(TO_RUN.length)} gates)\n`);
  }
} catch { /* receipt is best-effort; gates already passed */ }
