/**

// ────────────────────────────────────────────────────────────────
// DO NOT EDIT THIS FILE.
//
// COPY of source-of-truth at
//   ~/.claude/standards/scripts/verify/_walker-receipt.mjs
//
// Local edits will be overwritten the next time
//   bash ~/.claude/standards/scripts/install-slice-gates.sh
// runs. Edit the ORIGINAL and re-install.
// ────────────────────────────────────────────────────────────────
 * _walker-receipt — sign + verify helper for browser-validation walk receipts
 * (BROWSER_VALIDATION.yaml). Shared by the ui-walker (to SIGN a green walk) and
 * verify-browser-validation-receipt.mjs (to VERIFY).
 *
 * Threat model — read before trusting this:
 *   Prevents: (a) TAMPER — editing a signed record (flip ok, backdate, swap
 *   findings) breaks the signature; (b) CASUAL FORGERY — a stub can no longer
 *   pass, the record must go through the keyed signing routine with full per-step
 *   observations bound into the signature.
 *   Does NOT prevent: a session that deliberately calls sign() with fabricated
 *   observations — the key is machine-local, so the signature proves "signed by
 *   something with the key", not "a browser actually rendered". True walk-
 *   provenance requires the Chrome extension to emit the receipt itself (outside
 *   the model's control) — the ceiling, not buildable here.
 *
 * Key: machine-local, git-ignored, never committed. Default
 *   ~/.claude/.walker-signing-key (override with env WALKER_KEY_PATH for tests).
 *   Created on first sign; read on verify. Because walk records are LOCAL evidence
 *   (BROWSER_VALIDATION.yaml.ci_split), signature verification runs only where the
 *   records exist (local), never in CI.
 */
import { createHmac, randomBytes } from "node:crypto";
import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { homedir } from "node:os";

// The exact fields bound by the signature. Editing ANY of them post-sign breaks it.
export const SIGNED_FIELDS = ["v", "flow", "nonce", "walkedAt", "ok", "observed"];

export function keyPath() {
  return process.env.WALKER_KEY_PATH || join(homedir(), ".claude", ".walker-signing-key");
}

export function loadKey() {
  const p = keyPath();
  try { return readFileSync(p, "utf8").trim() || null; } catch { return null; }
}

export function loadOrCreateKey() {
  const p = keyPath();
  const existing = loadKey();
  if (existing) return existing;
  const key = randomBytes(32).toString("hex");
  try { mkdirSync(dirname(p), { recursive: true }); } catch { /* dir may exist */ }
  writeFileSync(p, key + "\n", { mode: 0o600 });
  return key;
}

// Stable, key-sorted JSON so the signer and verifier canonicalize identically.
export function canonical(value) {
  if (Array.isArray(value)) return "[" + value.map(canonical).join(",") + "]";
  if (value && typeof value === "object") {
    return "{" + Object.keys(value).sort().map((k) => JSON.stringify(k) + ":" + canonical(value[k])).join(",") + "}";
  }
  return JSON.stringify(value ?? null);
}

function pickSigned(obj) {
  const out = {};
  for (const k of SIGNED_FIELDS) out[k] = obj[k];
  return out;
}

export function sign(signedBody, key) {
  return createHmac("sha256", key).update(canonical(pickSigned(signedBody))).digest("hex");
}

/**
 * Build a signed walk receipt (walker side).
 * @param {{flow:string, observed:Array, ok:boolean, walkedAt:string, walker?:string, nonce?:string}} p
 * @param {string} key
 */
export function buildReceipt(p, key) {
  const body = {
    v: 1,
    flow: p.flow,
    nonce: p.nonce || randomBytes(9).toString("hex"),
    walkedAt: p.walkedAt,
    ok: p.ok,
    observed: p.observed,
  };
  return { ...body, walker: p.walker || "ui-walker", signature: sign(body, key) };
}

/**
 * Verify a receipt's signature (gate side).
 * @returns {{ok:boolean, reason?:string}}
 */
export function verifyReceipt(record, key) {
  if (!record || typeof record !== "object") return { ok: false, reason: "record is not a JSON object" };
  if (typeof record.signature !== "string" || !record.signature) return { ok: false, reason: "unsigned — walker receipts must carry a signature (re-walk to sign)" };
  if (!key) return { ok: false, reason: "receipt is signed but this machine has no walker key to verify it (WALKER_KEY_PATH / ~/.claude/.walker-signing-key)" };
  for (const f of SIGNED_FIELDS) {
    if (!(f in record)) return { ok: false, reason: `signed field "${f}" missing — receipt is malformed or hand-written` };
  }
  const expect = sign(record, key);
  if (expect !== record.signature) return { ok: false, reason: "signature INVALID — the record was edited after signing, or signed with a different key" };
  return { ok: true };
}
