#!/usr/bin/env node

// ────────────────────────────────────────────────────────────────
// DO NOT EDIT THIS FILE.
//
// COPY of source-of-truth at
//   ~/.claude/standards/scripts/verify/verify-mode.mjs
//
// Local edits will be overwritten the next time
//   bash ~/.claude/standards/scripts/install-slice-gates.sh
// runs. Edit the ORIGINAL and re-install.
// ────────────────────────────────────────────────────────────────
// Verifier-mode dispatcher — ONE entry point for every verifier mode.
//
//   node verify-mode.mjs <letter-or-name> [args]
//
// Modes (all previously separate verify-mode-* folders, now collapsed here):
//   a                 slice-on-commit verify — STAMPS the lock on green
//   b                 HEAD-only stamp + freshness check (read-only)
//   b5                uncommitted-working-tree stamp + freshness (read-only)
//   c                 push-time slice re-verify (invokes Mode A per slice)
//   d                 push-time stamp + freshness for slices touched vs origin (read-only)
//   e                 entire-repo stamp update (invokes Mode A per slice)
//   f                 entire-repo stamp + freshness check (read-only)
//   inspect           read-only walk of every lock — ALWAYS exits 0, never stamps
//   pristine          typecheck/build/lint/unit/e2e chain (read-only)
//   cleanup-orphans   report-only orphan-lock detector — ALWAYS exits 0
//   verify-all        feature-by-feature deep ceremony — unlocks-on-fail, relocks via Mode A
//
// Read-only modes (b, b5, c, d, e, f, inspect, cleanup-orphans, pristine)
// NEVER write a lock. Mode a and verify-all DO stamp. inspect always exits 0.
//
// Every mode's logic is exported as `main<Mode>({ rootDir, ...io })` so the
// selftest net can drive it in-process. Shared lock/freshness helpers are
// sourced from ../lib/locks.mjs (the single source).

import { spawnSync } from "node:child_process";
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

import { blastRadius } from "../lib/blast-radius.mjs";
import { getChangedPaths, findRepoRoot } from "../lib/changed-paths.mjs";
import {
  checkFreshness,
  checkLockShape,
  defaultGitLastCommit,
  findAllLocks,
  locksFromChangedPaths,
  parseScalarFields,
  slicesFromChangedPaths,
  slicesFromLocks,
  stampLock,
  unlockLock,
} from "../lib/locks.mjs";
import {
  extractFencedYaml,
  resolveLockFile,
  resolveSpecFile,
} from "../lib/load-spec.mjs";

const __filename = fileURLToPath(import.meta.url);
const SCRIPT_DIR = dirname(__filename);
// scripts/verify → up2 = the repo/web root (matches every gate's ROOT).
const ROOT = resolve(SCRIPT_DIR, "..", "..");
const DISPATCHER = resolve(SCRIPT_DIR, "verify-mode.mjs");
const VERIFY_ALL_GATE = resolve(ROOT, "scripts/verify-all.mjs");

// Re-export the shared helpers the selftests import from the dispatcher.
export {
  checkLockShape,
  locksFromChangedPaths,
  slicesFromChangedPaths,
  slicesFromLocks,
};

// ─────────────────────────────────────────────────────────────────────────
// Mode A — slice-on-commit verifier. STAMPS the lock on green.
// ─────────────────────────────────────────────────────────────────────────

/** @typedef {{ name: string, status: "PASS" | "FAIL" | "SKIP", detail: string }} iGateResult */

/** @param {string} folder @returns {boolean} */
export function hasSpecsFolder(folder) {
  return existsSync(join(folder, "__specs__"));
}

/** @param {string} folder @returns {boolean} */
export function hasTestsFolder(folder) {
  return existsSync(join(folder, "__tests__"));
}

/**
 * @param {string} sliceAbs
 * @param {{ sliceTests?: string[], callerTests?: string[], spawn: typeof spawnSync, cwd?: string }} io
 * @returns {iGateResult}
 */
export function runScopedVitest(sliceAbs, io) {
  const { spawn } = io;
  const cwd = io.cwd ?? ROOT;
  /** @type {string[]} */
  const testPaths = [];
  if (io.sliceTests && io.sliceTests.length > 0) {
    testPaths.push(...io.sliceTests);
  } else if (hasTestsFolder(sliceAbs)) {
    testPaths.push(join(sliceAbs, "__tests__"));
  }
  if (io.callerTests && io.callerTests.length > 0) {
    testPaths.push(...io.callerTests);
  }
  if (testPaths.length === 0) {
    return {
      name: "vitest (slice + caller tests)",
      status: "SKIP",
      detail: `no tests in slice or blast radius of ${relative(ROOT, sliceAbs) || "slice"}`,
    };
  }
  const res = spawn("pnpm", ["vitest", "run", ...testPaths], { cwd, encoding: "utf8" });
  if (res.error) {
    return { name: "vitest (slice + caller tests)", status: "FAIL", detail: `spawn error: ${res.error.message}` };
  }
  return {
    name: "vitest (slice + caller tests)",
    status: res.status === 0 ? "PASS" : "FAIL",
    detail: res.status === 0
      ? `${String(testPaths.length)} test path(s) passed`
      : (res.stdout ?? "") + (res.stderr ?? ""),
  };
}

/**
 * @param {string} sliceAbs
 * @param {{ callers?: string[], spawn: typeof spawnSync, cwd?: string }} io
 * @returns {iGateResult}
 */
export function runScopedLint(sliceAbs, io) {
  const { spawn } = io;
  const cwd = io.cwd ?? ROOT;
  const args = ["eslint", sliceAbs, ...(io.callers ?? [])];
  const res = spawn("pnpm", args, { cwd, encoding: "utf8" });
  if (res.error) {
    return { name: "eslint (slice + callers)", status: "FAIL", detail: `spawn error: ${res.error.message}` };
  }
  return {
    name: "eslint (slice + callers)",
    status: res.status === 0 ? "PASS" : "FAIL",
    detail: res.status === 0
      ? `slice + ${String(io.callers?.length ?? 0)} caller(s) clean`
      : (res.stdout ?? "") + (res.stderr ?? ""),
  };
}

/**
 * @param {{ spawn: typeof spawnSync, cwd?: string }} io
 * @returns {iGateResult}
 */
export function runTypecheck(io) {
  const { spawn } = io;
  const cwd = io.cwd ?? ROOT;
  const res = spawn("pnpm", ["typecheck"], { cwd, encoding: "utf8" });
  if (res.error) {
    return { name: "typecheck (project-wide)", status: "FAIL", detail: `spawn error: ${res.error.message}` };
  }
  return {
    name: "typecheck (project-wide)",
    status: res.status === 0 ? "PASS" : "FAIL",
    detail: res.status === 0 ? "tsc clean" : (res.stdout ?? "") + (res.stderr ?? ""),
  };
}

/**
 * Drop `grep -rn` output lines whose content is a comment (JSDoc or `//`).
 * @param {string} stdout
 * @returns {string}
 */
export function dropCommentLines(stdout) {
  if (!stdout) return "";
  /** @type {string[]} */
  const kept = [];
  for (const line of stdout.split(/\r?\n/)) {
    if (line === "") continue;
    const firstColon = line.indexOf(":");
    if (firstColon < 0) { kept.push(line); continue; }
    const secondColon = line.indexOf(":", firstColon + 1);
    if (secondColon < 0) { kept.push(line); continue; }
    const content = line.slice(secondColon + 1);
    const trimmed = content.replace(/^\s+/, "");
    if (
      trimmed.startsWith("*/") ||
      trimmed.startsWith("/*") ||
      trimmed.startsWith("//") ||
      trimmed.startsWith("*")
    ) {
      continue;
    }
    kept.push(line);
  }
  return kept.join("\n");
}

/**
 * @param {string} sliceAbs
 * @returns {Array<{ desc: string, args: string[], filterComments: boolean }>}
 */
export function buildBoundaryGrepChecks(sliceAbs) {
  return [
    {
      desc: "direct DB-driver imports outside src/db/",
      args: [
        "-rn", "-E",
        "from\\s+['\"](drizzle-orm|postgres-js|postgres|pg)([/'\"])",
        sliceAbs, "--include=*.ts", "--exclude-dir=__tests__",
      ],
      filterComments: true,
    },
    {
      desc: "@ts-ignore / @ts-expect-error outside __tests__/",
      args: ["-rn", "-E", "@ts-ignore|@ts-expect-error", sliceAbs, "--include=*.ts", "--exclude-dir=__tests__"],
      filterComments: false,
    },
    {
      desc: "AuthorizedPrincipal cast bypass",
      args: ["-rn", "-E", "as AuthorizedPrincipal|as unknown as AuthorizedPrincipal", sliceAbs, "--include=*.ts", "--exclude-dir=__tests__"],
      filterComments: true,
    },
  ];
}

/**
 * @param {string} sliceAbs
 * @param {{ spawn: typeof spawnSync }} io
 * @returns {iGateResult}
 */
export function runBoundaryGreps(sliceAbs, io) {
  const { spawn } = io;
  const checks = buildBoundaryGrepChecks(sliceAbs);
  /** @type {string[]} */
  const offenders = [];
  const sliceRel = relative(ROOT, sliceAbs);
  const isDbSlice = sliceRel.startsWith("src/db/") || sliceRel === "src/db" || sliceRel.includes("/db/") || sliceRel.endsWith("/db");
  const isMintSlice = sliceRel.startsWith("src/lib/authz/mint") || sliceRel.includes("/lib/authz/mint");
  for (const c of checks) {
    const res = spawn("grep", c.args, { encoding: "utf8" });
    if (res.error) continue;
    const allowDbDriverImport = c.desc.includes("DB-driver imports") && isDbSlice;
    const allowCast = c.desc.includes("AuthorizedPrincipal cast") && isMintSlice;
    if (res.status === 0 && !allowDbDriverImport && !allowCast) {
      const raw = res.stdout ?? "";
      const filtered = c.filterComments ? dropCommentLines(raw) : raw.replace(/\s+$/, "");
      if (filtered !== "") offenders.push(`${c.desc}:\n${filtered}`);
    }
  }
  if (offenders.length === 0) {
    return { name: "PRIMARY RULE boundary greps", status: "PASS", detail: "no forbidden patterns in slice" };
  }
  return { name: "PRIMARY RULE boundary greps", status: "FAIL", detail: offenders.join("\n\n") };
}

/**
 * Read + shape-check the slice's lock (Mode-A iGateResult shape, distinct from
 * lib's boolean checkLockShape — this one carries lockPath + lastValidatedMs).
 * @param {string} sliceAbs
 * @param {{ readFile?: (p: string) => string }} [io]
 * @returns {iGateResult & { lockPath?: string, lastValidatedMs?: number }}
 */
export function checkLockShapeGate(sliceAbs, io = {}) {
  const readFile = io.readFile ?? ((p) => readFileSync(p, "utf8"));
  // Dual-format: standards-compliance.md (fenced block) wins, else legacy .yaml.
  const lockPath = resolveLockFile(join(sliceAbs, "__specs__"));
  if (!existsSync(lockPath)) {
    return { name: "lock shape", status: "FAIL", detail: `no lock file at ${lockPath}` };
  }
  /** @type {string} */
  let contents;
  try {
    contents = readFile(lockPath);
    if (lockPath.endsWith(".md")) contents = extractFencedYaml(contents) ?? "";
  } catch (err) {
    return { name: "lock shape", status: "FAIL", detail: `cannot read lock: ${err instanceof Error ? err.message : String(err)}` };
  }
  const fields = parseScalarFields(contents);
  if (fields["status"] !== "locked") {
    return { name: "lock shape", status: "FAIL", detail: `status='${fields["status"] ?? ""}'; expected 'locked'` };
  }
  if (fields["verified"] !== "100%") {
    return { name: "lock shape", status: "FAIL", detail: `verified='${fields["verified"] ?? ""}'; expected '100%'` };
  }
  const stamp = fields["last_validated"] ?? "";
  const iso = /^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}(?:\.[0-9]+)?Z$/;
  if (!iso.test(stamp)) {
    return { name: "lock shape", status: "FAIL", detail: `last_validated='${stamp}'; expected ISO-8601 UTC` };
  }
  const ms = Date.parse(stamp);
  if (Number.isNaN(ms)) {
    return { name: "lock shape", status: "FAIL", detail: `last_validated='${stamp}' did not parse` };
  }
  return { name: "lock shape", status: "PASS", detail: `locked + 100% + last_validated=${stamp}`, lockPath, lastValidatedMs: ms };
}

/**
 * @param {Array<iGateResult>} results
 * @param {string} sliceRel
 * @param {string | null} stampedIso
 * @returns {string}
 */
export function formatReportA(results, sliceRel, stampedIso) {
  const lines = [`# Mode A — slice: ${sliceRel}`, ""];
  for (const r of results) {
    lines.push(`- ${r.name}: ${r.status}`);
    if (r.status !== "PASS") {
      lines.push(`    detail: ${r.detail.split("\n").slice(0, 5).join("\n             ")}`);
    }
  }
  const failed = results.some((r) => r.status === "FAIL");
  lines.push("");
  lines.push(`Verdict: ${failed ? "NOT SHIPPABLE" : "SHIPPABLE"}`);
  if (!failed && stampedIso) lines.push(`Lock stamped: last_validated = ${stampedIso}`);
  return lines.join("\n");
}

/**
 * @param {string} slicePath relative or absolute
 * @param {{
 *   rootDir?: string, skipTypecheck?: boolean, skipStamp?: boolean,
 *   spawn?: typeof spawnSync, readFile?: (p: string) => string,
 *   writeFile?: (p: string, c: string) => void, now?: () => Date,
 *   blastRadius?: { sliceTests: string[], callerTests: string[], callers: string[] },
 *   write?: (s: string) => void,
 * }} [io]
 * @returns {{ exitCode: 0 | 1, results: iGateResult[], stampedIso: string | null }}
 */
export function mainA(slicePath, io = {}) {
  const rootDir = io.rootDir ?? ROOT;
  const write = io.write ?? ((s) => process.stdout.write(s));
  const spawn = io.spawn ?? spawnSync;
  const sliceAbs = resolve(rootDir, slicePath);
  const sliceRel = relative(rootDir, sliceAbs) || ".";

  /** @type {iGateResult[]} */
  const results = [];

  if (!existsSync(sliceAbs)) {
    results.push({ name: "slice path", status: "FAIL", detail: `does not exist: ${sliceAbs}` });
    write(formatReportA(results, sliceRel, null) + "\n");
    return { exitCode: 1, results, stampedIso: null };
  }
  if (!hasSpecsFolder(sliceAbs)) {
    results.push({ name: "slice __specs__", status: "FAIL", detail: `missing __specs__/ in ${sliceRel}` });
    write(formatReportA(results, sliceRel, null) + "\n");
    return { exitCode: 1, results, stampedIso: null };
  }

  const lockResult = checkLockShapeGate(sliceAbs, { readFile: io.readFile });
  results.push(lockResult);

  if (lockResult.status === "PASS") {
    unlockLock(/** @type {string} */ (lockResult.lockPath), { readFile: io.readFile, writeFile: io.writeFile });
  }

  const radius = io.blastRadius ?? blastRadius(sliceAbs, rootDir, { spawn });
  const ioForChild = { spawn, cwd: rootDir };
  results.push(runScopedVitest(sliceAbs, { ...ioForChild, sliceTests: radius.sliceTests, callerTests: radius.callerTests }));
  results.push(runScopedLint(sliceAbs, { ...ioForChild, callers: radius.callers }));
  if (!io.skipTypecheck) results.push(runTypecheck(ioForChild));
  results.push(runBoundaryGreps(sliceAbs, { spawn }));

  const failed = results.some((r) => r.status === "FAIL");
  /** @type {string | null} */
  let stampedIso = null;
  if (!failed && !io.skipStamp && lockResult.lockPath) {
    stampedIso = stampLock(lockResult.lockPath, { readFile: io.readFile, writeFile: io.writeFile, now: io.now });
  }

  write(formatReportA(results, sliceRel, stampedIso) + "\n");
  return { exitCode: failed ? 1 : 0, results, stampedIso };
}

// ─────────────────────────────────────────────────────────────────────────
// Changed-path adapters for the read-only stamp/freshness modes.
// ─────────────────────────────────────────────────────────────────────────

/**
 * Absolute paths of every file changed in HEAD vs HEAD~1 (root commit → all).
 * @param {{ cwd?: string, exec?: (file: string, args: string[], opts: { cwd: string }) => string }} [io]
 * @returns {string[]}
 */
export function getHeadChangedPaths(io = {}) {
  const cwd = io.cwd ?? process.cwd();
  const exec = io.exec ?? ((file, args, opts) => execFileSync(file, args, opts).toString());
  /** @type {string} */
  let stdout;
  try {
    stdout = exec("git", ["diff-tree", "--no-commit-id", "--name-only", "-r", "HEAD"], { cwd });
  } catch {
    return [];
  }
  const repoRoot = findRepoRoot(cwd, spawnSync) ?? cwd;
  return stdout
    .split(/\r?\n/)
    .map((s) => s.trim())
    .filter((s) => s.length > 0)
    .map((rel) => resolve(repoRoot, rel));
}

/**
 * Working-tree changes vs HEAD (staged + unstaged tracked + untracked-not-ignored).
 * @param {{ cwd?: string, exec?: (file: string, args: string[], opts: { cwd: string }) => string }} [io]
 * @returns {string[]}
 */
export function getWorkingTreeChangedPaths(io = {}) {
  const cwd = io.cwd ?? process.cwd();
  const exec = io.exec ?? ((file, args, opts) => execFileSync(file, args, opts).toString());
  /** @type {string} */
  let stdout;
  try {
    stdout = exec("git", ["status", "--porcelain=v1", "--untracked-files=normal"], { cwd });
  } catch {
    return [];
  }
  const repoRoot = findRepoRoot(cwd, spawnSync) ?? cwd;
  /** @type {Set<string>} */
  const paths = new Set();
  for (const raw of stdout.split(/\r?\n/)) {
    const line = raw.trimEnd();
    if (line.length < 4) continue;
    const tail = line.slice(3);
    const arrow = tail.indexOf(" -> ");
    const rel = arrow === -1 ? tail : tail.slice(arrow + 4);
    if (rel.length === 0) continue;
    paths.add(resolve(repoRoot, rel));
  }
  return [...paths];
}

/**
 * Shared shape+freshness scan over a set of locks. Used by Modes B, B5, D, F.
 * @param {string[]} locks
 * @param {string} rootDir
 * @param {string} label mode label, e.g. "verify-mode-b"
 * @param {string} noneMsg message when no locks resolve
 * @param {{ gitLastCommit?: (folder: string, lockFile: string) => string | null, readFile?: (p: string) => string, write: (s: string) => void, writeErr: (s: string) => void }} io
 * @returns {{ exitCode: 0 | 1, locksChecked: string[], failures: Array<{ lock: string, gate: "shape" | "freshness", reason: string }> }}
 */
function scanLocks(locks, rootDir, label, noneMsg, io) {
  const { write, writeErr } = io;
  const gitLastCommit = io.gitLastCommit ?? defaultGitLastCommit;
  if (locks.length === 0) {
    write(`${label}: ${noneMsg}\n`);
    return { exitCode: 0, locksChecked: [], failures: [] };
  }
  /** @type {Array<{ lock: string, gate: "shape" | "freshness", reason: string }>} */
  const failures = [];
  for (const lock of locks) {
    const shape = checkLockShape(lock, { readFile: io.readFile });
    if (!shape.ok) { failures.push({ lock, gate: "shape", reason: shape.reason }); continue; }
    const fresh = checkFreshness(lock, shape.lastValidatedMs, { gitLastCommit });
    if (!fresh.ok) failures.push({ lock, gate: "freshness", reason: `${fresh.reason} — ${fresh.detail}` });
  }
  if (failures.length === 0) {
    write(`${label}: OK (${String(locks.length)} lock(s) locked + verified=100% + fresh vs git history)\n`);
    return { exitCode: 0, locksChecked: locks, failures: [] };
  }
  writeErr(`${label}: ${String(failures.length)} lock(s) failed\n`);
  for (const f of failures) {
    writeErr(`  - ${relative(rootDir, f.lock)} [${f.gate}]\n`);
    writeErr(`      reason: ${f.reason}\n`);
  }
  return { exitCode: 1, locksChecked: locks, failures };
}

/**
 * Mode B — HEAD-only stamp + freshness check (read-only).
 * @param {{ rootDir?: string, getChanged?: () => string[], gitLastCommit?: (folder: string, lockFile: string) => string | null, write?: (s: string) => void, writeErr?: (s: string) => void, readFile?: (p: string) => string }} [io]
 */
export function mainB(io = {}) {
  const rootDir = io.rootDir ?? ROOT;
  const getChanged = io.getChanged ?? (() => getHeadChangedPaths({ cwd: rootDir }));
  const write = io.write ?? ((s) => process.stdout.write(s));
  const writeErr = io.writeErr ?? ((s) => process.stderr.write(s));
  const changed = getChanged();
  if (changed.length === 0) {
    write("verify-mode-b: HEAD has no changed paths — nothing to stamp-check.\n");
    return { exitCode: 0, locksChecked: [], failures: [] };
  }
  const locks = locksFromChangedPaths(changed, rootDir);
  if (locks.length > 0) write(`verify-mode-b: stamp-checking ${String(locks.length)} lock(s) for slices touched by HEAD\n`);
  return scanLocks(locks, rootDir, "verify-mode-b", "HEAD's changed paths don't resolve to any spec'd slice — nothing to stamp-check.", { ...io, write, writeErr });
}

/**
 * Mode B.5 — uncommitted-working-tree stamp + freshness check (read-only).
 * @param {Parameters<typeof mainB>[0]} [io]
 */
export function mainB5(io = {}) {
  const rootDir = io.rootDir ?? ROOT;
  const getChanged = io.getChanged ?? (() => getWorkingTreeChangedPaths({ cwd: rootDir }));
  const write = io.write ?? ((s) => process.stdout.write(s));
  const writeErr = io.writeErr ?? ((s) => process.stderr.write(s));
  const changed = getChanged();
  if (changed.length === 0) {
    write("verify-mode-b5: working tree is clean — nothing to stamp-check.\n");
    return { exitCode: 0, locksChecked: [], failures: [] };
  }
  const locks = locksFromChangedPaths(changed, rootDir);
  if (locks.length > 0) write(`verify-mode-b5: stamp-checking ${String(locks.length)} lock(s) for slices with uncommitted changes\n`);
  return scanLocks(locks, rootDir, "verify-mode-b5", "working-tree changes don't resolve to any spec'd slice — nothing to stamp-check.", { ...io, write, writeErr });
}

/**
 * Mode D — push-time stamp + freshness for slices touched vs origin (read-only).
 * @param {{ rootDir?: string, getChanged?: (baseRef?: string) => string[], readFile?: (p: string) => string, gitLastCommit?: (folder: string, lockFile: string) => string | null, write?: (s: string) => void, writeErr?: (s: string) => void }} [io]
 */
export function mainD(io = {}) {
  const rootDir = io.rootDir ?? ROOT;
  const getChanged = io.getChanged ?? ((baseRef) => getChangedPaths(baseRef, { cwd: rootDir }));
  const write = io.write ?? ((s) => process.stdout.write(s));
  const writeErr = io.writeErr ?? ((s) => process.stderr.write(s));
  const changed = getChanged("origin/master");
  if (changed.length === 0) {
    write("verify-mode-d: no changed paths against origin/master — nothing to stamp-check.\n");
    return { exitCode: 0, locksChecked: [], failures: [] };
  }
  const locks = locksFromChangedPaths(changed, rootDir);
  if (locks.length > 0) write(`verify-mode-d: stamp-checking ${String(locks.length)} lock(s) for slices in this push\n`);
  return scanLocks(locks, rootDir, "verify-mode-d", "changed paths don't resolve to any spec'd slice — nothing to stamp-check.", { ...io, write, writeErr });
}

/**
 * Mode F — entire-repo stamp + freshness check (read-only).
 * @param {{ rootDir?: string, findLocks?: (root: string) => string[], gitLastCommit?: (folder: string, lockFile: string) => string | null, write?: (s: string) => void, writeErr?: (s: string) => void, readFile?: (p: string) => string }} [io]
 */
export function mainF(io = {}) {
  const rootDir = io.rootDir ?? ROOT;
  const findLocks = io.findLocks ?? findAllLocks;
  const write = io.write ?? ((s) => process.stdout.write(s));
  const writeErr = io.writeErr ?? ((s) => process.stderr.write(s));
  const locks = findLocks(rootDir);
  if (locks.length === 0) {
    write("verify-mode-f: no locks found in the repo — nothing to stamp-check.\n");
    return { exitCode: 0, locksChecked: [], failures: [] };
  }
  write(`verify-mode-f: stamp-checking ${String(locks.length)} lock(s) across the entire repo\n`);
  return scanLocks(locks, rootDir, "verify-mode-f", "no locks found in the repo — nothing to stamp-check.", { ...io, write, writeErr });
}

// ─────────────────────────────────────────────────────────────────────────
// Mode C / Mode E — invoke Mode A per slice, aggregate verdicts.
// ─────────────────────────────────────────────────────────────────────────

/**
 * @param {string[]} slices
 * @param {string} rootDir
 * @param {string} label
 * @param {{ spawn: typeof spawnSync, execPath: string, dispatcher: string, write: (s: string) => void, writeErr: (s: string) => void }} io
 * @returns {{ exitCode: 0 | 1, perSliceStatus: Array<{ slice: string, status: number }> }}
 */
function runModeAPerSlice(slices, rootDir, label, io) {
  const { spawn, execPath, dispatcher, write, writeErr } = io;
  /** @type {Array<{ slice: string, status: number }>} */
  const perSliceStatus = [];
  let aggregateExit = 0;
  for (const slice of slices) {
    const rel = relative(rootDir, slice);
    write(`\n--- slice: ${rel} ---\n`);
    const res = spawn(execPath, [dispatcher, "a", slice], { cwd: rootDir, encoding: "utf8" });
    if (res.stdout) write(res.stdout);
    if (res.stderr) writeErr(res.stderr);
    const status = res.status ?? 1;
    perSliceStatus.push({ slice, status });
    if (status !== 0) aggregateExit = 1;
  }
  const passed = perSliceStatus.filter((s) => s.status === 0).length;
  const failed = perSliceStatus.length - passed;
  write(`\n${label}: ${String(passed)}/${String(perSliceStatus.length)} slices PASS; ${String(failed)} FAIL\n`);
  return { exitCode: aggregateExit === 0 ? 0 : 1, perSliceStatus };
}

/**
 * Mode C — push-time slice re-verify (invokes Mode A per touched slice).
 * @param {{ spawn?: typeof spawnSync, execPath?: string, rootDir?: string, getChanged?: (baseRef?: string) => string[], dispatcher?: string, write?: (s: string) => void, writeErr?: (s: string) => void }} [io]
 */
export function mainC(io = {}) {
  const spawn = io.spawn ?? spawnSync;
  const execPath = io.execPath ?? process.execPath;
  const rootDir = io.rootDir ?? ROOT;
  const dispatcher = io.dispatcher ?? DISPATCHER;
  const getChanged = io.getChanged ?? ((baseRef) => getChangedPaths(baseRef, { cwd: rootDir }));
  const write = io.write ?? ((s) => process.stdout.write(s));
  const writeErr = io.writeErr ?? ((s) => process.stderr.write(s));
  const changed = getChanged("origin/master");
  if (changed.length === 0) {
    write("verify-mode-c: no changed paths against origin/master — nothing to verify.\n");
    return { exitCode: 0, slices: [], perSliceStatus: [] };
  }
  const slices = slicesFromChangedPaths(changed, rootDir);
  if (slices.length === 0) {
    write("verify-mode-c: changed paths don't resolve to any spec'd slice — nothing to verify.\n");
    return { exitCode: 0, slices: [], perSliceStatus: [] };
  }
  write(`verify-mode-c: re-verifying ${String(slices.length)} slice(s) in this push\n`);
  const { exitCode, perSliceStatus } = runModeAPerSlice(slices, rootDir, "mode-c", { spawn, execPath, dispatcher, write, writeErr });
  return { exitCode, slices, perSliceStatus };
}

/**
 * Mode E — entire-repo stamp update (invokes Mode A per slice).
 * @param {{ spawn?: typeof spawnSync, execPath?: string, rootDir?: string, findLocks?: (root: string) => string[], dispatcher?: string, write?: (s: string) => void, writeErr?: (s: string) => void }} [io]
 */
export function mainE(io = {}) {
  const spawn = io.spawn ?? spawnSync;
  const execPath = io.execPath ?? process.execPath;
  const rootDir = io.rootDir ?? ROOT;
  const dispatcher = io.dispatcher ?? DISPATCHER;
  const findLocks = io.findLocks ?? findAllLocks;
  const write = io.write ?? ((s) => process.stdout.write(s));
  const writeErr = io.writeErr ?? ((s) => process.stderr.write(s));
  const locks = findLocks(rootDir);
  if (locks.length === 0) {
    write("verify-mode-e: no locks found in the repo — nothing to re-stamp.\n");
    return { exitCode: 0, slices: [], perSliceStatus: [] };
  }
  const slices = slicesFromLocks(locks);
  write(`verify-mode-e: re-stamping ${String(slices.length)} slice(s) across the entire repo\n`);
  const { exitCode, perSliceStatus } = runModeAPerSlice(slices, rootDir, "mode-e", { spawn, execPath, dispatcher, write, writeErr });
  return { exitCode, slices, perSliceStatus };
}

// ─────────────────────────────────────────────────────────────────────────
// Mode Inspect — read-only lock walk. ALWAYS exits 0. NEVER stamps.
// ─────────────────────────────────────────────────────────────────────────

/**
 * @param {string} lockPath absolute
 * @param {{ readFile?: (p: string) => string, gitLastCommit?: (folder: string, lockFile: string) => string | null }} [io]
 * @returns {{ lockPath: string, status: string, lastValidated: string, freshness: "fresh" | "stale" | "unknown" }}
 */
export function inspectLock(lockPath, io = {}) {
  const readFile = io.readFile ?? ((p) => readFileSync(p, "utf8"));
  const gitLastCommit = io.gitLastCommit ?? defaultGitLastCommit;
  /** @type {string} */
  let contents;
  try {
    contents = readFile(lockPath);
  } catch {
    return { lockPath, status: "(unreadable)", lastValidated: "", freshness: "unknown" };
  }
  const fields = parseScalarFields(contents);
  const status = fields["status"] ?? "(missing)";
  const lastValidated = fields["last_validated"] ?? "(missing)";
  /** @type {"fresh" | "stale" | "unknown"} */
  let freshness = "unknown";
  if (status === "locked") {
    const stampMs = Date.parse(lastValidated);
    if (!Number.isNaN(stampMs)) {
      const result = checkFreshness(lockPath, stampMs, { gitLastCommit });
      freshness = result.ok ? "fresh" : "stale";
    }
  }
  return { lockPath, status, lastValidated, freshness };
}

/**
 * @param {ReadonlyArray<{ lockPath: string, status: string, lastValidated: string, freshness: "fresh" | "stale" | "unknown" }>} rows
 * @param {string} rootDir
 * @returns {{ text: string, lockedCount: number, unlockedCount: number, otherCount: number, staleCount: number }}
 */
export function formatReportInspect(rows, rootDir) {
  /** @type {string[]} */
  const lines = [];
  lines.push(`verify-mode-inspect: ${String(rows.length)} lock(s) found\n`);
  let lockedCount = 0, unlockedCount = 0, otherCount = 0, staleCount = 0;
  for (const row of rows) {
    const rel = relative(rootDir, row.lockPath);
    /** @type {string} */
    let tag;
    if (row.status === "locked") { tag = "  LOCKED"; lockedCount++; }
    else if (row.status === "unlocked") { tag = "UNLOCKED"; unlockedCount++; }
    else { tag = `[${row.status}]`; otherCount++; }
    const freshTag = row.freshness === "stale" ? " [STALE]" : "";
    if (row.freshness === "stale") staleCount++;
    lines.push(`  ${tag}  ${row.lastValidated}  ${rel}${freshTag}\n`);
  }
  lines.push(`\nsummary: ${String(lockedCount)} locked, ${String(unlockedCount)} unlocked, ${String(otherCount)} other, ${String(staleCount)} stale\n`);
  return { text: lines.join(""), lockedCount, unlockedCount, otherCount, staleCount };
}

/**
 * @param {{ rootDir?: string, findLocks?: (root: string) => string[], readFile?: (p: string) => string, gitLastCommit?: (folder: string, lockFile: string) => string | null, write?: (s: string) => void }} [io]
 * @returns {{ exitCode: 0, rows: Array<{ lockPath: string, status: string, lastValidated: string, freshness: "fresh" | "stale" | "unknown" }>, summary: ReturnType<typeof formatReportInspect> }}
 */
export function mainInspect(io = {}) {
  const rootDir = io.rootDir ?? ROOT;
  const findLocks = io.findLocks ?? ((root) => findAllLocks(root));
  const write = io.write ?? ((s) => process.stdout.write(s));
  const locks = findLocks(rootDir);
  const rows = locks.map((lock) => inspectLock(lock, io));
  const summary = formatReportInspect(rows, rootDir);
  write(summary.text);
  return { exitCode: 0, rows, summary };
}

// ─────────────────────────────────────────────────────────────────────────
// Mode Pristine — typecheck/build/lint/unit/e2e chain (read-only).
// ─────────────────────────────────────────────────────────────────────────

/** @typedef {{ name: string, args: readonly string[], optional?: boolean }} PristineStage */

/** @type {ReadonlyArray<PristineStage>} */
export const DEFAULT_STAGES = [
  { name: "typecheck", args: ["typecheck"] },
  { name: "build", args: ["build"] },
  { name: "lint", args: ["lint"] },
  { name: "unit", args: ["test"] },
  { name: "e2e", args: ["e2e"], optional: true },
];

/**
 * @param {{ stages?: ReadonlyArray<PristineStage>, pnpm?: string, cwd?: string, spawn?: typeof spawnSync, write?: (s: string) => void, writeErr?: (s: string) => void }} [io]
 * @returns {{ exitCode: 0 | 1, stages: Array<{ name: string, status: number, skipped: boolean }> }}
 */
export function mainPristine(io = {}) {
  const stages = io.stages ?? DEFAULT_STAGES;
  const pnpm = io.pnpm ?? "pnpm";
  const cwd = io.cwd ?? ROOT;
  const spawn = io.spawn ?? spawnSync;
  const write = io.write ?? ((s) => process.stdout.write(s));
  const writeErr = io.writeErr ?? ((s) => process.stderr.write(s));

  /** @type {Array<{ name: string, status: number, skipped: boolean }>} */
  const results = [];
  let aggregateExit = 0;
  for (const stage of stages) {
    write(`\n=== verify-mode-pristine: ${stage.name} ===\n`);
    const res = spawn(pnpm, [...stage.args], { cwd, encoding: "utf8" });
    if (res.error !== undefined) {
      const skipped = Boolean(stage.optional);
      writeErr(`verify-mode-pristine: stage '${stage.name}' could not be spawned${skipped ? " — skipping (optional)" : ""}: ${String(res.error)}\n`);
      results.push({ name: stage.name, status: skipped ? 0 : 1, skipped });
      if (!skipped) { aggregateExit = 1; break; }
      continue;
    }
    if (res.stdout) write(res.stdout);
    if (res.stderr) writeErr(res.stderr);
    const status = res.status ?? 1;
    if (status !== 0 && Boolean(stage.optional)) {
      writeErr(`verify-mode-pristine: stage '${stage.name}' returned non-zero (${String(status)}) — skipping (optional)\n`);
      results.push({ name: stage.name, status: 0, skipped: true });
      continue;
    }
    results.push({ name: stage.name, status, skipped: false });
    if (status !== 0) {
      aggregateExit = 1;
      writeErr(`verify-mode-pristine: stage '${stage.name}' FAILED (exit ${String(status)})\n`);
      break;
    }
  }
  if (aggregateExit === 0) write(`\nmode-pristine: PASS — ${String(results.length)} stage(s) green\n`);
  else writeErr(`\nmode-pristine: FAIL — stopped at first non-zero stage\n`);
  return { exitCode: aggregateExit === 0 ? 0 : 1, stages: results };
}

// ─────────────────────────────────────────────────────────────────────────
// Mode Cleanup-Orphans — report-only orphan-lock detector. ALWAYS exits 0.
// ─────────────────────────────────────────────────────────────────────────

const META_DIRS = new Set(["__specs__", "__tests__", "__stories__", "__manual__"]);

/**
 * @param {string} sliceDir
 * @param {{ readDir?: (dir: string) => Array<{ name: string, isDirectory: () => boolean, isFile: () => boolean }> }} [io]
 * @returns {boolean}
 */
export function sliceHasSource(sliceDir, io = {}) {
  const readDir = io.readDir ?? ((d) => readdirSync(d, { withFileTypes: true }));
  /** @type {Array<{ name: string, isDirectory: () => boolean, isFile: () => boolean }>} */
  let entries;
  try {
    entries = readDir(sliceDir);
  } catch {
    return false;
  }
  for (const entry of entries) {
    if (META_DIRS.has(entry.name)) continue;
    if (entry.isFile()) return true;
    if (entry.isDirectory()) return true;
  }
  return false;
}

/**
 * @param {string} specYamlPath absolute
 * @param {{ readFile?: (p: string) => string }} [io]
 * @returns {string | null}
 */
export function extractFeatureName(specYamlPath, io = {}) {
  const readFile = io.readFile ?? ((p) => readFileSync(p, "utf8"));
  /** @type {string} */
  let body;
  try {
    body = readFile(specYamlPath);
  } catch {
    return null;
  }
  const m = body.match(/^feature_name:\s*([^\s#]+)/m);
  return m === null ? null : m[1];
}

/**
 * @param {{ rootDir?: string, findLocks?: (root: string) => string[], sliceHasSource?: (slice: string) => boolean, extractFeatureName?: (specPath: string) => string | null, write?: (s: string) => void }} [io]
 * @returns {{ exitCode: 0, orphans: string[], deadCatalogEntries: Array<{ specPath: string, featureName: string }> }}
 */
export function mainCleanupOrphans(io = {}) {
  const rootDir = io.rootDir ?? ROOT;
  const findLocks = io.findLocks ?? findAllLocks;
  const hasSource = io.sliceHasSource ?? ((slice) => sliceHasSource(slice));
  const extractName = io.extractFeatureName ?? ((path) => extractFeatureName(path));
  const write = io.write ?? ((s) => process.stdout.write(s));

  const locks = findLocks(rootDir);
  /** @type {string[]} */
  const orphans = [];
  /** @type {Array<{ specPath: string, featureName: string }>} */
  const deadEntries = [];

  for (const lock of locks) {
    const specsDir = dirname(lock);
    const sliceDir = dirname(specsDir);
    if (!hasSource(sliceDir)) orphans.push(lock);
    // Dual-format: spec.md (fenced block) wins, else legacy spec.yaml.
    const specYaml = resolveSpecFile(specsDir);
    const featureName = extractName(specYaml);
    if (featureName !== null) {
      const relPath = relative(rootDir, sliceDir).replace(/\//g, "-");
      if (!relPath.endsWith(featureName)) deadEntries.push({ specPath: specYaml, featureName });
    }
  }

  write(`verify-mode-cleanup-orphans: ${String(orphans.length)} orphan lock(s); ${String(deadEntries.length)} catalog mismatch(es)\n`);
  if (orphans.length > 0) {
    write("\norphan locks (slice folder has no source):\n");
    for (const lock of orphans) write(`  - ${relative(rootDir, lock)}\n`);
  }
  if (deadEntries.length > 0) {
    write("\ncatalog mismatches (spec.yaml feature_name does not match slice path):\n");
    for (const e of deadEntries) write(`  - ${relative(rootDir, e.specPath)} → feature_name=${e.featureName}\n`);
  }
  if (orphans.length === 0 && deadEntries.length === 0) write("\nclean — no orphan locks or catalog mismatches\n");
  else write("\nReport-only — remove orphans via git; reconcile catalog entries by hand.\n");
  return { exitCode: 0, orphans, deadCatalogEntries: deadEntries };
}

// ─────────────────────────────────────────────────────────────────────────
// Compliance — scope-aware parallel gate orchestrator (read-only, no stamp).
// Default catalog is empty; the real gate chain is scripts/verify-all.mjs.
// ─────────────────────────────────────────────────────────────────────────

/**
 * @typedef {object} iScriptEntry
 * @property {string} id
 * @property {string} script
 * @property {boolean} importTsx
 * @property {"phase1" | "phase2"} phase
 * @property {boolean} fullOnly
 * @property {(changed: ReadonlyArray<string>) => boolean} territory
 */

/**
 * @param {ReadonlyArray<string>} argv
 * @returns {{ full: boolean, scope: boolean }}
 */
export function parseArgs(argv) {
  return { full: argv.includes("--full"), scope: argv.includes("--scope") };
}

/**
 * @param {{ full: boolean, scope: boolean }} mode
 * @param {ReadonlyArray<string>} changed
 * @param {ReadonlyArray<iScriptEntry>} catalog
 * @returns {{ toRun: iScriptEntry[], skipped: Array<{ entry: iScriptEntry, reason: string }> }}
 */
export function planRun(mode, changed, catalog) {
  /** @type {iScriptEntry[]} */
  const toRun = [];
  /** @type {Array<{ entry: iScriptEntry, reason: string }>} */
  const skipped = [];
  for (const entry of catalog) {
    if (entry.fullOnly && !mode.full) {
      skipped.push({ entry, reason: "fullOnly — only runs in --full mode" });
      continue;
    }
    if (mode.scope && !entry.territory(changed)) {
      skipped.push({ entry, reason: "no changed paths in territory" });
      continue;
    }
    toRun.push(entry);
  }
  return { toRun, skipped };
}

/**
 * @template T, R
 * @param {ReadonlyArray<T>} items
 * @param {(item: T) => Promise<R>} worker
 * @param {number} concurrency
 * @returns {Promise<R[]>}
 */
export async function runInPool(items, worker, concurrency) {
  const cap = Math.max(1, Math.min(concurrency, items.length));
  /** @type {R[]} */
  const results = new Array(items.length);
  let cursor = 0;
  async function next() {
    while (true) {
      const idx = cursor;
      cursor += 1;
      if (idx >= items.length) return;
      results[idx] = await worker(items[idx]);
    }
  }
  const workers = [];
  for (let i = 0; i < cap; i += 1) workers.push(next());
  await Promise.all(workers);
  return results;
}

/**
 * @param {ReadonlyArray<{ entry: iScriptEntry, status: number, stdout: string, stderr: string, ms: number }>} results
 * @param {(s: string) => void} write
 * @param {(s: string) => void} writeErr
 */
export function replayResults(results, write, writeErr) {
  for (const r of results) {
    if (r.stdout) write(r.stdout);
    if (r.stderr) writeErr(r.stderr);
  }
}

/**
 * @param {{ full: boolean, scope: boolean }} mode
 * @param {number} ran @param {number} skipped @param {number} totalMs
 * @returns {string}
 */
export function buildSuffix(mode, ran, skipped, totalMs) {
  const seconds = (totalMs / 1000).toFixed(1);
  if (mode.scope) return ` (scoped): OK (${String(ran)} of ${String(ran + skipped)} scripts ran, ${String(skipped)} skipped) in ${seconds}s`;
  if (mode.full) return ` (full): OK (all ${String(ran)} scripts passed) in ${seconds}s`;
  return `: OK (all ${String(ran)} scripts passed) in ${seconds}s`;
}

/**
 * @param {{ argv?: ReadonlyArray<string>, rootDir?: string, catalog?: ReadonlyArray<iScriptEntry>, runEntry?: (item: iScriptEntry) => Promise<{ entry: iScriptEntry, status: number, stdout: string, stderr: string, ms: number }>, concurrency?: number, getChanged?: (baseRef?: string) => string[], write?: (s: string) => void, writeErr?: (s: string) => void, now?: () => number }} [io]
 * @returns {Promise<{ exitCode: 0 | 1 }>}
 */
export async function mainCompliance(io = {}) {
  const argv = io.argv ?? process.argv.slice(2);
  const rootDir = io.rootDir ?? ROOT;
  const catalog = io.catalog ?? [];
  const concurrency = io.concurrency ?? 6;
  const write = io.write ?? ((s) => process.stdout.write(s));
  const writeErr = io.writeErr ?? ((s) => process.stderr.write(s));
  const now = io.now ?? (() => Date.now());
  const getChanged = io.getChanged ?? ((baseRef) => getChangedPaths(baseRef, { cwd: rootDir }));
  const runEntry = io.runEntry ?? (async (entry) => ({ entry, status: 0, stdout: "", stderr: "", ms: 0 }));

  const parsed = parseArgs(argv);
  /** @type {string[]} */
  let changed = [];
  let effectiveScope = parsed.scope;
  if (parsed.scope) {
    changed = getChanged("origin/master");
    if (changed.length === 0) {
      writeErr("verify-mode-compliance: --scope requested but no changed paths detected. Falling back to a full run.\n");
      effectiveScope = false;
    }
  }
  const effectiveMode = { full: parsed.full, scope: effectiveScope };
  const { toRun, skipped } = planRun(effectiveMode, changed, catalog);
  for (const s of skipped) write(`verify-mode-compliance: SKIP ${s.entry.id} (${s.reason})\n`);

  const phase1 = toRun.filter((e) => e.phase === "phase1");
  const phase2 = toRun.filter((e) => e.phase === "phase2");
  const startedAt = now();

  const phase1Results = await runInPool(phase1, runEntry, concurrency);
  replayResults(phase1Results, write, writeErr);
  const phase1Failed = phase1Results.some((r) => r.status !== 0);

  /** @type {Awaited<ReturnType<typeof runEntry>>[]} */
  const phase2Results = [];
  /** @type {iScriptEntry[]} */
  const phase2Skipped = [];
  if (phase1Failed) {
    if (phase2.length > 0) {
      writeErr(`verify-mode-compliance: Phase 1 failed — skipping ${String(phase2.length)} Phase-2 writer(s) to avoid committing stale artifacts\n`);
      for (const entry of phase2) phase2Skipped.push(entry);
    }
  } else {
    for (const entry of phase2) phase2Results.push(await runEntry(entry));
    replayResults(phase2Results, write, writeErr);
  }

  const totalMs = now() - startedAt;
  const allResults = [...phase1Results, ...phase2Results];
  const failures = allResults.filter((r) => r.status !== 0);
  if (failures.length > 0) {
    const lines = [`verify-mode-compliance: ${String(failures.length)} script(s) failed (of ${String(allResults.length)} that ran)`];
    for (const f of failures) lines.push(`  FAIL: ${f.entry.id} (exit ${String(f.status)})`);
    if (phase2Skipped.length > 0) lines.push(`  Phase-2 SKIPPED (gated on Phase-1 success): ${phase2Skipped.map((e) => e.id).join(", ")}`);
    writeErr(`${lines.join("\n")}\n`);
    return { exitCode: 1 };
  }
  write(`verify-mode-compliance${buildSuffix(effectiveMode, allResults.length, skipped.length, totalMs)}\n`);
  return { exitCode: 0 };
}

// ─────────────────────────────────────────────────────────────────────────
// Pristine+Compliance — Mode Pristine, then the verify-all gate chain.
// First non-zero stops the chain.
// ─────────────────────────────────────────────────────────────────────────

/**
 * @param {{ spawn?: typeof spawnSync, execPath?: string, cwd?: string, dispatcher?: string, verifyAllGate?: string, write?: (s: string) => void, writeErr?: (s: string) => void }} [io]
 * @returns {{ exitCode: 0 | 1, stages: Array<{ name: string, status: number }> }}
 */
export function mainPristineAndCompliance(io = {}) {
  const spawn = io.spawn ?? spawnSync;
  const execPath = io.execPath ?? process.execPath;
  const cwd = io.cwd ?? ROOT;
  const dispatcher = io.dispatcher ?? DISPATCHER;
  const verifyAllGate = io.verifyAllGate ?? VERIFY_ALL_GATE;
  const write = io.write ?? ((s) => process.stdout.write(s));
  const writeErr = io.writeErr ?? ((s) => process.stderr.write(s));

  /** @type {Array<{ name: string, status: number }>} */
  const stages = [];
  for (const stage of [
    { name: "pristine", args: [dispatcher, "pristine"] },
    { name: "compliance", args: [verifyAllGate] },
  ]) {
    write(`\n=== verify-mode-pristine-and-compliance: ${stage.name} ===\n`);
    const res = spawn(execPath, stage.args, { cwd, encoding: "utf8" });
    if (res.stdout) write(res.stdout);
    if (res.stderr) writeErr(res.stderr);
    const status = res.status ?? 1;
    stages.push({ name: stage.name, status });
    if (status !== 0) {
      writeErr(`verify-mode-pristine-and-compliance: stage '${stage.name}' FAILED (exit ${String(status)})\n`);
      return { exitCode: 1, stages };
    }
  }
  write(`\nmode-pristine-and-compliance: PASS — pristine + compliance both green\n`);
  return { exitCode: 0, stages };
}

// ─────────────────────────────────────────────────────────────────────────
// Mode Verify-All — feature-by-feature deep ceremony. Unlocks-on-fail;
// relocks via Mode A on green. Writes .verify-all-progress.json.
// ─────────────────────────────────────────────────────────────────────────

/** @typedef {{ slice: string, verdict: "pass" | "fail", lastRun: string }} VerifyAllRow */

/**
 * @param {string} progressPath
 * @param {{ readFile?: (p: string) => string }} [io]
 * @returns {Record<string, VerifyAllRow>}
 */
export function loadProgress(progressPath, io = {}) {
  const readFile = io.readFile ?? ((p) => readFileSync(p, "utf8"));
  if (!existsSync(progressPath)) return {};
  try {
    const parsed = JSON.parse(readFile(progressPath));
    if (parsed === null || typeof parsed !== "object") return {};
    return /** @type {Record<string, VerifyAllRow>} */ (parsed);
  } catch {
    return {};
  }
}

/**
 * @param {string} progressPath
 * @param {Record<string, VerifyAllRow>} state
 * @param {{ writeFile?: (p: string, c: string) => void }} [io]
 */
export function saveProgress(progressPath, state, io = {}) {
  const writeFile = io.writeFile ?? ((p, c) => writeFileSync(p, c, "utf8"));
  writeFile(progressPath, JSON.stringify(state, null, 2) + "\n");
}

/**
 * @param {{
 *   rootDir?: string, findLocks?: (root: string) => string[], slices?: string[],
 *   progressPath?: string, resume?: boolean, spawn?: typeof spawnSync, execPath?: string,
 *   dispatcher?: string, pristineAndCompliance?: (io: object) => { exitCode: 0 | 1 },
 *   unlock?: (lockPath: string) => void, write?: (s: string) => void, writeErr?: (s: string) => void,
 *   now?: () => Date, readFile?: (p: string) => string, writeFile?: (p: string, c: string) => void,
 * }} [io]
 * @returns {{ exitCode: 0 | 1, rows: VerifyAllRow[] }}
 */
export function mainVerifyAll(io = {}) {
  const rootDir = io.rootDir ?? ROOT;
  const findLocks = io.findLocks ?? findAllLocks;
  const progressPath = io.progressPath ?? resolve(ROOT, ".verify-all-progress.json");
  const resume = io.resume ?? true;
  const spawn = io.spawn ?? spawnSync;
  const execPath = io.execPath ?? process.execPath;
  const dispatcher = io.dispatcher ?? DISPATCHER;
  const runPc = io.pristineAndCompliance ?? mainPristineAndCompliance;
  const unlock = io.unlock ?? unlockLock;
  const write = io.write ?? ((s) => process.stdout.write(s));
  const writeErr = io.writeErr ?? ((s) => process.stderr.write(s));
  const now = io.now ?? (() => new Date());

  const locks = findLocks(rootDir);
  const slices = io.slices ?? slicesFromLocks(locks);
  /** @type {Record<string, VerifyAllRow>} */
  const progress = resume ? loadProgress(progressPath, { readFile: io.readFile }) : {};

  write(`verify-mode-verify-all: ${String(slices.length)} slice(s) total; ${String(Object.values(progress).filter((r) => r.verdict === "pass").length)} already passed${resume ? " (resuming)" : ""}\n`);

  let aggregateExit = 0;
  /** @type {VerifyAllRow[]} */
  const rows = [];

  for (const slice of slices) {
    const rel = relative(rootDir, slice);
    const prior = progress[rel];
    if (resume && prior !== undefined && prior.verdict === "pass") {
      write(`\n--- slice: ${rel} — already PASSED; skipping ---\n`);
      rows.push(prior);
      continue;
    }
    write(`\n--- slice: ${rel} ---\n`);
    const lockPath = resolveLockFile(join(slice, "__specs__"));

    // Pristine + the verify-all gate chain, composed in-process (not spawning
    // any deleted file). The lock stays locked during this run; the unlock
    // signal happens only AFTER a failure.
    const pcRes = runPc({ spawn, execPath, cwd: rootDir, dispatcher, write, writeErr });
    if (pcRes.exitCode !== 0) {
      writeErr(`verify-mode-verify-all: ${rel} FAILED Pristine+Compliance; unlocking\n`);
      try { unlock(lockPath); } catch (err) { writeErr(`verify-mode-verify-all: also could not unlock ${rel}: ${String(err)}\n`); }
      const row = /** @type {VerifyAllRow} */ ({ slice: rel, verdict: "fail", lastRun: now().toISOString() });
      progress[rel] = row; rows.push(row);
      saveProgress(progressPath, progress, { writeFile: io.writeFile });
      aggregateExit = 1;
      continue;
    }

    // P+C passed — invoke Mode A (via the dispatcher) to refresh the stamp.
    const aRes = spawn(execPath, [dispatcher, "a", slice], { cwd: rootDir, encoding: "utf8" });
    if (aRes.stdout) write(aRes.stdout);
    if (aRes.stderr) writeErr(aRes.stderr);
    if ((aRes.status ?? 1) !== 0) {
      writeErr(`verify-mode-verify-all: ${rel} FAILED Mode A relock; unlocking\n`);
      try { unlock(lockPath); } catch (err) { writeErr(`verify-mode-verify-all: also could not unlock ${rel}: ${String(err)}\n`); }
      const row = /** @type {VerifyAllRow} */ ({ slice: rel, verdict: "fail", lastRun: now().toISOString() });
      progress[rel] = row; rows.push(row);
      saveProgress(progressPath, progress, { writeFile: io.writeFile });
      aggregateExit = 1;
      continue;
    }

    const row = /** @type {VerifyAllRow} */ ({ slice: rel, verdict: "pass", lastRun: now().toISOString() });
    progress[rel] = row; rows.push(row);
    saveProgress(progressPath, progress, { writeFile: io.writeFile });
  }

  const passed = rows.filter((r) => r.verdict === "pass").length;
  write(`\nmode-verify-all: ${String(passed)}/${String(rows.length)} slices PASS\n`);
  return { exitCode: aggregateExit === 0 ? 0 : 1, rows };
}

// ─────────────────────────────────────────────────────────────────────────
// CLI dispatch.
// ─────────────────────────────────────────────────────────────────────────

const USAGE =
  "verify-mode: usage: node verify-mode.mjs <mode> [args]\n" +
  "  modes: a <slice> | b | b5 | c | d | e | f | inspect | pristine | cleanup-orphans | verify-all\n" +
  "         (aliases: compliance, pristine-and-compliance)\n";

/**
 * Run the requested mode. Returns an exit code (may be a Promise for the
 * async compliance orchestrator).
 * @param {ReadonlyArray<string>} argv the argv AFTER the node script path (process.argv.slice(2))
 * @param {{ write?: (s: string) => void, writeErr?: (s: string) => void }} [io]
 * @returns {number | Promise<number>}
 */
export function dispatch(argv, io = {}) {
  const write = io.write ?? ((s) => process.stdout.write(s));
  const writeErr = io.writeErr ?? ((s) => process.stderr.write(s));
  const mode = argv[0];
  const rest = argv.slice(1);
  switch (mode) {
    case "a": {
      if (rest.length === 0) {
        writeErr("verify-mode a: missing slice path. Usage: node verify-mode.mjs a <slice-path>\n");
        return 1;
      }
      return mainA(rest[0]).exitCode;
    }
    case "b": return mainB().exitCode;
    case "b5": return mainB5().exitCode;
    case "c": return mainC().exitCode;
    case "d": return mainD().exitCode;
    case "e": return mainE().exitCode;
    case "f": return mainF().exitCode;
    case "inspect": return mainInspect().exitCode;
    case "pristine": return mainPristine().exitCode;
    case "cleanup-orphans": return mainCleanupOrphans().exitCode;
    case "verify-all": return mainVerifyAll().exitCode;
    case "compliance": return mainCompliance().then((r) => r.exitCode);
    case "pristine-and-compliance": return mainPristineAndCompliance().exitCode;
    default:
      writeErr(`verify-mode: unknown mode '${mode ?? ""}'\n${USAGE}`);
      void write;
      return 1;
  }
}

/**
 * @param {{ argv?: ReadonlyArray<string>, exit?: (code: number) => void }} [io]
 * @returns {Promise<void>}
 */
export async function cliMain(io = {}) {
  const argv = io.argv ?? process.argv.slice(2);
  const exit = io.exit ?? ((code) => process.exit(code));
  const code = await dispatch(argv);
  exit(code);
}

/**
 * @param {string} importMetaUrl
 * @param {string | undefined} argv1
 * @returns {boolean}
 */
export function isCliInvocation(importMetaUrl, argv1) {
  if (argv1 === undefined || argv1 === "") return false;
  return importMetaUrl === pathToFileURL(argv1).href;
}

/**
 * @param {{ importMetaUrl: string, argv1: string | undefined, argv?: ReadonlyArray<string>, exit?: (code: number) => void }} io
 * @returns {Promise<boolean>}
 */
export async function maybeRunCli(io) {
  if (!isCliInvocation(io.importMetaUrl, io.argv1)) return false;
  await cliMain({ argv: io.argv, exit: io.exit });
  return true;
}

await maybeRunCli({ importMetaUrl: import.meta.url, argv1: process.argv[1] });
