#!/usr/bin/env node

// ────────────────────────────────────────────────────────────────
// DO NOT EDIT THIS FILE.
//
// COPY of source-of-truth at
//   ~/.claude/standards/scripts/verify/verify-tests.mjs
//
// Local edits will be overwritten the next time
//   bash ~/.claude/standards/scripts/install-slice-gates.sh
// runs. Edit the ORIGINAL and re-install.
// ────────────────────────────────────────────────────────────────
/**
 * verify-tests.mjs — consolidated test-quality gate.
 *
 * Runs five test-quality sub-checks. By default every sub-check runs and the
 * gate exits nonzero iff ANY sub-check fails (OR semantics). `--check <name>`
 * runs exactly one sub-check.
 *
 * Sub-checks (each preserves its own no-op-green short-circuit + exact stderr):
 *   coverage-threshold    the vitest config must gate coverage at 100% perFile
 *                         (UNIT_COVERAGE). No-op green when no vitest config.
 *   test-naming           path-derived test IDs — __tests__/ + __stories__/
 *                         filename shapes + e2e scenario/flow folder contract
 *                         (TEST_NAMING).
 *   e2e-db-safety         e2e tests + seeds target only local/e2e databases
 *                         (E2E_TESTING.db_safety). No-op green when no e2e scope.
 *   accessibility-wiring  a Storybook UI repo wires the axe gate into pnpm verify
 *                         (ACCESSIBILITY). No-op green when ui_discipline:none or
 *                         no Storybook.
 *   no-theater-tests      detects trivial-true / empty-it / negative-no-op
 *                         patterns. No-op green when no src/ (or chosen root).
 *
 * Usage:
 *   node scripts/verify/verify-tests.mjs [<root>]              run all sub-checks
 *   node scripts/verify/verify-tests.mjs --check <name> [<root>]  run one sub-check
 *
 * Exit: 0 when every run sub-check passes; 1 otherwise.
 */
import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import { execSync } from "node:child_process";

const GREEN = "\x1b[32m";
const RED = "\x1b[31m";
const RESET = "\x1b[0m";

// ── arg parsing ──────────────────────────────────────────────────────────
// `--check <name>` selects one sub-check; the first non-flag positional is the
// root each sub-check applies its own default to (default cwd / "." / "src").
const argv = process.argv.slice(2);
let checkName = null;
const positionals = [];
for (let i = 0; i < argv.length; i++) {
  if (argv[i] === "--check") {
    checkName = argv[++i];
  } else {
    positionals.push(argv[i]);
  }
}
const RAW_ROOT = positionals[0];

// ════════════════════════════════════════════════════════════════════════
// Sub-check: coverage-threshold
// (from verify-coverage-threshold.mjs — UNIT_COVERAGE.yaml.coverage)
// ════════════════════════════════════════════════════════════════════════
function checkCoverageThreshold() {
  const REPO_ROOT = RAW_ROOT || process.cwd();
  const NAME = "verify-coverage-threshold";
  const IGNORE = new Set(["node_modules", ".git", ".next", ".turbo", "dist", "build", "out", "coverage", ".vercel", "test-results", "playwright-report"]);
  const CONFIG_RE = /^(vitest|vite)\.config\.[mc]?[jt]s$/;

  function findConfigs(dir, acc = []) {
    let entries;
    try { entries = fs.readdirSync(dir, { withFileTypes: true }); } catch { return acc; }
    for (const e of entries) {
      if (IGNORE.has(e.name)) continue;
      const p = path.join(dir, e.name);
      if (e.isDirectory()) findConfigs(p, acc);
      else if (e.isFile() && CONFIG_RE.test(e.name)) acc.push(p);
    }
    return acc;
  }

  function isVitestConfig(file, text) {
    if (path.basename(file).startsWith("vitest.config")) return true;
    return /\btest\s*:/.test(text) && /\bcoverage\s*:/.test(text);
  }

  function checkThresholds(text) {
    const problems = [];
    const tIdx = text.search(/\bthresholds\s*:/);
    if (tIdx === -1) {
      return ["no `coverage.thresholds` block — coverage is ungated (UNIT_COVERAGE requires 100 perFile)"];
    }
    const win = text.slice(tIdx, tIdx + 600);
    const shorthand100 = /\b100\s*:\s*true/.test(win);
    const metrics = ["lines", "branches", "functions", "statements"];
    const explicit100 = metrics.every((m) => new RegExp(`\\b${m}\\s*:\\s*100\\b`).test(win));
    if (!shorthand100 && !explicit100) {
      problems.push("thresholds do not demand 100 on all metrics (need `100: true` or lines/branches/functions/statements all = 100)");
    }
    if (!/\bperFile\s*:\s*true/.test(text)) {
      problems.push("`perFile: true` not set — aggregate 100% can hide a 0%-covered file");
    }
    return problems;
  }

  const configs = findConfigs(REPO_ROOT).filter((f) => {
    try { return fs.statSync(f).isFile(); } catch { return false; }
  });

  const gated = [];
  const violations = [];
  for (const file of configs) {
    let text = "";
    try { text = fs.readFileSync(file, "utf8"); } catch { continue; }
    if (!isVitestConfig(file, text)) continue;
    const problems = checkThresholds(text);
    gated.push(file);
    if (problems.length) {
      for (const p of problems) violations.push(`${path.relative(REPO_ROOT, file)}: ${p}`);
    }
  }

  if (gated.length === 0) {
    process.stdout.write(`✅ ${NAME} — no vitest config in this repo; nothing to gate.\n`);
    return true;
  }
  if (violations.length === 0) {
    process.stdout.write(`✅ ${NAME} — ${gated.length} vitest config(s) gate coverage at 100% perFile.\n`);
    return true;
  }
  process.stderr.write(`\n❌ ${NAME}: ${violations.length} coverage-threshold violation(s)\n`);
  for (const v of violations) process.stderr.write(`   - ${v}\n`);
  process.stderr.write(`\n   Fix: set coverage.thresholds to 100 (or \`100: true\`) with perFile:true in the vitest config. UNIT_COVERAGE.yaml.coverage.\n`);
  return false;
}

// ════════════════════════════════════════════════════════════════════════
// Sub-check: test-naming
// (from verify-test-naming.mjs — TEST_NAMING.yaml)
// ════════════════════════════════════════════════════════════════════════
function checkTestNaming() {
  const NAME = "verify-test-naming";
  const SKIP_DIRS = new Set(["node_modules", ".git", ".next", ".turbo", "dist", "build", "coverage", "out", ".archive"]);
  const KEBAB = /^[a-z0-9]+(-[a-z0-9]+)*$/;

  function* walkDirs(dir) {
    yield dir;
    for (const ent of fs.readdirSync(dir, { withFileTypes: true })) {
      if (ent.isDirectory() && !SKIP_DIRS.has(ent.name)) yield* walkDirs(path.join(dir, ent.name));
    }
  }

  const root = path.resolve(process.cwd(), RAW_ROOT || ".");
  const EXTRA_ROOTS = [];
  // Also scan the repo-root e2e/ tree when running from a code subdir —
  // the e2e contracts live at the git root (E2E_TESTING placement.mono).
  try {
    const top = execSync("git rev-parse --show-toplevel", { encoding: "utf8" }).trim();
    const rootE2e = path.join(top, "e2e");
    if (fs.existsSync(rootE2e) && !path.resolve(root).startsWith(top + path.sep + "e2e") && path.resolve(root) !== rootE2e) {
      EXTRA_ROOTS.push(rootE2e);
    }
  } catch { /* not a git repo */ }

  const violations = [];
  let checked = 0;

  for (const dir of [...(fs.existsSync(root) ? [...walkDirs(root)] : []), ...EXTRA_ROOTS.flatMap((r) => [...walkDirs(r)])]) {
    const base = path.basename(dir);
    const rel = path.relative(root, dir) || ".";
    const files = fs.readdirSync(dir, { withFileTypes: true }).filter((e) => e.isFile()).map((e) => e.name);

    if (base === "__tests__") {
      for (const f of files) {
        checked++;
        const isTooling = /(^|\/)scripts\//.test(rel);
        if (!(isTooling ? /\.test\.(tsx?|mjs)$/ : /\.test\.tsx?$/).test(f) && !/^support$/.test(f)) violations.push({ rel: `${rel}/${f}`, rule: isTooling ? "files in scripts __tests__/ must be <name>.test.ts(x) or <name>.test.mjs" : "files in __tests__/ must be <name>.test.ts(x)" });
      }
    }
    if (base === "__stories__") {
      for (const f of files) {
        checked++;
        if (!/(\.stories\.tsx|\.usage\.mdx|\.readme\.mdx)$/.test(f)) violations.push({ rel: `${rel}/${f}`, rule: "files in __stories__/ must be <name>.stories.tsx / <name>.usage.mdx / <name>.readme.mdx" });
      }
    }
    // e2e flow contract dirs: parent chain .../e2e/<scenario>/<flow>/
    const parts = rel.split(path.sep);
    const e2eIdx = parts.lastIndexOf("e2e");
    if (e2eIdx !== -1 && parts.length === e2eIdx + 3) {
      const [scenario, flow] = [parts[e2eIdx + 1], parts[e2eIdx + 2]];
      checked++;
      if (!KEBAB.test(scenario)) violations.push({ rel, rule: `e2e scenario folder "${scenario}" is not kebab-case` });
      if (!KEBAB.test(flow)) violations.push({ rel, rule: `e2e flow folder "${flow}" is not kebab-case` });
      const contract = files.find((f) => f === `${flow}.yaml`);
      if (contract) {
        const text = fs.readFileSync(path.join(dir, contract), "utf8");
        const field = (k) => (text.match(new RegExp(`^${k}:\\s*(\\S+)\\s*$`, "m")) || [])[1];
        const sc = field("scenario");
        const fl = field("flow");
        if (sc && sc !== scenario) violations.push({ rel: `${rel}/${contract}`, rule: `scenario: "${sc}" != folder "${scenario}"` });
        if (fl && fl !== flow) violations.push({ rel: `${rel}/${contract}`, rule: `flow: "${fl}" != folder "${flow}"` });
        const varBlock = text.match(/^variants:\s*\n((?:\s+-\s+.+\n?)+)/m);
        if (varBlock) {
          for (const vm of varBlock[1].matchAll(/-\s+([A-Za-z0-9._-]+)/g)) {
            const variant = vm[1];
            if (!files.some((f) => f !== contract && f.includes(variant))) {
              violations.push({ rel: `${rel}/${contract}`, rule: `variants[] entry "${variant}" has no matching file in the flow folder` });
            }
          }
        }
      }
    }
  }

  if (violations.length === 0) {
    process.stdout.write(`${GREEN}✅ ${NAME}${RESET} — ${checked} test-naming target(s) checked; all path-derived IDs valid.\n`);
    return true;
  }
  process.stderr.write(`${RED}❌ ${NAME}:${RESET} ${violations.length} violation(s)\n`);
  for (const v of violations) process.stderr.write(`  [${v.rel}] ${v.rule}\n`);
  process.stderr.write(`Per TEST_NAMING.yaml — IDs are path-derived; folders/files must match the naming contract.\n`);
  return false;
}

// ════════════════════════════════════════════════════════════════════════
// Sub-check: e2e-db-safety
// (from verify-e2e-db-safety.mjs — E2E_TESTING.yaml db_safety)
// ════════════════════════════════════════════════════════════════════════
function checkE2eDbSafety() {
  const NAME = "verify-e2e-db-safety";
  const SKIP_DIRS = new Set(["node_modules", ".git", ".next", ".turbo", "dist", "build", "coverage", "out", ".archive"]);
  const CODE_EXT = /\.(ts|tsx|mts|cts|js|mjs|cjs|yaml|yml|sql|env|sh)$/;
  const LOCAL_HOST = /^(localhost|127(\.\d+){3}|0\.0\.0\.0|::1|\[::1\])$|(\.(local|test|localhost))$/;
  const CONN_RE = /(?:postgres(?:ql)?|mysql|mongodb(?:\+srv)?):\/\/([^\s'"`]+)/g;
  const ENV_RE = /(?:process\.env\.|\$\{?)([A-Z0-9_]*(?:DATABASE|DB)_?URL[A-Z0-9_]*)/g;
  const SAFE_ENV = /^(E2E|TEST|LOCAL)_/;

  function* walk(dir) {
    for (const ent of fs.readdirSync(dir, { withFileTypes: true })) {
      if (ent.isDirectory()) {
        if (!SKIP_DIRS.has(ent.name)) yield* walk(path.join(dir, ent.name));
      } else yield path.join(dir, ent.name);
    }
  }

  function hostOf(rest) {
    const noCred = rest.includes("@") ? rest.slice(rest.lastIndexOf("@") + 1) : rest;
    return noCred.split(/[:/?]/)[0];
  }

  const root = path.resolve(process.cwd(), RAW_ROOT || ".");
  const EXTRA_ROOTS = [];
  try {
    const top = execSync("git rev-parse --show-toplevel", { encoding: "utf8" }).trim();
    const rootE2e = path.join(top, "e2e");
    if (fs.existsSync(rootE2e) && !path.resolve(root).startsWith(top + path.sep + "e2e") && path.resolve(root) !== rootE2e) {
      EXTRA_ROOTS.push(rootE2e);
    }
  } catch { /* not a git repo */ }

  const violations = [];
  let scanned = 0;

  for (const f of [...(fs.existsSync(root) ? [...walk(root)] : []), ...EXTRA_ROOTS.flatMap((r) => [...walk(r)])]) {
    const rel = path.relative(root, f);
    const inScope = /(^|\/)e2e\//.test(rel) || /(^|\/)db\/seeds\/e2e\//.test(rel);
    if (!inScope || !CODE_EXT.test(rel)) continue;
    scanned++;
    const text = fs.readFileSync(f, "utf8");

    for (const m of text.matchAll(CONN_RE)) {
      if (m[1].startsWith("$")) continue; // templated — judged by the env-var rule
      const host = hostOf(m[1]);
      if (host && !LOCAL_HOST.test(host)) {
        violations.push({ rel, rule: `non-local DB connection string (host "${host}") — e2e scope may only target local/e2e databases` });
      }
    }
    for (const m of text.matchAll(ENV_RE)) {
      if (!SAFE_ENV.test(m[1])) {
        violations.push({ rel, rule: `e2e scope consumes env var "${m[1]}" — DB URLs in e2e scope must be E2E_/TEST_/LOCAL_-prefixed (never DATABASE_URL/PROD*)` });
      }
    }
  }

  if (violations.length === 0) {
    process.stdout.write(`${GREEN}✅ ${NAME}${RESET} — ${scanned} e2e-scope file(s) scanned; no remote DB targets.\n`);
    return true;
  }
  process.stderr.write(`${RED}❌ ${NAME}:${RESET} ${violations.length} violation(s)\n`);
  for (const v of violations) process.stderr.write(`  [${v.rel}] ${v.rule}\n`);
  process.stderr.write(`Per E2E_TESTING.yaml.db_safety — never real/remote DBs from e2e; local or e2e-db only.\n`);
  return false;
}

// ════════════════════════════════════════════════════════════════════════
// Sub-check: accessibility-wiring
// (from verify-accessibility-wiring.mjs — ACCESSIBILITY.yaml.test_runner)
// ════════════════════════════════════════════════════════════════════════
function checkAccessibilityWiring() {
  const REPO_ROOT = RAW_ROOT || process.cwd();
  const NAME = "verify-accessibility-wiring";
  const IGNORE = new Set(["node_modules", ".git", ".next", ".turbo", "dist", "build", "out", "coverage", ".vercel"]);

  // ui_discipline: none → this standard short-circuits.
  try {
    const autonomy = fs.readFileSync(path.join(REPO_ROOT, ".standards", "autonomy.yaml"), "utf8");
    if (/\bui_discipline\s*:\s*none\b/.test(autonomy)) {
      process.stdout.write(`✅ ${NAME} — ui_discipline: none; n/a.\n`);
      return true;
    }
  } catch { /* no autonomy file → assume UI may apply, continue */ }

  function findStorybookDirs(dir, acc = []) {
    let entries;
    try { entries = fs.readdirSync(dir, { withFileTypes: true }); } catch { return acc; }
    for (const e of entries) {
      if (IGNORE.has(e.name)) continue;
      const p = path.join(dir, e.name);
      if (!e.isDirectory()) continue;
      if (e.name === ".storybook") acc.push(p);
      else findStorybookDirs(p, acc);
    }
    return acc;
  }

  function readJson(file) {
    try { return JSON.parse(fs.readFileSync(file, "utf8")); } catch { return null; }
  }

  const rootPkg = readJson(path.join(REPO_ROOT, "package.json")) || {};
  const rootVerify = String(rootPkg.scripts?.verify || "");

  const sbDirs = findStorybookDirs(REPO_ROOT);
  if (sbDirs.length === 0) {
    process.stdout.write(`✅ ${NAME} — no Storybook UI in this repo; nothing to gate.\n`);
    return true;
  }

  const violations = [];
  for (const sb of sbDirs) {
    const pkgRoot = path.dirname(sb);
    const rel = path.relative(REPO_ROOT, pkgRoot) || ".";
    if (!fs.existsSync(path.join(sb, "test-runner.ts"))) {
      violations.push(`${rel}: missing .storybook/test-runner.ts (the axe-core injection config)`);
    }
    const pkg = readJson(path.join(pkgRoot, "package.json")) || {};
    const scripts = pkg.scripts || {};
    if (!scripts["test:stories"]) violations.push(`${rel}: package.json has no "test:stories" script`);
    if (!scripts["verify:stories"]) violations.push(`${rel}: package.json has no "verify:stories" script`);
    const pkgVerify = String(scripts.verify || "");
    const chained = /verify:stories/.test(pkgVerify) || /verify:stories/.test(rootVerify);
    if (!chained) {
      violations.push(`${rel}: "verify:stories" is not chained into any verify script (ACCESSIBILITY: the a11y gate must be part of \`pnpm verify\`)`);
    }
  }

  if (violations.length === 0) {
    process.stdout.write(`✅ ${NAME} — ${sbDirs.length} Storybook package(s) wire the axe a11y gate.\n`);
    return true;
  }
  process.stderr.write(`\n❌ ${NAME}: ${violations.length} a11y-wiring violation(s)\n`);
  for (const v of violations) process.stderr.write(`   - ${v}\n`);
  process.stderr.write(`\n   Fix: add .storybook/test-runner.ts + test:stories/verify:stories scripts and chain verify:stories into pnpm verify. ACCESSIBILITY.yaml.test_runner.\n`);
  return false;
}

// ════════════════════════════════════════════════════════════════════════
// Sub-check: no-theater-tests
// (from verify-no-theater-tests/verify-no-theater-tests.mjs)
// ════════════════════════════════════════════════════════════════════════
const PATTERN_TRIVIAL_TRUE  = /expect\(\s*(true|false|1|0|null|undefined|""|''|`\s*`)\s*\)\.toBe\(\s*\1\s*\)/g;
const PATTERN_EMPTY_IT      = /\b(?:it|test)\s*\(\s*['"`][^'"`]+['"`]\s*,\s*(?:async\s*)?\(\s*\)\s*=>\s*\{\s*\}\s*\)/g;

function extractItBlocks(src) {
  const out = [];
  const re = /\b(?:it|test)\s*\(\s*(['"`])([^'"`]+)\1\s*,\s*(?:async\s*)?\(\s*\)\s*=>\s*\{/g;
  let m;
  while ((m = re.exec(src)) !== null) {
    const name = m[2];
    const bodyStart = re.lastIndex;
    let depth = 1;
    let i = bodyStart;
    while (i < src.length && depth > 0) {
      const ch = src[i];
      if (ch === "{") depth++;
      else if (ch === "}") depth--;
      i++;
    }
    if (depth === 0) out.push({ name, body: src.slice(bodyStart, i - 1) });
  }
  return out;
}

function isNegativeNoOpBlock(blockBody) {
  const allExpects = blockBody.match(/expect\(/g) ?? [];
  if (allExpects.length === 0) return false;
  const specific = blockBody.match(/expect\([^)]*\)\.(?!not\.toThrow\b)[a-zA-Z]+\(/g) ?? [];
  if (specific.length > 0) return false;
  return blockBody.includes(".not.toThrow(");
}

function scanSource(src) {
  const hits = [];
  const lines = src.split("\n");
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    if (PATTERN_TRIVIAL_TRUE.test(line)) hits.push({ line: i + 1, pattern: "trivial-true", snippet: line.trim() });
    PATTERN_TRIVIAL_TRUE.lastIndex = 0;
    if (PATTERN_EMPTY_IT.test(line))     hits.push({ line: i + 1, pattern: "empty-it", snippet: line.trim() });
    PATTERN_EMPTY_IT.lastIndex = 0;
  }
  const blocks = extractItBlocks(src);
  for (const { name, body } of blocks) {
    if (isNegativeNoOpBlock(body)) {
      const lineIdx = src.slice(0, src.indexOf(body)).split("\n").length;
      hits.push({ line: lineIdx, pattern: "negative-no-op", snippet: `it("${name}", …) — only assertion is .not.toThrow()` });
    }
  }
  return hits;
}

function checkNoTheaterTests() {
  const SOURCE_ROOT = RAW_ROOT || "src";
  const REPO_ROOT = process.cwd();
  const absRoot = path.join(REPO_ROOT, SOURCE_ROOT);

  const SKIP_DIRS = new Set([
    "node_modules", ".next", ".turbo", "dist", "build", "out", ".git",
    "coverage", "test-results", "playwright-report",
  ]);
  const TEST_FILE_RE = /\.(?:test|spec)\.(?:ts|tsx|js|jsx|mts|mjs)$/;

  const violations = [];

  function walk(dir) {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      if (entry.isDirectory()) {
        if (SKIP_DIRS.has(entry.name)) continue;
        walk(path.join(dir, entry.name));
        continue;
      }
      if (!TEST_FILE_RE.test(entry.name)) continue;
      const file = path.join(dir, entry.name);
      let src;
      try { src = fs.readFileSync(file, "utf8"); } catch { continue; }
      const hits = scanSource(src);
      for (const h of hits) violations.push({ file: path.relative(REPO_ROOT, file), ...h });
    }
  }

  if (!fs.existsSync(absRoot)) {
    process.stdout.write(`✅ verify-no-theater-tests — no ${SOURCE_ROOT}/ in this repo; nothing to check.\n`);
    return true;
  }
  walk(absRoot);
  if (violations.length === 0) {
    process.stdout.write(`✅ verify-no-theater-tests — no theater patterns found in ${SOURCE_ROOT}/.\n`);
    return true;
  }
  process.stderr.write(`❌ verify-no-theater-tests: ${violations.length} theater test pattern(s)\n\n`);
  for (const v of violations) {
    process.stderr.write(`  ${v.file}:${v.line} [${v.pattern}]\n     ${v.snippet}\n`);
  }
  process.stderr.write(
    `\nReplace with specific assertions:\n` +
    `  trivial-true     → assert a fact the code under test produces\n` +
    `  empty-it         → write the test body, or delete the test\n` +
    `  negative-no-op   → assert the specific shape / value, not just "didn't throw"\n`,
  );
  return false;
}

// ════════════════════════════════════════════════════════════════════════
// Orchestrator
// ════════════════════════════════════════════════════════════════════════
const SUBCHECKS = {
  "coverage-threshold": checkCoverageThreshold,
  "test-naming": checkTestNaming,
  "e2e-db-safety": checkE2eDbSafety,
  "accessibility-wiring": checkAccessibilityWiring,
  "no-theater-tests": checkNoTheaterTests,
};

if (checkName !== null) {
  const fn = SUBCHECKS[checkName];
  if (!fn) {
    process.stderr.write(`❌ verify-tests: unknown --check "${checkName}". Valid: ${Object.keys(SUBCHECKS).join(", ")}\n`);
    process.exit(2);
  }
  process.exit(fn() ? 0 : 1);
}

// Run all — OR semantics: exit nonzero iff ANY sub-check fails.
let anyFail = false;
for (const name of Object.keys(SUBCHECKS)) {
  const ok = SUBCHECKS[name]();
  if (!ok) anyFail = true;
}
process.exit(anyFail ? 1 : 0);
