#!/usr/bin/env node

// ────────────────────────────────────────────────────────────────
// DO NOT EDIT THIS FILE.
//
// COPY of source-of-truth at
//   ~/.claude/standards/scripts/verify/verify-runtime.mjs
//
// Local edits will be overwritten the next time
//   bash ~/.claude/standards/scripts/install-slice-gates.sh
// runs. Edit the ORIGINAL and re-install.
// ────────────────────────────────────────────────────────────────
/**
 * verify-runtime.mjs
 *
 * Consolidated heavy / live-runtime gate. Bundles two sub-checks that each
 * exercise a real runtime rather than static analysis:
 *
 *   dev-server-boots  — spawns the project's `pnpm dev` (or equivalent) and
 *                       asserts an HTTP 2xx/3xx on the configured dev URL
 *                       within a timeout, with no error-level log lines.
 *                       Catches "compiles fine, app doesn't actually start"
 *                       (missing env vars, port collisions, broken
 *                       composition roots).
 *
 *   migration-replay  — replays every `drizzle/*.sql` migration, in filename
 *                       order, against a FRESH throwaway database on a real
 *                       Postgres cluster. Catches ordering bugs, syntax
 *                       errors, and "works on my already-migrated DB" drift.
 *
 * Usage:
 *   node verify-runtime.mjs                          run all sub-checks
 *   node verify-runtime.mjs --check dev-server-boots run one sub-check
 *   node verify-runtime.mjs --check migration-replay run one sub-check
 *
 * Exit (single --check): identical to the standalone gate it replaces —
 *   dev-server-boots: 0 real boot · 1 never-serves/error-lines · 2 BLOCKED
 *     (pnpm absent OR no dev script)
 *   migration-replay: 0 clean replay · 1 empty replay / bad migration / harness
 *     error
 * Exit (default, all): 0 iff every sub-check exits 0, else 1.
 *
 * Heavy gate (boots a real process / hits a real DB). Runs only in
 * `pnpm verify:full`, not the default chain.
 */

import { existsSync, readFileSync, readdirSync } from "node:fs";
import { spawn } from "node:child_process";
import { setTimeout as wait } from "node:timers/promises";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";

const require = createRequire(import.meta.url);

/* ────────────────────────────────────────────────────────────────────────
 * Sub-check: dev-server-boots
 * ──────────────────────────────────────────────────────────────────────── */

const ERROR_LINE_RE = /\b(?:error|fatal|uncaught|UnhandledPromiseRejection|Cannot find module|EADDRINUSE|ECONNREFUSED|TypeError|ReferenceError)\b/i;

// README.yaml lives at the git repo root, which may be ABOVE the package dir
// (these repos run gates from code/web while README.yaml sits two levels up).
// Walk up from cwd until we find it.
function findReadme(repoRoot) {
  let dir = repoRoot;
  for (let i = 0; i < 6; i++) {
    const p = `${dir}/README.yaml`;
    if (existsSync(p)) return p;
    const parent = dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  return null;
}

function readRepoConfig(repoRoot, YAML) {
  const readmePath = findReadme(repoRoot);
  if (!readmePath || !YAML) return {};
  try { return YAML.parse(readFileSync(readmePath, "utf8")) ?? {}; }
  catch { return {}; }
}

/**
 * Polls `url` every 250ms until it returns a 2xx/3xx OR `timeoutMs`
 * elapses. Resolves with { ok, status, ms } on success or false on
 * timeout.
 *
 * @param {string} url
 * @param {number} timeoutMs
 * @returns {Promise<{ ok: boolean, status: number | null, ms: number }>}
 */
export async function pollHttp(url, timeoutMs) {
  const startedAt = Date.now();
  while (Date.now() - startedAt < timeoutMs) {
    try {
      const resp = await fetch(url, { redirect: "manual" });
      if (resp.status >= 200 && resp.status < 400) {
        return { ok: true, status: resp.status, ms: Date.now() - startedAt };
      }
    } catch { /* not up yet */ }
    await wait(250);
  }
  return { ok: false, status: null, ms: Date.now() - startedAt };
}

/**
 * Scans a captured stdout/stderr blob for error-level log lines.
 *
 * @param {string} text
 * @returns {string[]}
 */
export function findErrorLines(text) {
  return text.split("\n").filter((line) => ERROR_LINE_RE.test(line));
}

function hasDevScript(repoRoot, scriptName) {
  const candidates = [
    `${repoRoot}/package.json`,
    `${repoRoot}/code/web/package.json`,
    `${repoRoot}/code/package.json`,
    `${repoRoot}/web/package.json`,
  ];
  for (const p of candidates) {
    if (!existsSync(p)) continue;
    try {
      const pkg = JSON.parse(readFileSync(p, "utf8"));
      if (pkg.scripts && pkg.scripts[scriptName]) return p;
    } catch { /* skip */ }
  }
  return null;
}

/**
 * @returns {Promise<number>} exit code — 0 boot ok, 1 never-serves/error-lines,
 *   2 BLOCKED (pnpm absent OR no dev script).
 */
async function runDevServerBoots() {
  const REPO_ROOT = process.cwd();
  let YAML;
  try { YAML = require("yaml"); } catch { /* optional */ }

  const repoConfig = readRepoConfig(REPO_ROOT, YAML);
  const DEV_URL = String(repoConfig.ui_screenshot_dev_server_url ?? "http://localhost:3000");
  const TIMEOUT_MS = Number(repoConfig.dev_boot_timeout_ms ?? 30000);
  const DEV_SCRIPT = String(repoConfig.dev_boot_script ?? "dev");

  // dependency check
  const pnpmCheck = spawn("pnpm", ["--version"], { stdio: "ignore" });
  await new Promise((res) => pnpmCheck.on("close", res));
  if (pnpmCheck.exitCode !== 0) {
    process.stderr.write(
      `🚧 verify-dev-server-boots: BLOCKED — pnpm not on PATH. Install pnpm or run from a shell with it.\n`,
    );
    return 2;
  }
  const pkgPath = hasDevScript(REPO_ROOT, DEV_SCRIPT);
  if (!pkgPath) {
    process.stderr.write(
      `🚧 verify-dev-server-boots: BLOCKED — no package.json declares a "${DEV_SCRIPT}" script. ` +
      `Set README.yaml.dev_boot_script if your script has a different name.\n`,
    );
    return 2;
  }

  const cwd = pkgPath.replace(/\/package\.json$/, "");
  const child = spawn("pnpm", ["run", DEV_SCRIPT], { cwd, stdio: ["ignore", "pipe", "pipe"] });
  let stdoutBuf = "";
  let stderrBuf = "";
  child.stdout.on("data", (b) => { stdoutBuf += b.toString(); });
  child.stderr.on("data", (b) => { stderrBuf += b.toString(); });

  let httpResult;
  try {
    httpResult = await pollHttp(DEV_URL, TIMEOUT_MS);
  } finally {
    child.kill("SIGTERM");
    await new Promise((res) => child.on("close", res));
  }

  const errorLines = findErrorLines(stdoutBuf + stderrBuf);

  if (!httpResult.ok) {
    process.stderr.write(
      `❌ verify-dev-server-boots: dev server did not respond at ${DEV_URL} within ${TIMEOUT_MS}ms\n\n`,
    );
    if (errorLines.length > 0) {
      process.stderr.write(`  Error lines from server output:\n`);
      for (const l of errorLines.slice(0, 20)) process.stderr.write(`    ${l}\n`);
    } else {
      process.stderr.write(`  Last 20 stdout lines:\n`);
      for (const l of stdoutBuf.split("\n").slice(-20)) process.stderr.write(`    ${l}\n`);
    }
    return 1;
  }
  if (errorLines.length > 0) {
    process.stderr.write(
      `❌ verify-dev-server-boots: dev server responded ${httpResult.status} at ${DEV_URL} in ${httpResult.ms}ms, ` +
      `but ${errorLines.length} error line(s) detected in stdout/stderr\n\n`,
    );
    for (const l of errorLines.slice(0, 20)) process.stderr.write(`  ${l}\n`);
    return 1;
  }
  process.stdout.write(
    `✅ verify-dev-server-boots — ${DEV_URL} returned ${httpResult.status} in ${httpResult.ms}ms; no errors in stdout.\n`,
  );
  return 0;
}

/* ────────────────────────────────────────────────────────────────────────
 * Sub-check: migration-replay
 *
 * ROOT is resolved relative to THIS file's install location (NOT cwd), the
 * same as the standalone gate: <ROOT>/scripts/verify/verify-runtime.mjs →
 * ../.. = <ROOT>. The empty-replay selftest depends on this fixed root.
 * ──────────────────────────────────────────────────────────────────────── */

function ownerUrl(root) {
  if (process.env.DATABASE_URL_OWNER) return process.env.DATABASE_URL_OWNER;
  const envPath = join(root, ".env.local");
  if (!existsSync(envPath)) return null;
  for (const line of readFileSync(envPath, "utf8").split("\n")) {
    const t = line.trim();
    if (t.startsWith("#") || !t.includes("=")) continue;
    const i = t.indexOf("=");
    if (t.slice(0, i).trim() === "DATABASE_URL_OWNER") return t.slice(i + 1).trim();
  }
  return null;
}

function sqlFiles(drizzleDir) {
  if (!existsSync(drizzleDir)) return [];
  return readdirSync(drizzleDir).filter((f) => f.endsWith(".sql")).sort();
}

/**
 * @returns {Promise<number>} exit code — 0 clean replay, 1 empty replay /
 *   bad migration / harness error.
 */
async function runMigrationReplay() {
  const ROOT = new URL("../..", import.meta.url).pathname;
  const DRIZZLE_DIR = join(ROOT, "drizzle");

  const files = sqlFiles(DRIZZLE_DIR);
  if (files.length === 0) {
    console.error("verify-migration-replay: no drizzle/*.sql migrations found — refusing to claim success on an empty replay");
    return 1;
  }
  const url = ownerUrl(ROOT);
  if (!url) {
    console.error("verify-migration-replay: DATABASE_URL_OWNER not set (env or .env.local) — cannot run replay");
    return 1;
  }

  let postgres;
  try { postgres = require("postgres"); }
  catch (err) {
    console.error("verify-migration-replay: failed to import `postgres`");
    console.error(`  ${err instanceof Error ? err.message : String(err)}`);
    return 1;
  }

  // maintenance connection on the same cluster (the default `postgres` db) to
  // CREATE/DROP the throwaway replay database.
  const maintUrl = new URL(url);
  maintUrl.pathname = "/postgres";
  const tmpDb = `replay_${String(process.pid)}_${String(Date.now()).slice(-6)}`;
  const replayUrl = new URL(url);
  replayUrl.pathname = `/${tmpDb}`;

  const admin = postgres(maintUrl.toString(), { max: 1 });
  let exitCode = 0;
  try {
    await admin.unsafe(`DROP DATABASE IF EXISTS ${tmpDb}`);
    await admin.unsafe(`CREATE DATABASE ${tmpDb}`);
    const db = postgres(replayUrl.toString(), { max: 1 });
    try {
      let n = 0;
      for (const f of files) {
        const sqlText = readFileSync(join(DRIZZLE_DIR, f), "utf8");
        try {
          await db.unsafe(sqlText);
          n += 1;
        } catch (err) {
          exitCode = 1;
          console.error(`verify-migration-replay: migration ${f} failed on a fresh database`);
          console.error(`  ${err instanceof Error ? err.message : String(err)}`);
          break;
        }
      }
      if (exitCode === 0) {
        console.log(`verify-migration-replay: OK (${String(n)} migration(s) applied to a fresh database)`);
      }
    } finally {
      await db.end({ timeout: 5 });
    }
  } catch (err) {
    exitCode = 1;
    console.error("verify-migration-replay: replay harness error");
    console.error(`  ${err instanceof Error ? err.message : String(err)}`);
  } finally {
    try { await admin.unsafe(`DROP DATABASE IF EXISTS ${tmpDb}`); } catch { /* best-effort */ }
    await admin.end({ timeout: 5 });
  }
  return exitCode;
}

/* ────────────────────────────────────────────────────────────────────────
 * CLI
 * ──────────────────────────────────────────────────────────────────────── */

const CHECKS = {
  "dev-server-boots": runDevServerBoots,
  "migration-replay": runMigrationReplay,
};

function parseCheck(argv) {
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === "--check") return argv[i + 1] ?? "";
    if (a.startsWith("--check=")) return a.slice("--check=".length);
  }
  return null;
}

async function main() {
  const requested = parseCheck(process.argv.slice(2));

  if (requested !== null) {
    const fn = CHECKS[requested];
    if (!fn) {
      process.stderr.write(
        `verify-runtime: unknown --check "${requested}". Valid: ${Object.keys(CHECKS).join(", ")}\n`,
      );
      return 2;
    }
    return await fn();
  }

  // Default: run all sub-checks; exit nonzero iff any fails.
  let failed = false;
  for (const fn of Object.values(CHECKS)) {
    const code = await fn();
    if (code !== 0) failed = true;
  }
  return failed ? 1 : 0;
}

function isCli() {
  return import.meta.url === `file://${process.argv[1]}`;
}

if (isCli()) {
  main()
    .then((code) => process.exit(code))
    .catch((e) => {
      process.stderr.write(`💥 verify-runtime: unexpected error — ${e.message}\n`);
      process.exit(2);
    });
}
