#!/usr/bin/env node

// ────────────────────────────────────────────────────────────────
// DO NOT EDIT THIS FILE.
//
// COPY of source-of-truth at
//   ~/.claude/standards/scripts/verify/verify-stamps.mjs
//
// Local edits will be overwritten the next time
//   bash ~/.claude/standards/scripts/install-slice-gates.sh
// runs. Edit the ORIGINAL and re-install.
// ────────────────────────────────────────────────────────────────
/**
 * verify-stamps — consolidated stamp/receipt gate. Three sub-checks that each
 * guard a different "the stamp must not lie" invariant live here behind one
 * dispatcher (each in its own closure; no top-level name collisions):
 *
 *   commit-stamp
 *     Pre-commit gate that refuses staged `<web>/src/**` behavior-file changes
 *     without a fresh (<30 min) verifier Mode A stamp on the owning slice.
 *     Reachable by exact name via the tiny shim verify/verify-commit-stamp.mjs
 *     (CLAUDE.md pre-action rules + install-slice-gates universal copy).
 *
 *   browser-validation-receipt
 *     Refuses a browser_validated stamp whose newest manual-results record is
 *     not a valid WALKER-SIGNED walk (BROWSER_VALIDATION.yaml.evidence).
 *
 *   trunk-integration
 *     Flags locked features that live on the current branch but never landed on
 *     main (BRANCHES_AND_COMMITS + PULL_REQUESTS).
 *
 * Usage:
 *   node scripts/verify/verify-stamps.mjs                 # run all three; exit nonzero iff any fails
 *   node scripts/verify/verify-stamps.mjs --check commit-stamp
 *   node scripts/verify/verify-stamps.mjs --check browser-validation-receipt [<repo-root>]
 *   node scripts/verify/verify-stamps.mjs --check trunk-integration [<repo-dir>] [--main <ref>]
 *
 * Env vars:
 *   WEB_SUBDIR       — commit-stamp src prefix (defaults "code/web"; "" for root-nested src/).
 *   WALKER_KEY_PATH  — browser-validation-receipt walker signing key (via _walker-receipt.mjs).
 */

import { execSync, spawnSync } from "node:child_process";
import { existsSync, readFileSync, readdirSync, statSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { pathToFileURL } from "node:url";

// Shared 30-min re-stamp grace window + slice-lock walk — single source in ../lib/locks.mjs.
import { SAME_COMMIT_GRACE_MS, findSliceLock } from "../lib/locks.mjs";
// Dual-format lock loader — every verifier routes lock reads through here.
import { loadLock } from "../lib/load-spec.mjs";

// ════════════════════════════════════════════════════════════════════════
// commit-stamp — pre-commit fresh-stamp gate
// ════════════════════════════════════════════════════════════════════════
async function checkCommitStamp() {
  const NAME = "verify-commit-stamp";

  let REPO_ROOT;
  try {
    REPO_ROOT = execSync("git rev-parse --show-toplevel", { encoding: "utf8" }).trim();
  } catch {
    process.stderr.write(`\n❌ ${NAME}: not in a git repo\n`);
    return 2;
  }

  const WEB_SUBDIR = process.env.WEB_SUBDIR ?? "code/web";
  const SRC_PREFIX = WEB_SUBDIR ? `${WEB_SUBDIR}/src/` : "src/";
  const SKIP_DIR_SEGMENTS = ["/__specs__/", "/__tests__/", "/__manual__/", "/__stories__/"];

  function readStagedPaths() {
    try {
      const out = execSync("git diff --cached --name-only", { cwd: REPO_ROOT, encoding: "utf8" });
      return out.split("\n").map((s) => s.trim()).filter((s) => s.length > 0);
    } catch {
      return [];
    }
  }

  function findLockFor(behaviorFile) {
    // Walk up from the behavior file's directory to the nearest owning slice lock.
    return findSliceLock(dirname(join(REPO_ROOT, behaviorFile)), REPO_ROOT);
  }

  function block(violations) {
    process.stderr.write("");
    process.stderr.write("\nBLOCKED: commit refused by verify-commit-stamp\n\n");
    process.stderr.write(
      `  One or more ${SRC_PREFIX}** behavior files are staged without a fresh\n` +
      `  verifier Mode A stamp on the owning slice. The orchestrator MUST route\n` +
      `  writes through coder, then through verifier (Mode A), before commit.\n\n`,
    );
    for (const v of violations) {
      process.stderr.write(`  • ${v.file}\n`);
      process.stderr.write(`      reason: ${v.reason}\n`);
      if (v.lock) process.stderr.write(`      lock:   ${relative(REPO_ROOT, v.lock)}\n`);
    }
    process.stderr.write(
      `\n  Fix path: invoke the verifier in Mode A on each slice. On green, the\n` +
      `  verifier re-stamps the lock; re-attempt commit.\n\n` +
      `  This hook lives at .git/hooks/pre-commit (local only).\n\n`,
    );
  }

  const staged = readStagedPaths();
  const behaviorFiles = staged.filter((p) => {
    if (!p.startsWith(SRC_PREFIX)) return false;
    if (!/\.(ts|tsx|mjs|js)$/.test(p)) return false;
    if (SKIP_DIR_SEGMENTS.some((seg) => p.includes(seg))) return false;
    return true;
  });

  if (behaviorFiles.length === 0) {
    return 0;
  }

  const now = Date.now();
  const violations = [];

  for (const file of behaviorFiles) {
    const lock = findLockFor(file);
    if (lock === null) {
      violations.push({
        file,
        reason: "no __specs__/standards-compliance.yaml found in any ancestor folder",
        lock: null,
      });
      continue;
    }
    // Route the lock read through the dual-format loader (loadLock takes the
    // __specs__ dir; the lock file lives at <dir>/standards-compliance.{md,yaml}).
    const loaded = loadLock(dirname(lock));
    if (!loaded.ok) {
      violations.push({ file, reason: `lock unreadable: ${loaded.error}`, lock });
      continue;
    }
    const status = loaded.value.status ?? null;
    const verified = loaded.value.verified ?? null;
    const lastValidated = loaded.value.last_validated ?? null;
    if (status !== "locked") {
      violations.push({ file, reason: `lock status is "${status ?? "(missing)"}" — must be "locked"`, lock });
      continue;
    }
    if (verified !== "100%") {
      violations.push({ file, reason: `lock verified is "${verified ?? "(missing)"}" — must be "100%"`, lock });
      continue;
    }
    if (lastValidated === null) {
      violations.push({ file, reason: "lock last_validated is missing", lock });
      continue;
    }
    const lastValidatedMs = Date.parse(lastValidated);
    if (Number.isNaN(lastValidatedMs)) {
      violations.push({ file, reason: `lock last_validated "${lastValidated}" is not valid ISO-8601`, lock });
      continue;
    }
    const ageMs = now - lastValidatedMs;
    if (ageMs > SAME_COMMIT_GRACE_MS) {
      const ageMin = Math.round(ageMs / 60000);
      violations.push({
        file,
        reason: `lock last_validated is ${ageMin} minutes old — must be within 30 min (verifier Mode A re-stamp required)`,
        lock,
      });
      continue;
    }
    if (ageMs < -60_000) {
      violations.push({
        file,
        reason: `lock last_validated is in the future by ${Math.round(-ageMs / 1000)}s — clock skew or bad stamp`,
        lock,
      });
      continue;
    }
  }

  if (violations.length > 0) {
    block(violations);
    return 1;
  }

  process.stdout.write(
    `✅ verify-commit-stamp — ${behaviorFiles.length} behavior file(s) backed by fresh locks\n`,
  );
  return 0;
}

// ════════════════════════════════════════════════════════════════════════
// browser-validation-receipt — walker-signed walk record gate
// ════════════════════════════════════════════════════════════════════════
async function checkBrowserValidationReceipt(restArgs) {
  const REPO_ROOT = restArgs.find((a) => !a.startsWith("--")) || process.cwd();
  const NAME = "verify-browser-validation-receipt";
  const IGNORE = new Set(["node_modules", ".git", ".next", ".turbo", "dist", "build", "out", "coverage", ".vercel"]);

  // Walker receipt helpers are only needed by this sub-check — import lazily so
  // the commit-stamp path (and planning-status repos that omit _walker-receipt)
  // never depend on it.
  const { verifyReceipt, loadKey } = await import("./_walker-receipt.mjs");
  const WALKER_KEY = loadKey();

  function walk(dir, match, acc = []) {
    let entries;
    try { entries = readdirSync(dir, { withFileTypes: true }); } catch { return acc; }
    for (const e of entries) {
      if (IGNORE.has(e.name)) continue;
      const p = join(dir, e.name);
      if (e.isDirectory()) walk(p, match, acc);
      else if (e.isFile() && match(e.name, p)) acc.push(p);
    }
    return acc;
  }

  function browserValidatedValue(text) {
    const m = text.match(/^\s*browser_validated\s*:\s*["']?([^"'\n#]+)["']?/m);
    if (!m) return null;
    const v = m[1].trim();
    if (!v || /^(n\/a|not[-_ ]?required|false|null|~)$/i.test(v)) return null;
    return v;
  }

  function findResultsDir(startDir) {
    let dir = startDir;
    for (let i = 0; i < 8; i++) {
      const cand = join(dir, "manual-results");
      if (existsSync(cand)) return cand;
      const parent = dirname(dir);
      if (parent === dir) break;
      dir = parent;
    }
    return null;
  }

  function newestRecord(resultsDir, stem) {
    let files;
    try { files = readdirSync(resultsDir).filter((f) => f.startsWith(`${stem}.`) && f.endsWith(".json")); } catch { return null; }
    let best = null, bestMs = -1;
    for (const f of files) {
      const p = join(resultsDir, f);
      let ms = 0;
      try { ms = statSync(p).mtimeMs; } catch { continue; }
      if (ms > bestMs) { bestMs = ms; best = p; }
    }
    return best;
  }

  function validateRecord(file) {
    let raw;
    try { raw = readFileSync(file, "utf8"); } catch { return "record unreadable"; }
    let obj;
    try { obj = JSON.parse(raw); } catch { return "record is not valid JSON"; }
    if (obj === null || typeof obj !== "object" || Array.isArray(obj)) return "record is not a JSON object";
    const sig = verifyReceipt(obj, WALKER_KEY);
    if (!sig.ok) return sig.reason;
    if (obj.ok !== true) return "record `ok` is false — the walk FAILED but the lock was stamped browser_validated";
    if (!Array.isArray(obj.observed) || obj.observed.length === 0) return "signed record has no `observed` steps — an empty walk is not a walk";
    const everyStepJudged = obj.observed.every((s) => s && typeof s === "object" && typeof s.verdict === "string" && s.verdict.trim());
    if (!everyStepJudged) return "at least one `observed` step has no verdict — the walk is incomplete";
    return null;
  }

  const compFiles = walk(REPO_ROOT, (name) => name === "standards-compliance.yaml");
  let stampedFeatures = 0;
  const violations = [];

  for (const comp of compFiles) {
    let text = "";
    try { text = readFileSync(comp, "utf8"); } catch { continue; }
    if (!browserValidatedValue(text)) continue;
    stampedFeatures++;
    const specsDir = dirname(comp);
    const featureDir = dirname(specsDir);
    const manualDir = join(specsDir, "manual");
    if (!existsSync(manualDir)) continue;
    let stems = [];
    try { stems = readdirSync(manualDir).filter((f) => f.endsWith(".md")).map((f) => f.slice(0, -3)); } catch { stems = []; }
    const resultsDir = findResultsDir(featureDir);
    if (!resultsDir) continue;
    for (const stem of stems) {
      const rec = newestRecord(resultsDir, stem);
      if (!rec) continue;
      const problem = validateRecord(rec);
      if (problem) violations.push(`${relative(REPO_ROOT, rec)} (flow "${stem}"): ${problem}`);
    }
  }

  if (stampedFeatures === 0) {
    process.stdout.write(`✅ ${NAME} — no browser_validated stamps in this repo; nothing to gate.\n`);
    return 0;
  }
  if (violations.length === 0) {
    process.stdout.write(`✅ ${NAME} — ${stampedFeatures} stamped feature(s); every checked walk record is real.\n`);
    return 0;
  }
  process.stderr.write(`\n❌ ${NAME}: ${violations.length} stub/invalid walk-record violation(s)\n`);
  for (const v of violations) process.stderr.write(`   - ${v}\n`);
  process.stderr.write(`\n   A browser_validated stamp requires a real walk record (ok:true + findings/steps). BROWSER_VALIDATION.yaml.evidence.\n`);
  return 1;
}

// ════════════════════════════════════════════════════════════════════════
// trunk-integration — locked-but-unmerged feature gate
// ════════════════════════════════════════════════════════════════════════
async function checkTrunkIntegration(restArgs) {
  const NAME = "verify-trunk-integration";
  const mainFlagIdx = restArgs.indexOf("--main");
  const MAIN_OVERRIDE = mainFlagIdx !== -1 ? restArgs[mainFlagIdx + 1] : null;
  const START = restArgs.find((a) => !a.startsWith("--") && a !== MAIN_OVERRIDE) || process.cwd();

  const git = (a) => spawnSync("git", ["-C", START, ...a], { encoding: "utf8" });
  const green = (msg) => { process.stdout.write(`✅ ${NAME} — ${msg}\n`); return 0; };

  let root;
  try {
    const r = git(["rev-parse", "--show-toplevel"]);
    if (r.status !== 0) return green("not a git repo; nothing to check");
    root = r.stdout.trim();
  } catch { return green("git unavailable; skipped"); }
  void root;

  const branch = (git(["rev-parse", "--abbrev-ref", "HEAD"]).stdout || "").trim();
  if (!branch || branch === "HEAD") return green("detached HEAD; nothing to integrate");
  if (branch === "main" || branch === "master") return green(`on ${branch}; nothing to integrate`);

  let mainRef = MAIN_OVERRIDE;
  if (!mainRef) {
    for (const cand of ["main", "master"]) {
      if (git(["rev-parse", "--verify", "--quiet", cand]).status === 0) { mainRef = cand; break; }
    }
  }
  if (!mainRef) return green("no main/master ref to compare against; skipped");

  const isLocked = (text) => /^\s*status\s*:\s*["']?locked\b/m.test(text || "");

  const listed = (git(["ls-tree", "-r", "--name-only", "HEAD"]).stdout || "")
    .split("\n").map((s) => s.trim())
    .filter((p) => p.endsWith("__specs__/standards-compliance.yaml"));

  const unmerged = [];
  for (const path of listed) {
    const headText = git(["show", `HEAD:${path}`]).stdout;
    if (!isLocked(headText)) continue;
    const onMain = git(["cat-file", "-e", `${mainRef}:${path}`]).status === 0;
    let mergedLocked = false;
    if (onMain) mergedLocked = isLocked(git(["show", `${mainRef}:${path}`]).stdout);
    if (!mergedLocked) unmerged.push(dirname(dirname(path)));
  }

  const features = [...new Set(unmerged)];
  const conforms = /^(feat|fix)\/\d{4}-/.test(branch);
  const flag = features.length >= 1 && (!conforms || features.length > 1);

  if (!flag) {
    const why = features.length === 0 ? "every locked feature is on main" : `1 locked feature in-progress on conforming ${branch}`;
    return green(`${why}`);
  }

  process.stderr.write(`\n⚠️  ${NAME}: ${features.length} locked feature(s) on "${branch}" NOT integrated to ${mainRef}\n`);
  for (const f of features) process.stderr.write(`   - ${f}\n`);
  const reasons = [];
  if (!conforms) reasons.push(`branch "${branch}" is not a short-lived (feat|fix)/NNNN-… branch`);
  if (features.length > 1) reasons.push(`${features.length} locked features accumulated off-trunk (one feature = one branch = one merge)`);
  process.stderr.write(`\n   Why flagged: ${reasons.join("; ")}.\n`);
  process.stderr.write(`\n   Integration flow — do this now, oldest-locked feature first (dependency order):\n`);
  process.stderr.write(`     1. Open a PR from "${branch}" (or a per-feature slice of it) into ${mainRef}.\n`);
  process.stderr.write(`     2. Let the green chain run; merge with a MERGE COMMIT (keeps the 100%-standards-met stamp on ${mainRef}).\n`);
  process.stderr.write(`     3. Re-run this gate until green — ${mainRef} then holds every locked feature above.\n`);
  process.stderr.write(`   Going forward: one feature = one short-lived feat/NNNN branch = one merge, AS IT LOCKS. Never a long-lived integration branch. BRANCHES_AND_COMMITS + PULL_REQUESTS + WRITING_ORDER.\n`);
  return 1;
}

// ════════════════════════════════════════════════════════════════════════
// Dispatcher
// ════════════════════════════════════════════════════════════════════════
const CHECKS = {
  "commit-stamp": checkCommitStamp,
  "browser-validation-receipt": checkBrowserValidationReceipt,
  "trunk-integration": checkTrunkIntegration,
};

async function main(argv) {
  const checkIdx = argv.indexOf("--check");
  if (checkIdx !== -1) {
    const selected = argv[checkIdx + 1];
    if (!selected || !(selected in CHECKS)) {
      process.stderr.write(
        `verify-stamps: unknown --check "${selected ?? ""}" (expected one of: ${Object.keys(CHECKS).join(", ")})\n`,
      );
      return 2;
    }
    const rest = argv.filter((_, i) => i !== checkIdx && i !== checkIdx + 1);
    return CHECKS[selected](rest);
  }
  // Default: run all three; exit nonzero iff any fails.
  let worst = 0;
  for (const name of Object.keys(CHECKS)) {
    const code = await CHECKS[name](argv);
    if (code !== 0) worst = 1;
  }
  return worst;
}

// CLI guard — run only when invoked directly, not when imported.
if (import.meta.url === pathToFileURL(process.argv[1] || "").href) {
  main(process.argv.slice(2)).then((code) => process.exit(code));
}

export { checkCommitStamp, checkBrowserValidationReceipt, checkTrunkIntegration };
