#!/usr/bin/env node

// ────────────────────────────────────────────────────────────────
// DO NOT EDIT THIS FILE.
//
// COPY of source-of-truth at
//   ~/.claude/standards/scripts/verify/verify-specs.mjs
//
// Local edits will be overwritten the next time
//   bash ~/.claude/standards/scripts/install-slice-gates.sh
// runs. Edit the ORIGINAL and re-install.
// ────────────────────────────────────────────────────────────────
// verify-specs — consolidated spec/doc/structure gate (plan target T4).
//
// Runs 7 sub-checks in one process. Default (no flag) runs all 7 and exits
// nonzero iff any fails. `--check <name>` runs exactly one.
//
//   names: docs, flow-coverage, manual-playbooks, source-coverage,
//          no-padding-folders, no-stray-scaffolding, setup-headers
//
// Each sub-check preserves its original no-op-green short-circuit, exact
// stderr messages, and exact exit codes. spec.yaml reads (source-coverage)
// route through the shared dual-format loader (lib/load-spec.mjs) so a
// Markdown-fenced machine block OR a legacy .yaml both resolve; the parsed
// shape is identical for .yaml.

import {
  existsSync,
  readFileSync,
  readdirSync,
  statSync,
} from "node:fs";
import { readdir, readFile as readFileAsync } from "node:fs/promises";
import { basename, dirname, join, relative, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

import { listAllDirs, listAllFiles } from "../lib/walk.mjs";
import { toKebabCandidates } from "../lib/kebab.mjs";
import { listExportedBehaviors } from "../lib/exports.mjs";
import { loadSpec } from "../lib/load-spec.mjs";

const __filename = fileURLToPath(import.meta.url);
const SCRIPT_DIR = dirname(__filename);
const ROOT_DIR = resolve(SCRIPT_DIR, "..", "..");
const DEFAULT_SRC = resolve(ROOT_DIR, "src");
const DEFAULT_E2E = resolve(ROOT_DIR, "e2e");
const DEFAULT_APP = resolve(ROOT_DIR, "src", "app");

// ════════════════════════════════════════════════════════════════════════
// docs — unified documentation verifier.
// ════════════════════════════════════════════════════════════════════════
const docsGate = (() => {
  const SPEC_HEADINGS_NEW = [
    "Purpose",
    "Inputs",
    "Outputs",
    "Invariants",
    "Permissions used",
    "Cross-module dependencies",
    "Edge cases",
    "Error modes",
    "Data shape touched",
    "Flows",
  ];
  const SPEC_NEW_DISTINCTIVE = ["Invariants", "Permissions used"];
  const FLOW_HEADINGS_NEW = [
    "Pre-conditions",
    "Sequence",
    "Branch points",
    "Failure paths",
    "Post-conditions",
  ];
  const FLOW_NEW_DISTINCTIVE = ["Pre-conditions"];
  const FLOW_HEADINGS_LEGACY = [
    "Paths",
    "Flow Diagram",
    "Error Exits",
    "Side Effects (detailed)",
    "AI Chat Agent Guidance",
  ];
  const FLOW_DOC_EXTENSIONS = [".flow.md", ".flow.yaml"];
  const ALLOWED_FRONTMATTER_KEYS = new Set([
    "source",
    "symbol",
    "inputs",
    "returns",
    "throws",
    "calls",
    "called_by",
    "transaction",
    "ai_agent_action",
    "flow",
    "kind",
    "emits_events",
    "side_effects_on_success",
    "side_effects_on_failure",
    "test",
    "spec",
  ]);
  const BACKUP_SEGMENT = "__specs__.backup";

  function isInsideBackupFolder(path) {
    return path.split("/").includes(BACKUP_SEGMENT);
  }

  const defaultExistsSync = (p) => existsSync(p);
  const defaultReadFile = (p) => readFileSync(p, "utf8");
  const defaultReadDir = (p) => readdirSync(p);
  const defaultStatFile = (p) => statSync(p);
  const defaultListAllDirs = (p) => listAllDirs(p);
  const defaultListAllFiles = (p) => listAllFiles(p);
  const defaultStdoutWrite = (s) => process.stdout.write(s);
  const defaultStderrWrite = (s) => process.stderr.write(s);

  function extractH2(src) {
    const out = [];
    for (const line of src.split("\n")) {
      const m = line.match(/^##\s+(.+?)\s*$/);
      if (m) out.push(m[1].trim());
    }
    return out;
  }

  function sectionBodies(src) {
    const out = {};
    let current = "";
    for (const rawLine of src.split("\n")) {
      const h2 = rawLine.match(/^##\s+(.+?)\s*$/);
      if (h2) {
        current = h2[1].trim();
        out[current] = [];
        continue;
      }
      if (!current) continue;
      if (rawLine.match(/^#\s/)) continue;
      const trimmed = rawLine.trim();
      if (trimmed === "" || trimmed.startsWith("---")) continue;
      out[current].push(rawLine);
    }
    return out;
  }

  function sectionBodyText(src, heading) {
    const escaped = heading.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    const re = new RegExp(`^##\\s+${escaped}\\s*$`, "m");
    const parts = src.split(re);
    if (parts.length < 2) return "";
    const after = parts[1];
    const nextH2 = after.match(/\n##\s/);
    if (nextH2 === null) return after;
    return after.slice(0, after.indexOf(nextH2[0]));
  }

  function extractFrontmatter(src) {
    if (!src.startsWith("---\n")) return null;
    const end = src.indexOf("\n---\n", 4);
    if (end === -1) return null;
    return src.slice(4, end);
  }

  function splitFrontmatter(src) {
    if (!src.startsWith("---\n")) return { frontmatter: null, body: src };
    const end = src.indexOf("\n---\n", 4);
    if (end === -1) return { frontmatter: null, body: src };
    return { frontmatter: src.slice(4, end), body: src.slice(end + 5) };
  }

  function parseFrontmatterKeys(frontmatter) {
    const keys = [];
    for (const line of frontmatter.split("\n")) {
      if (line === "" || line.startsWith("#")) continue;
      if (line.startsWith(" ") || line.startsWith("\t") || line.startsWith("-"))
        continue;
      const m = line.match(/^([A-Za-z_][\w-]*)\s*:/);
      if (!m) {
        return { keys, invalid: `unparseable line: "${line}"` };
      }
      keys.push(m[1]);
    }
    return { keys, invalid: null };
  }

  function isNewFormSpec(headings) {
    return SPEC_NEW_DISTINCTIVE.every((h) => headings.includes(h));
  }

  function isNewFormFlow(headings) {
    return FLOW_NEW_DISTINCTIVE.every((h) => headings.includes(h));
  }

  function checkSpecMd(file, relPath, injected = {}) {
    const readFile = injected.readFile ?? defaultReadFile;
    const exists = injected.existsSync ?? defaultExistsSync;
    const errors = [];
    const src = readFile(file);
    const headings = extractH2(src);

    if (headings.length === 0) {
      errors.push(`${relPath}: no \`## \` headings found`);
      return errors;
    }

    const seen = new Set();
    for (const h of headings) {
      if (seen.has(h)) {
        errors.push(`${relPath}: duplicate heading "${h}"`);
      }
      seen.add(h);
    }

    const bodies = sectionBodies(src);
    for (const h of headings) {
      if (bodies[h] !== undefined && bodies[h].length === 0) {
        errors.push(
          `${relPath}: section "## ${h}" is empty (use "None." if intentional)`,
        );
      }
    }

    if (isNewFormSpec(headings)) {
      for (const h of SPEC_HEADINGS_NEW) {
        if (!headings.includes(h)) {
          errors.push(
            `${relPath}: NEW-form spec missing heading "## ${h}" (SPEC_TEMPLATE.md)`,
          );
        }
      }
      if (bodies["Flows"]) {
        const dir = dirname(file);
        for (const line of bodies["Flows"]) {
          const m = line.match(/(?:\(|\s|^)(\.?\/?flows\/[^)\s]+\.flow\.md)/);
          if (!m) continue;
          const target = m[1].replace(/^\.\//, "");
          const fullTarget = join(dir, target);
          if (!exists(fullTarget)) {
            errors.push(
              `${relPath}: ## Flows links to "${target}" which does not exist`,
            );
          }
        }
      }
    }

    return errors;
  }

  function checkFlowMd(file, relPath, injected = {}) {
    const readFile = injected.readFile ?? defaultReadFile;
    const errors = [];
    let src = readFile(file);

    if (!file.includes("/__specs__/flows/")) {
      errors.push(`${relPath}: flow doc must live inside __specs__/flows/`);
    }

    const { frontmatter, body } = splitFrontmatter(src);
    if (frontmatter !== null) {
      const { keys, invalid } = parseFrontmatterKeys(frontmatter);
      if (invalid) {
        errors.push(`${relPath}: malformed frontmatter (${invalid})`);
      }
      for (const k of keys) {
        if (!ALLOWED_FRONTMATTER_KEYS.has(k)) {
          errors.push(
            `${relPath}: frontmatter key "${k}" not in the allowlist (allowed: ${[...ALLOWED_FRONTMATTER_KEYS].sort().join(", ")})`,
          );
        }
      }
    }
    src = body;

    const headings = extractH2(src);
    if (headings.length === 0) {
      errors.push(`${relPath}: no \`## \` headings found`);
      return errors;
    }

    const seen = new Set();
    for (const h of headings) {
      if (seen.has(h)) {
        errors.push(`${relPath}: duplicate heading "${h}"`);
      }
      seen.add(h);
    }

    const bodies = sectionBodies(src);
    for (const h of headings) {
      if (bodies[h] !== undefined && bodies[h].length === 0) {
        errors.push(
          `${relPath}: section "## ${h}" is empty (use "None." if intentional)`,
        );
      }
    }

    if (isNewFormFlow(headings)) {
      for (const h of FLOW_HEADINGS_NEW) {
        if (!headings.includes(h)) {
          errors.push(
            `${relPath}: NEW-form flow missing heading "## ${h}" (FLOW_TEMPLATE.md)`,
          );
        }
      }
      const diagIdx = headings.indexOf("Diagram");
      const preIdx = headings.indexOf("Pre-conditions");
      if (diagIdx !== -1 && preIdx !== -1 && diagIdx > preIdx) {
        errors.push(
          `${relPath}: optional "## Diagram" heading must precede "## Pre-conditions"`,
        );
      }
      if (diagIdx !== -1) {
        const diagBody = sectionBodyText(src, "Diagram");
        if (!/```mermaid/.test(diagBody)) {
          errors.push(
            `${relPath}: "## Diagram" must contain a \`\`\`mermaid\`\`\` code fence`,
          );
        }
      }
    } else {
      const legacyHits = FLOW_HEADINGS_LEGACY.filter((h) =>
        headings.includes(h),
      ).length;
      if (legacyHits === 0) {
        errors.push(
          `${relPath}: flow doc carries neither NEW-form headings ` +
            `(${FLOW_HEADINGS_NEW.join(", ")}) nor any LEGACY heading ` +
            `(${FLOW_HEADINGS_LEGACY.join(", ")}); found: ${headings.map((h) => `"${h}"`).join(", ")}`,
        );
      }
      if (headings.includes("Flow Diagram")) {
        const fdBody = sectionBodyText(src, "Flow Diagram");
        if (!/```mermaid/.test(fdBody)) {
          errors.push(
            `${relPath}: "## Flow Diagram" must contain a \`\`\`mermaid\`\`\` code fence`,
          );
        }
      }
    }

    return errors;
  }

  function checkCodeConfidenceMd(file, relPath, injected = {}) {
    const readFile = injected.readFile ?? defaultReadFile;
    const errors = [];
    const src = readFile(file);

    const gateRows = src.match(/^\|\s*\d+\s*\|/gm) ?? [];
    if (gateRows.length !== 10) {
      errors.push(
        `${relPath}: expected 10 gate rows, found ${gateRows.length}`,
      );
    }

    if (!/Overall confidence:/.test(src)) {
      errors.push(`${relPath}: missing "Overall confidence:" line`);
    }

    if (src.includes("❌")) {
      errors.push(`${relPath}: contains ❌ (hard fail symbol)`);
    }

    return errors;
  }

  function isModuleLevelSpecsDir(dir, srcDir) {
    const rel = relative(srcDir, dir).split("\\").join("/");
    return /^features\/[^/]+\/__specs__$/.test(rel);
  }

  function checkSpecsFolder(specsDir, relPath, srcDir, injected = {}) {
    const exists = injected.existsSync ?? defaultExistsSync;
    const readDir = injected.readDir ?? defaultReadDir;
    const statFile = injected.statFile ?? defaultStatFile;
    const errors = [];

    const specMd = join(specsDir, "spec.md");
    const ccMd = join(specsDir, "CODE_CONFIDENCE.md");
    const lockMd = join(specsDir, "standards-compliance.md");
    const lockYaml = join(specsDir, "standards-compliance.yaml");
    const flowsDir = join(specsDir, "flows");

    if (!exists(specMd)) {
      errors.push(`MISSING spec.md in ${relPath}`);
    }

    if (isModuleLevelSpecsDir(specsDir, srcDir)) {
      if (!exists(ccMd) && !exists(lockMd) && !exists(lockYaml)) {
        errors.push(
          `MISSING CODE_CONFIDENCE.md OR standards-compliance.yaml in ${relPath} (module-level landing zones must carry the scorecard or the new lock file)`,
        );
      }
    }

    if (exists(flowsDir) && statFile(flowsDir).isDirectory()) {
      const flowDocs = readDir(flowsDir).filter((f) =>
        FLOW_DOC_EXTENSIONS.some((ext) => f.endsWith(ext)),
      );
      if (flowDocs.length === 0) {
        const tried = FLOW_DOC_EXTENSIONS.map((e) => `*${e}`).join(" | ");
        errors.push(`MISSING at least one ${tried} in ${relPath}/flows/`);
      }
    }

    return errors;
  }

  function audit(roots, injected = {}) {
    const exists = injected.existsSync ?? defaultExistsSync;
    const listDirs = injected.listAllDirs ?? defaultListAllDirs;
    const listFiles = injected.listAllFiles ?? defaultListAllFiles;
    const errors = [];
    let specsFoldersChecked = 0;
    let specsChecked = 0;
    let flowsChecked = 0;
    let ccChecked = 0;

    for (const base of [roots.src, roots.e2e]) {
      if (!exists(base)) continue;
      for (const dir of listDirs(base)) {
        if (!dir.endsWith("/__specs__")) continue;
        if (isInsideBackupFolder(dir)) continue;
        specsFoldersChecked += 1;
        const rel = relative(ROOT_DIR, dir);
        errors.push(
          ...checkSpecsFolder(dir, rel, roots.src, {
            existsSync: injected.existsSync,
            readDir: injected.readDir,
            statFile: injected.statFile,
          }),
        );
      }
    }

    for (const base of [roots.src, roots.e2e]) {
      if (!exists(base)) continue;
      for (const file of listFiles(base)) {
        if (isInsideBackupFolder(file)) continue;
        const rel = relative(ROOT_DIR, file);
        if (file.endsWith("/__specs__/spec.md")) {
          specsChecked += 1;
          errors.push(
            ...checkSpecMd(file, rel, {
              readFile: injected.readFile,
              existsSync: injected.existsSync,
            }),
          );
        } else if (file.endsWith(".flow.md")) {
          flowsChecked += 1;
          errors.push(...checkFlowMd(file, rel, { readFile: injected.readFile }));
        } else if (file.endsWith("/CODE_CONFIDENCE.md")) {
          ccChecked += 1;
          errors.push(
            ...checkCodeConfidenceMd(file, rel, { readFile: injected.readFile }),
          );
        }
      }
    }

    return { errors, specsFoldersChecked, specsChecked, flowsChecked, ccChecked };
  }

  function formatReport(result) {
    if (result.errors.length === 0) {
      return {
        exitCode: 0,
        stdout: `verify-docs: OK (${String(result.specsFoldersChecked)} __specs__ folder(s); ${String(result.specsChecked)} spec.md, ${String(result.flowsChecked)} flow.md, ${String(result.ccChecked)} CODE_CONFIDENCE.md checked)\n`,
        stderr: "",
      };
    }
    const lines = [`verify-docs: ${String(result.errors.length)} issue(s)`];
    for (const e of result.errors) lines.push(`  ${e}`);
    return { exitCode: 1, stdout: "", stderr: `${lines.join("\n")}\n` };
  }

  function main(io = {}) {
    const src = io.src ?? DEFAULT_SRC;
    const e2e = io.e2e ?? DEFAULT_E2E;
    const write = io.write ?? defaultStdoutWrite;
    const writeErr = io.writeErr ?? defaultStderrWrite;
    const result = audit(
      { src, e2e },
      {
        existsSync: io.existsSync,
        listAllDirs: io.listAllDirs,
        listAllFiles: io.listAllFiles,
        readFile: io.readFile,
        readDir: io.readDir,
        statFile: io.statFile,
      },
    );
    const report = formatReport(result);
    if (report.stdout) write(report.stdout);
    if (report.stderr) writeErr(report.stderr);
    return { exitCode: report.exitCode };
  }

  return { main };
})();

// ════════════════════════════════════════════════════════════════════════
// flow-coverage — every exported behavior has a co-located flow doc.
// ════════════════════════════════════════════════════════════════════════
const flowCoverageGate = (() => {
  const FLOW_DOC_EXTENSIONS = [".flow.yaml", ".flow.md"];

  const defaultExistsSync = (p) => existsSync(p);
  const defaultReadFile = (p) => readFileSync(p, "utf8");
  const defaultListFiles = (p) => listAllFiles(p);
  const defaultListExportedBehaviors = (p) => listExportedBehaviors(p);
  const defaultStdoutWrite = (s) => process.stdout.write(s);
  const defaultStderrWrite = (s) => process.stderr.write(s);

  function isInScope(filePath, injected = {}) {
    const readFile = injected.readFile ?? defaultReadFile;
    const name = basename(filePath);
    if (name === "types.ts" || name === "index.ts") return false;
    if (name.endsWith(".test.ts") || name.endsWith(".test.tsx")) return false;
    if (name.endsWith(".config.ts")) return false;
    if (filePath.includes("/__tests__/")) return false;
    if (filePath.includes("/__specs__/")) return false;
    if (filePath.includes("/__specs__.backup/")) return false;
    if (filePath.endsWith(".d.ts")) return false;
    if (!filePath.endsWith(".ts") && !filePath.endsWith(".tsx")) return false;

    const head = readFile(filePath).slice(0, 2000);
    if (/SETUP FILE\./.test(head)) return false;

    return true;
  }

  function flowDocCandidates(behaviorName) {
    const kebabs = toKebabCandidates(behaviorName);
    const out = [];
    for (const k of kebabs) {
      for (const ext of FLOW_DOC_EXTENSIONS) {
        out.push(`${k}${ext}`);
      }
    }
    return out;
  }

  function audit(srcDir, injected = {}) {
    const listFiles = injected.listFiles ?? defaultListFiles;
    const listBehaviors =
      injected.listExportedBehaviors ?? defaultListExportedBehaviors;
    const exists = injected.existsSync ?? defaultExistsSync;

    const missing = [];
    let exportedCount = 0;

    for (const file of listFiles(srcDir)) {
      if (!isInScope(file, { readFile: injected.readFile })) continue;
      const behaviors = listBehaviors(file);
      if (behaviors.length === 0) continue;
      const flowsDir = join(dirname(file), "__specs__", "flows");
      for (const b of behaviors) {
        exportedCount += 1;
        const candidates = flowDocCandidates(b.name);
        const found = candidates.some((c) => exists(join(flowsDir, c)));
        if (!found) {
          missing.push({
            flowsDir,
            behavior: b.name,
            sourceFile: file,
            candidates,
          });
        }
      }
    }

    return { exportedCount, missing };
  }

  function formatReport(result, rootDir) {
    if (result.missing.length === 0) {
      return {
        exitCode: 0,
        stdout: `verify-flow-coverage: OK (${String(result.exportedCount)} exported behavior(s) checked)\n`,
        stderr: "",
      };
    }
    const lines = [
      `verify-flow-coverage: ${String(result.missing.length)} missing flow doc(s)`,
    ];
    for (const m of result.missing) {
      const tried = m.candidates.join(" | ");
      lines.push(
        `  MISSING: ${relative(rootDir, m.flowsDir)}/{${tried}} for export ${m.behavior} in ${relative(rootDir, m.sourceFile)}`,
      );
    }
    return {
      exitCode: 1,
      stdout: "",
      stderr: `${lines.join("\n")}\n`,
    };
  }

  function main(io = {}) {
    const srcDir = io.srcDir ?? DEFAULT_SRC;
    const rootDir = io.rootDir ?? ROOT_DIR;
    const write = io.write ?? defaultStdoutWrite;
    const writeErr = io.writeErr ?? defaultStderrWrite;
    const result = audit(srcDir, {
      listFiles: io.listFiles,
      listExportedBehaviors: io.listExportedBehaviors,
      existsSync: io.existsSync,
      readFile: io.readFile,
    });
    const report = formatReport(result, rootDir);
    if (report.stdout) write(report.stdout);
    if (report.stderr) writeErr(report.stderr);
    return { exitCode: report.exitCode };
  }

  return { main };
})();

// ════════════════════════════════════════════════════════════════════════
// manual-playbooks — every callable surface has a runnable markdown manual.
// ════════════════════════════════════════════════════════════════════════
const manualPlaybooksGate = (() => {
  const REQUIRED_SECTIONS = [
    "## Target",
    "## Preconditions",
    "## Steps",
    "## Assertions",
    "## Report",
  ];

  const defaultListAllDirs = (p) => listAllDirs(p);
  const defaultReadDirSync = (p) => readdirSync(p);
  const defaultStatSync = (p) => statSync(p);
  const defaultExistsSync = (p) => existsSync(p);
  const defaultReadFile = (p) => readFileSync(p, "utf8");
  const defaultStdoutWrite = (s) => process.stdout.write(s);
  const defaultStderrWrite = (s) => process.stderr.write(s);

  function isSurfaceFolder(dir, j = {}) {
    const readDir = j.readDir ?? defaultReadDirSync;
    const statFile = j.statFile ?? defaultStatSync;
    let entries;
    try {
      entries = readDir(dir);
    } catch {
      return false;
    }
    for (const entry of entries) {
      if (entry !== "route.ts" && entry !== "page.tsx") continue;
      try {
        if (statFile(join(dir, entry)).isFile()) return true;
      } catch {
        continue;
      }
    }
    return false;
  }

  function manualFiles(folder, j = {}) {
    const exists = j.existsSync ?? defaultExistsSync;
    const readDir = j.readDir ?? defaultReadDirSync;
    const dir = join(folder, "__specs__", "manual");
    if (!exists(dir)) return { md: [], yaml: [] };
    let names;
    try {
      names = readDir(dir);
    } catch {
      return { md: [], yaml: [] };
    }
    return {
      md: names.filter((n) => n.endsWith(".md")).map((n) => join(dir, n)),
      yaml: names.filter((n) => n.endsWith(".yaml") || n.endsWith(".yml")).map((n) => join(dir, n)),
    };
  }

  function escapeRegExp(s) {
    return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  }

  function checkFlowMd(text) {
    const problems = [];
    for (const h of REQUIRED_SECTIONS) {
      if (!new RegExp(`^${escapeRegExp(h)}\\s*$`, "m").test(text)) {
        problems.push(`missing section "${h}"`);
      }
    }
    if (!/must\s+not/i.test(text)) {
      problems.push('no "MUST NOT" assertion — a flow must state what must NOT happen (adversarial)');
    }
    if (!/\/api\/v1\/manual-results/.test(text)) {
      problems.push("Report section does not name the POST /api/v1/manual-results route");
    }
    return problems;
  }

  function audit(appRoot, j = {}) {
    const listDirs = j.listDirs ?? defaultListAllDirs;
    const readDir = j.readDir ?? defaultReadDirSync;
    const statFile = j.statFile ?? defaultStatSync;
    const exists = j.existsSync ?? defaultExistsSync;
    const readFile = j.readFile ?? defaultReadFile;

    const errors = [];
    let surfaces = 0;
    let flows = 0;

    for (const dir of listDirs(appRoot)) {
      if (!isSurfaceFolder(dir, { readDir, statFile })) continue;
      surfaces += 1;
      const rel = relative(ROOT_DIR, dir);
      const { md, yaml } = manualFiles(dir, { existsSync: exists, readDir });
      for (const y of yaml) {
        errors.push(`LEGACY_YAML ${relative(ROOT_DIR, y)} — migrate to a runnable .md flow`);
      }
      if (md.length === 0) {
        errors.push(`MISSING __specs__/manual/<flow>.md for ${rel} (a runnable adversarial flow is mandatory)`);
        continue;
      }
      for (const file of md) {
        flows += 1;
        const relFile = relative(ROOT_DIR, file);
        for (const p of checkFlowMd(readFile(file))) errors.push(`${relFile}: ${p}`);
      }
    }
    return { errors, surfaces, flows };
  }

  function formatReport(r) {
    if (r.errors.length === 0) {
      return {
        exitCode: 0,
        stdout: `verify-manual-playbooks: OK (${String(r.surfaces)} surface(s) checked, ${String(r.flows)} runnable .md flow(s))\n`,
        stderr: "",
      };
    }
    const lines = [`verify-manual-playbooks: ${String(r.errors.length)} issue(s)`];
    for (const e of r.errors) lines.push(`  ${e}`);
    return { exitCode: 1, stdout: "", stderr: `${lines.join("\n")}\n` };
  }

  function main(io = {}) {
    const app = io.app ?? DEFAULT_APP;
    const write = io.write ?? defaultStdoutWrite;
    const writeErr = io.writeErr ?? defaultStderrWrite;
    const result = audit(app, {
      listDirs: io.listDirs,
      readDir: io.readDir,
      statFile: io.statFile,
      existsSync: io.existsSync,
      readFile: io.readFile,
    });
    const report = formatReport(result);
    if (report.stdout) write(report.stdout);
    if (report.stderr) writeErr(report.stderr);
    return { exitCode: report.exitCode };
  }

  return { main };
})();

// ════════════════════════════════════════════════════════════════════════
// no-stray-scaffolding — old-style scaffolding outside __specs__/ blocked.
// ════════════════════════════════════════════════════════════════════════
const noStrayGate = (() => {
  const defaultListAllDirs = (p) => listAllDirs(p);
  const defaultListAllFiles = (p) => listAllFiles(p);
  const defaultStdoutWrite = (s) => process.stdout.write(s);
  const defaultStderrWrite = (s) => process.stderr.write(s);

  const BACKUP_SEGMENT = "__specs__.backup";

  function isInsideBackupFolder(path) {
    const segments = path.split("/");
    return segments.includes(BACKUP_SEGMENT);
  }

  function classifyDirStray(dir) {
    const segments = dir.split("/");
    const last = segments[segments.length - 1];
    const parent = segments[segments.length - 2];
    if (last === "flows" && parent !== "__specs__") {
      return { kind: "flows-outside-specs", detail: "flows/ must live inside __specs__/" };
    }
    if (last === "specs" || last === "__spec__" || last === "_specs_") {
      return { kind: "wrong-specs-folder", detail: "must use __specs__/" };
    }
    return null;
  }

  function classifyFileStray(file) {
    const fileName = file.split("/").pop();
    if (fileName === "FLOWS.md") {
      return {
        kind: "flows-md",
        detail: "no FLOWS.md anywhere — AI agent crawls __specs__/",
      };
    }
    if (fileName === "CODE_CONFIDENCE.md" && !file.includes("/__specs__/")) {
      return {
        kind: "code-confidence-outside-specs",
        detail: "CODE_CONFIDENCE.md must live inside __specs__/",
      };
    }
    return null;
  }

  function audit(roots, injected = {}) {
    const listDirs = injected.listDirs ?? defaultListAllDirs;
    const listFiles = injected.listFiles ?? defaultListAllFiles;
    const strays = [];

    for (const root of roots) {
      for (const dir of listDirs(root)) {
        if (isInsideBackupFolder(dir)) continue;
        const verdict = classifyDirStray(dir);
        if (verdict !== null) {
          strays.push({ path: dir, kind: verdict.kind, detail: verdict.detail });
        }
      }
      for (const file of listFiles(root)) {
        if (isInsideBackupFolder(file)) continue;
        const verdict = classifyFileStray(file);
        if (verdict !== null) {
          strays.push({ path: file, kind: verdict.kind, detail: verdict.detail });
        }
      }
    }

    return { strays };
  }

  function formatReport(result, rootDir) {
    if (result.strays.length === 0) {
      return {
        exitCode: 0,
        stdout: "verify-no-stray-scaffolding: OK (no strays found)\n",
        stderr: "",
      };
    }
    const lines = [
      `verify-no-stray-scaffolding: ${String(result.strays.length)} stray item(s)`,
    ];
    for (const s of result.strays) {
      lines.push(`  STRAY: ${relative(rootDir, s.path)} (${s.detail})`);
    }
    return {
      exitCode: 1,
      stdout: "",
      stderr: `${lines.join("\n")}\n`,
    };
  }

  function main(io = {}) {
    const src = io.src ?? DEFAULT_SRC;
    const e2e = io.e2e ?? DEFAULT_E2E;
    const rootDir = io.rootDir ?? ROOT_DIR;
    const write = io.write ?? defaultStdoutWrite;
    const writeErr = io.writeErr ?? defaultStderrWrite;
    const result = audit([src, e2e], {
      listDirs: io.listDirs,
      listFiles: io.listFiles,
    });
    const report = formatReport(result, rootDir);
    if (report.stdout) write(report.stdout);
    if (report.stderr) writeErr(report.stderr);
    return { exitCode: report.exitCode };
  }

  return { main };
})();

// ════════════════════════════════════════════════════════════════════════
// setup-headers — SETUP FILE. marker on architectural files (two-way).
// ════════════════════════════════════════════════════════════════════════
const setupHeadersGate = (() => {
  const SETUP_GLOBS = [
    "db/client/client.ts",
    "db/drizzle-scope/drizzle-scope.ts",
    "lib/clock/system/system-clock.ts",
    "lib/cloud-logging/google/google-cloud-logging-reader.ts",
    "lib/hashing/argon2/argon2-hasher.ts",
    "lib/logger/logger/logger.ts",
    "lib/logger/config/config.ts",
    "events/in-process/event-bus/event-bus.ts",
    "events/in-process/publisher/publisher.ts",
    "events/in-process/subscriber/subscriber.ts",
    "modules/*/composition-root.ts",
    "modules/*/openapi-registrations.ts",
    "modules/*/*/openapi-registrations.ts",
    "db/test/setup/setup.ts",
    "db/test/server-only-shim/server-only-shim.ts",
    "db/test/scenarios/scenarios.ts",
    "db/test/principals/principals.ts",
    "lib/api/result/result.ts",
    "lib/api/status-codes/status-codes.ts",
    "app/layout.tsx",
    "app/page.tsx",
    "middleware.ts",
    "db/seed/cli/cli.ts",
    "db/seed/cli/bootstrap.ts",
    "db/seed/cli/validate-cli.ts",
    "db/seed/cli/validate-bootstrap.ts",
    "db/seed/foundation-catalog/foundation-catalog.ts",
    "db/seed/foundation-principal/foundation-principal.ts",
    "db/seed/permissions/permissions.ts",
    "db/seed/roles/roles.ts",
    "db/seed/role-default-permissions/role-default-permissions.ts",
    "db/seed/service-principals/service-principals.ts",
    "db/seed/service-principal-roles/service-principal-roles.ts",
    "db/setup/cli/cli.ts",
    "db/setup/cli/bootstrap.ts",
    "db/reset/cli/cli.ts",
    "db/reset/cli/bootstrap.ts",
    "lib/config/**/*.ts",
    "lib/analytics/**/*.ts",
    "lib/analytics/**/*.tsx",
    "lib/admin-auth/**/*.ts",
  ];

  function globToRegex(glob) {
    const META = ".+^${}()|[]\\";
    let out = "";
    let i = 0;
    while (i < glob.length) {
      const c = glob[i];
      const next = glob[i + 1];
      const next2 = glob[i + 2];
      if (c === "*" && next === "*" && next2 === "/") {
        out += "(?:.*/)?";
        i += 3;
        continue;
      }
      if (c === "*" && next === "*") {
        out += ".*";
        i += 2;
        continue;
      }
      if (c === "*") {
        out += "[^/]*";
        i += 1;
        continue;
      }
      if (META.includes(c)) {
        out += "\\" + c;
      } else {
        out += c;
      }
      i += 1;
    }
    return new RegExp(`^${out}$`);
  }

  const SETUP_REGEXES = SETUP_GLOBS.map(globToRegex);

  const defaultListAllFiles = (p) => listAllFiles(p);
  const defaultReadFile = (p) => readFileSync(p, "utf8");
  const defaultExistsSync = (p) => existsSync(p);
  const defaultStdoutWrite = (s) => process.stdout.write(s);
  const defaultStderrWrite = (s) => process.stderr.write(s);

  function classify(absolutePath, srcRoot) {
    const rel = relative(srcRoot, absolutePath).split("\\").join("/");
    const parts = rel.split("/");
    const fileName = parts[parts.length - 1];

    if (fileName === "types.ts") {
      return { required: true, reason: "types.ts (interface port)" };
    }

    if (
      /(^|\/)schemas\/[^/]+\/[^/]+\.ts$/.test(rel) ||
      /(^|\/)schemas\/[^/]+\.ts$/.test(rel)
    ) {
      if (rel.includes("/__tests__/") || rel.includes("/__specs__/")) {
        return { required: false, reason: "schemas test/specs artifact" };
      }
      return { required: true, reason: "Drizzle schema (pure DDL)" };
    }

    for (let i = 0; i < SETUP_REGEXES.length; i += 1) {
      if (SETUP_REGEXES[i].test(rel)) {
        return { required: true, reason: `glob ${SETUP_GLOBS[i]}` };
      }
    }

    return { required: false, reason: "" };
  }

  function hasSetupHeader(source) {
    const head = source.split("\n").slice(0, 30).join("\n");
    return /SETUP FILE\./.test(head);
  }

  function isCandidateSourceFile(file) {
    if (!file.endsWith(".ts") && !file.endsWith(".tsx")) return false;
    if (file.endsWith(".d.ts")) return false;
    if (file.endsWith(".test.ts") || file.endsWith(".test.tsx")) return false;
    if (file.includes("/__tests__/") || file.includes("/__specs__/")) return false;
    if (file.endsWith("/index.ts")) return false;
    return true;
  }

  function audit(srcRoot, injected = {}) {
    const listFiles = injected.listFiles ?? defaultListAllFiles;
    const readFile = injected.readFile ?? defaultReadFile;
    const exists = injected.existsSync ?? defaultExistsSync;

    if (!exists(srcRoot)) {
      return { errors: [], checked: 0, srcMissing: true };
    }

    const errors = [];
    let checked = 0;

    for (const file of listFiles(srcRoot)) {
      if (!isCandidateSourceFile(file)) continue;

      const { required, reason } = classify(file, srcRoot);
      const source = readFile(file);
      const has = hasSetupHeader(source);

      if (required) {
        checked += 1;
        if (!has) {
          errors.push(
            `MISSING SETUP header: ${relative(ROOT_DIR, file)} (matched: ${reason})`,
          );
        }
      } else if (has) {
        errors.push(
          `UNEXPECTED SETUP header: ${relative(ROOT_DIR, file)} (file is not covered by any SETUP convention — either remove the marker or add a matching glob to SETUP_GLOBS)`,
        );
      }
    }

    return { errors, checked, srcMissing: false };
  }

  function formatReport(result, srcRoot) {
    if (result.srcMissing) {
      return {
        exitCode: 1,
        stdout: "",
        stderr: `verify-setup-headers: missing ${relative(ROOT_DIR, srcRoot)}\n`,
      };
    }
    if (result.errors.length === 0) {
      return {
        exitCode: 0,
        stdout: `verify-setup-headers: OK (${String(result.checked)} required setup file(s) checked)\n`,
        stderr: "",
      };
    }
    const lines = [
      `verify-setup-headers: ${String(result.errors.length)} issue(s)`,
    ];
    for (const e of result.errors) lines.push(`  ${e}`);
    return { exitCode: 1, stdout: "", stderr: `${lines.join("\n")}\n` };
  }

  function main(io = {}) {
    const src = io.src ?? DEFAULT_SRC;
    const write = io.write ?? defaultStdoutWrite;
    const writeErr = io.writeErr ?? defaultStderrWrite;
    const result = audit(src, {
      listFiles: io.listFiles,
      readFile: io.readFile,
      existsSync: io.existsSync,
    });
    const report = formatReport(result, src);
    if (report.stdout) write(report.stdout);
    if (report.stderr) writeErr(report.stderr);
    return { exitCode: report.exitCode };
  }

  return { main };
})();

// ════════════════════════════════════════════════════════════════════════
// source-coverage — every src/ .ts(x) owned by a spec.yaml owns: list or
// exempt via .ignore.specs.yaml. spec.yaml reads route through load-spec.
// cwd + optional argv source-root, exactly like the original CLI.
// ════════════════════════════════════════════════════════════════════════

/** Dep-free field grab for the .ignore.specs.yaml marker (NOT a load-spec artifact). */
function grabField(contents, key) {
  const lines = contents
    .split("\n")
    .map((l) => l.replace(/\s*#.*$/, ""))
    .filter((l) => l.trim().length > 0);
  for (const line of lines) {
    const m = line.match(new RegExp(`^\\s*${key}\\s*:\\s*(.*)$`));
    if (m && m[1].trim() !== "") {
      return m[1].trim().replace(/^["']|["']$/g, "");
    }
  }
  return undefined;
}

/** Normalize a spec's owns: field (loadSpec/yaml.parse gives an array). */
function ownsList(v) {
  return Array.isArray(v) ? v.map(String) : [];
}

async function runSourceCoverage(sourceRoot) {
  const SOURCE_ROOT = sourceRoot || "src";
  const REPO_ROOT = process.cwd();
  const absRoot = join(REPO_ROOT, SOURCE_ROOT);

  const IGNORE_DIRS = new Set([
    "node_modules",
    ".next",
    ".turbo",
    "coverage",
    "test-results",
    "playwright-report",
    ".git",
    "dist",
    "build",
    "out",
  ]);

  const SOURCE_EXTS = [".ts", ".tsx"];

  if (!existsSync(absRoot)) {
    process.stderr.write(
      `\n❌ verify-source-coverage: source root '${SOURCE_ROOT}' not found at ${absRoot}\n`,
    );
    return 2;
  }

  const featuresIndex = new Map();
  const featureDeclarations = new Map();

  /** Presence check: a spec lives here if spec.md (fenced) or legacy spec.yaml exists. */
  function specPresent(specDir) {
    return existsSync(join(specDir, "spec.md")) || existsSync(join(specDir, "spec.yaml"));
  }

  async function collectFeatures(dir) {
    let entries;
    try {
      entries = await readdir(dir, { withFileTypes: true });
    } catch {
      return;
    }
    const specsDir = entries.find((e) => e.isDirectory() && e.name === "__specs__");
    if (specsDir) {
      const sd = join(dir, "__specs__");
      if (specPresent(sd)) {
        const res = loadSpec(sd);
        const value = res.ok && res.value ? res.value : {};
        const name = value.feature_name;
        const owns = ownsList(value.owns);
        if (name) {
          const specRel = relative(REPO_ROOT, res.path ?? join(sd, "spec.yaml"));
          featuresIndex.set(name, {
            specPath: specRel,
            owns: new Set(owns),
          });
          const declared = featureDeclarations.get(name) ?? [];
          declared.push(specRel);
          featureDeclarations.set(name, declared);
        }
      }
    }
    for (const e of entries) {
      if (!e.isDirectory()) continue;
      if (IGNORE_DIRS.has(e.name)) continue;
      if (e.name === "__specs__" || e.name === "__tests__") continue;
      await collectFeatures(join(dir, e.name));
    }
  }

  await collectFeatures(absRoot);

  const violations = [];
  let covered = 0;
  let exempt = 0;

  for (const [name, paths] of featureDeclarations) {
    if (paths.length > 1) {
      violations.push(
        `DUPLICATE feature_name="${name}" — declared at ${paths.join(" AND ")}. feature_name MUST be unique repo-wide.`,
      );
    }
  }

  async function walkSources(dir) {
    let entries;
    try {
      entries = await readdir(dir, { withFileTypes: true });
    } catch {
      return;
    }
    for (const e of entries) {
      if (e.isDirectory()) {
        if (IGNORE_DIRS.has(e.name)) continue;
        if (e.name === "__tests__") continue;
        await walkSources(join(dir, e.name));
        continue;
      }
      if (!e.isFile()) continue;
      if (!SOURCE_EXTS.some((ext) => e.name.endsWith(ext))) continue;
      if (e.name.endsWith(".test.ts") || e.name.endsWith(".test.tsx")) continue;
      if (e.name === "next-env.d.ts") continue;
      await auditSource(join(dir, e.name));
    }
  }

  async function auditSource(filePath) {
    const rel = relative(REPO_ROOT, filePath);
    let cur = dirname(filePath);
    while (true) {
      const sd = join(cur, "__specs__");
      const ignorePath = join(cur, ".ignore.specs.yaml");

      if (specPresent(sd)) {
        const res = loadSpec(sd);
        const value = res.ok && res.value ? res.value : {};
        const name = value.feature_name;
        const owns = new Set(ownsList(value.owns));
        const specRel = relative(REPO_ROOT, res.path ?? join(sd, "spec.yaml"));
        if (!name) {
          if (value.component) {
            covered++;
            return;
          }
          violations.push(
            `${rel}: parent ${specRel} has no feature_name — cannot resolve ownership.`,
          );
          return;
        }
        if (!owns.has(rel)) {
          violations.push(
            `${rel}: under feature_name="${name}" (spec ${specRel}) but NOT in that spec's owns: list. Add this path to owns: or move the file out of this feature.`,
          );
          return;
        }
        covered++;
        return;
      }

      if (existsSync(ignorePath)) {
        const text = (await readFileAsync(ignorePath, "utf-8")).trim();
        if (text === "" || text.split("\n").every((l) => l.trim() === "" || l.trim().startsWith("#"))) {
          exempt++;
          return;
        }
        const declared = grabField(text, "feature_name");
        if (!declared) {
          violations.push(
            `${rel}: marker ${relative(REPO_ROOT, ignorePath)} has content + no feature_name — invalid marker.`,
          );
          return;
        }
        if (!featuresIndex.has(declared)) {
          violations.push(
            `${rel}: marker ${relative(REPO_ROOT, ignorePath)} names feature_name="${declared}" but no __specs__/spec.yaml declares it.`,
          );
          return;
        }
        const ownerInfo = featuresIndex.get(declared);
        if (!ownerInfo.owns.has(rel)) {
          violations.push(
            `${rel}: marker points at feature_name="${declared}" but that feature's spec (${ownerInfo.specPath}) owns: list does NOT include this file. Add it.`,
          );
          return;
        }
        covered++;
        return;
      }

      if (cur === absRoot) break;
      const parent = dirname(cur);
      if (parent === cur) break;
      cur = parent;
    }
    violations.push(
      `${rel}: NAKED — no __specs__/spec.yaml or .ignore.specs.yaml found in any parent up to ${SOURCE_ROOT}/.`,
    );
  }

  await walkSources(absRoot);

  if (violations.length === 0) {
    process.stdout.write(
      `✅ verify-source-coverage — ${covered} file(s) covered + ${exempt} explicitly exempt; ${featuresIndex.size} feature(s) declared\n`,
    );
    return 0;
  }

  process.stderr.write(
    `\n❌ verify-source-coverage: ${violations.length} violation(s)\n`,
  );
  for (const v of violations) process.stderr.write(`   - ${v}\n`);
  process.stderr.write(
    `\n   ${covered} file(s) covered + ${exempt} exempt; ${featuresIndex.size} feature(s) declared.\n`,
  );
  return 1;
}

// ════════════════════════════════════════════════════════════════════════
// no-padding-folders — refuse README-only padding folders in src/features/.
// cwd + optional argv source-root, exactly like the original CLI.
// ════════════════════════════════════════════════════════════════════════
async function runNoPaddingFolders(sourceRoot) {
  const SOURCE_ROOT = sourceRoot || "src";
  const REPO_ROOT = process.cwd();
  const featuresDir = join(REPO_ROOT, SOURCE_ROOT, "features");

  const IGNORE_DIRS = new Set([
    "node_modules",
    ".next",
    ".turbo",
    "coverage",
    "test-results",
    "playwright-report",
    ".git",
    "dist",
    "build",
    "out",
    "__specs__",
  ]);

  if (!existsSync(featuresDir)) {
    process.stdout.write(
      `✅ verify-no-padding-folders — no src/features/ in this repo; nothing to check.\n`,
    );
    return 0;
  }

  const violations = [];
  let checked = 0;

  async function countTsFiles(dir) {
    let count = 0;
    async function scan(d) {
      let entries;
      try {
        entries = await readdir(d, { withFileTypes: true });
      } catch {
        return;
      }
      for (const e of entries) {
        if (IGNORE_DIRS.has(e.name)) continue;
        const p = join(d, e.name);
        if (e.isDirectory()) {
          await scan(p);
        } else if (e.isFile()) {
          if (e.name.endsWith(".ts") || e.name.endsWith(".tsx")) count++;
        }
      }
    }
    await scan(dir);
    return count;
  }

  async function scanFeature(featDir) {
    let subs;
    try {
      subs = await readdir(featDir, { withFileTypes: true });
    } catch {
      return;
    }
    for (const sub of subs) {
      if (!sub.isDirectory()) continue;
      if (IGNORE_DIRS.has(sub.name)) continue;
      const subPath = join(featDir, sub.name);
      const tsCount = await countTsFiles(subPath);
      checked++;
      if (tsCount === 0) {
        violations.push(
          `${relative(REPO_ROOT, subPath)}: EMPTY PADDING — 0 .ts/.tsx files. Delete the folder or add real code.`,
        );
      }
    }
  }

  const featureEntries = await readdir(featuresDir, { withFileTypes: true });
  for (const feat of featureEntries) {
    if (!feat.isDirectory()) continue;
    if (IGNORE_DIRS.has(feat.name)) continue;
    if (feat.name === "shared") continue;
    await scanFeature(join(featuresDir, feat.name));
  }

  if (violations.length === 0) {
    process.stdout.write(
      `✅ verify-no-padding-folders — ${checked} sub-folder(s) checked; every one has real code.\n`,
    );
    return 0;
  }

  process.stderr.write(
    `\n❌ verify-no-padding-folders: ${violations.length} violation(s)\n`,
  );
  for (const v of violations) process.stderr.write(`   - ${v}\n`);
  process.stderr.write(
    `\n   ${checked} sub-folder(s) checked total.\n`,
  );
  return 1;
}

// ════════════════════════════════════════════════════════════════════════
// Per-gate entry points (exported for the selftests that inject roots).
// ════════════════════════════════════════════════════════════════════════
export const mainDocs = docsGate.main;
export const mainFlowCoverage = flowCoverageGate.main;
export const mainManualPlaybooks = manualPlaybooksGate.main;
export const mainNoStray = noStrayGate.main;
export const mainSetupHeaders = setupHeadersGate.main;
export { runSourceCoverage, runNoPaddingFolders };

// ════════════════════════════════════════════════════════════════════════
// Dispatcher.
// ════════════════════════════════════════════════════════════════════════
const CHECK_NAMES = [
  "docs",
  "flow-coverage",
  "manual-playbooks",
  "source-coverage",
  "no-padding-folders",
  "no-stray-scaffolding",
  "setup-headers",
];

/**
 * Run one named sub-check. Returns its exit code.
 * @param {string} name
 * @returns {Promise<number>}
 */
export async function runCheck(name) {
  switch (name) {
    case "docs":
      return mainDocs().exitCode;
    case "flow-coverage":
      return mainFlowCoverage().exitCode;
    case "manual-playbooks":
      return mainManualPlaybooks().exitCode;
    case "source-coverage":
      return runSourceCoverage();
    case "no-padding-folders":
      return runNoPaddingFolders();
    case "no-stray-scaffolding":
      return mainNoStray().exitCode;
    case "setup-headers":
      return mainSetupHeaders().exitCode;
    default:
      process.stderr.write(
        `verify-specs: unknown check "${String(name)}" (valid: ${CHECK_NAMES.join(", ")})\n`,
      );
      return 2;
  }
}

/**
 * Run all 7 sub-checks. Returns 1 iff any failed, else 0.
 * @returns {Promise<number>}
 */
export async function runAll() {
  let failures = 0;
  for (const n of CHECK_NAMES) {
    const code = await runCheck(n);
    if (code !== 0) failures += 1;
  }
  return failures > 0 ? 1 : 0;
}

export function isCliInvocation(importMetaUrl, argv1) {
  if (argv1 === undefined || argv1 === "") return false;
  return importMetaUrl === pathToFileURL(argv1).href;
}

async function cliMain() {
  const idx = process.argv.indexOf("--check");
  if (idx !== -1) {
    return runCheck(process.argv[idx + 1]);
  }
  return runAll();
}

if (isCliInvocation(import.meta.url, process.argv[1])) {
  process.exit(await cliMain());
}
