import type { Meta, StoryObj } from '@storybook/react';
import { useState, type CSSProperties } from 'react';
import { Handle, Position, type NodeProps } from '@xyflow/react';
import { FlowChart } from './react/FlowChart';
import { elkEngine } from './layout/elkEngine';
import type { iFlowGraph } from './ir/types';
import type { iFlowNodeData } from './react/types';

const meta: Meta<typeof FlowChart> = {
  title: 'FlowChart/FlowChart',
  component: FlowChart,
  parameters: {
    layout: 'fullscreen',
    docs: {
      description: {
        component:
          'Author a diagram as Mermaid-like `chart` text or as a `graph` object; it renders on ' +
          'React Flow with auto-layout, rich interactive nodes, and semantic path detection. ' +
          'Every story below is live — edit the `chart` in the Controls panel to see it re-render.',
      },
    },
  },
  argTypes: {
    pathDrawerPosition: { control: 'select', options: ['top', 'bottom', 'left', 'right'] },
    direction: { control: 'select', options: ['TD', 'BT', 'LR', 'RL'] },
  },
};
export default meta;

type Story = StoryObj<typeof FlowChart>;
const doc = (story: string) => ({ parameters: { docs: { description: { story } } } });

/* ─────────────────────────  AUTHORING  ───────────────────────── */

const CHECKOUT = `flowchart TD
  start([Order placed]) --> cart[Review cart]
  cart --> pay{Payment OK?}
  pay -->|yes| ship[Ship order]
  pay ==>|no| fail[Payment failed]:::error
  pay -.->|manual review| hold[Hold for review]:::warning
  ship --> done([Delivered])
  fail --> done
  hold --> ship`;

/**
 * The primary way to use the package: write a Mermaid-like text string. `[]` is an action,
 * `{}` a decision, `([])` a start/end (resolved by position). `-->` is a normal edge,
 * `==>` an error edge (thick red), `-.->` a warning edge (dotted amber), and `|label|`
 * labels it. `:::type` sets an explicit node/edge type. Node positions are computed for you.
 */
export const AuthorWithText: Story = {
  args: { chart: CHECKOUT, height: 560 },
  ...doc(
    'The headline feature — diagram-as-code. Try changing the text in the Controls panel; ' +
      'the chart re-lays-out automatically. Note the red error path and dotted warning path.'
  ),
};

const SIGNUP: iFlowGraph = {
  id: 'signup',
  name: 'Signup',
  direction: 'TD',
  nodes: [
    { id: 's', label: 'Visitor', type: 'start' },
    { id: 'form', label: 'Fill form', type: 'action', description: 'Email + password + name' },
    { id: 'v', label: 'Valid?', type: 'decision' },
    { id: 'ok', label: 'Create account', type: 'action' },
    { id: 'err', label: 'Show errors', type: 'error' },
    { id: 'e', label: 'Dashboard', type: 'end' },
  ],
  edges: [
    { id: 'e0', from: 's', to: 'form', type: 'default' },
    { id: 'e1', from: 'form', to: 'v', type: 'default' },
    { id: 'e2', from: 'v', to: 'ok', type: 'happy', label: 'yes' },
    { id: 'e3', from: 'v', to: 'err', type: 'error', label: 'no' },
    { id: 'e4', from: 'ok', to: 'e', type: 'happy' },
    { id: 'e5', from: 'err', to: 'form', type: 'warning' },
  ],
};

/**
 * When you already have structured data (from a DB, an API, or generated by code/an LLM), pass
 * the `graph` object instead of text. It is the exact same shape the parser produces — the
 * `iFlowGraph` IR — and it supports a per-node `description` (shown via the node's expand toggle).
 */
export const AuthorWithObject: Story = {
  args: { graph: SIGNUP, height: 560, showMiniMap: true },
  ...doc(
    'Same renderer, object input. Click the “+” on the “Fill form” node to reveal its ' +
      'description. The minimap (bottom-right) is enabled here via `showMiniMap`.'
  ),
};

/* ─────────────────────────  LAYOUT / DIRECTION  ───────────────────────── */

const PIPELINE = `flowchart LR
  a([Commit]) --> b[Install deps]
  b --> c[Lint]
  c --> d[Unit tests]
  d --> e{All green?}
  e -->|yes| f[Build]
  e ==>|no| x[Fail the run]:::error
  f --> g([Deploy])`;

/**
 * The header direction controls layout: `TD` (top-down, default), `LR` (left-right),
 * `BT` (bottom-top), `RL` (right-left). You can also override it with the `direction` prop.
 * Pipelines and timelines usually read best left-to-right.
 */
export const DirectionLeftToRight: Story = {
  args: { chart: PIPELINE, height: 360 },
  ...doc('A CI pipeline laid out left-to-right (`flowchart LR`).'),
};

/**
 * The same diagram, re-oriented purely by the `direction` prop — no change to the chart text.
 * Handles (the little connection dots) re-orient automatically so edges always enter/leave the
 * correct side.
 */
export const DirectionBottomToTop: Story = {
  args: { chart: PIPELINE, direction: 'BT', height: 480 },
  ...doc('`direction="BT"` overrides the header and flows the pipeline upward.'),
};

/* ─────────────────────────  ENGINES  ───────────────────────── */

/**
 * Layout is pluggable. `dagre` is the default (fast, synchronous, great for most flowcharts).
 * For large or dense graphs, opt into **ELK** by passing `layoutEngine={elkEngine}` — it does
 * layered layout with cleaner edge routing. ELK needs the optional peer dep `elkjs`.
 */
export const ElkLayoutEngine: Story = {
  args: { chart: CHECKOUT, layoutEngine: elkEngine, height: 560 },
  ...doc('Same diagram, laid out by ELK instead of dagre. Compare the edge routing.'),
};

/* ─────────────────────────  NODE & EDGE VOCABULARY  ───────────────────────── */

const ALL_TYPES = `flowchart TD
  s([start]) --> a[action]
  a --> d{decision}
  d -->|happy edge| ok[action]
  d -.->|warning edge| w[warning]:::warning
  d ==>|error edge| e[error]:::error
  ok --> lnk[link]:::link
  w --> fin([end])
  e --> fin
  lnk --> fin`;

/**
 * Every node type and every edge type in one diagram. Node types set the shape + border color
 * (`start`/`end` pill, `decision` cut corners, `error`/`warning`/`link` status colors). Edge
 * types set the line style and feed path detection: `happy`=green, `warning`=dotted amber,
 * `error`=thick red, `default`=grey.
 */
export const NodeAndEdgeTypes: Story = {
  args: { chart: ALL_TYPES, height: 520 },
  ...doc('A cheat-sheet diagram showing all 7 node types and all 4 edge types.'),
};

/* ─────────────────────────  PATH DETECTION  ───────────────────────── */

/**
 * The package automatically enumerates every route from a start node to an end node and
 * classifies each as happy / warning / error / neutral. The **path drawer** on the right lists
 * them; click one to highlight only that route and dim everything else. This is the feature
 * plain Mermaid and plain React Flow don't give you.
 */
export const PathDetection: Story = {
  args: { chart: CHECKOUT, height: 560, pathDrawerPosition: 'right' },
  ...doc(
    'Click a path in the drawer to highlight it. The happy path (place → pay → ship → deliver) ' +
      'and the error path (pay → failed) are detected and colored automatically.'
  ),
};

/**
 * Path selection can be **controlled** from your own UI. Pass `selectedPathId` + `onPathChange`
 * and drive it however you like — here from a plain button row above the chart.
 */
export const ControlledPathSelection: Story = {
  render: (args) => {
    const [sel, setSel] = useState<string | null>(null);
    return (
      <div>
        <div style={{ display: 'flex', gap: 8, padding: '10px 12px', fontFamily: 'system-ui' }}>
          {['path-1', 'path-2', 'path-3'].map((p) => (
            <button key={p} onClick={() => setSel(p)} style={{ padding: '4px 10px', cursor: 'pointer' }}>
              Highlight {p}
            </button>
          ))}
          <button onClick={() => setSel(null)} style={{ padding: '4px 10px', cursor: 'pointer' }}>
            Clear
          </button>
          <span style={{ marginLeft: 'auto', color: '#71717a' }}>selected: {sel ?? 'none'}</span>
        </div>
        <FlowChart {...args} selectedPathId={sel} onPathChange={setSel} />
      </div>
    );
  },
  args: { chart: CHECKOUT, height: 500, showPathDrawer: false },
  ...doc('External buttons drive `selectedPathId`; the drawer is hidden to prove it is optional.'),
};

/* ─────────────────────────  INTERACTIVITY  ───────────────────────── */

/**
 * `onNodeClick(id, data)` fires for every node; `activeNodeId` visually highlights one (a blue
 * ring). Together they make a guided walkthrough: click a node to make it active.
 */
export const ClickAndActiveNode: Story = {
  render: (args) => {
    const [active, setActive] = useState<string | undefined>('cart');
    return <FlowChart {...args} activeNodeId={active} onNodeClick={(id) => setActive(id)} />;
  },
  args: { chart: CHECKOUT, height: 520 },
  ...doc('Click any node — it becomes the active node (blue ring). Great for “you are here” tours.'),
};

/* ─────────────────────────  CUSTOMIZATION  ───────────────────────── */

/** A fully custom node component the consumer supplies via the `nodeTypes` registry. */
function KpiNode({ data }: NodeProps): JSX.Element {
  const d = data as iFlowNodeData & { metric?: string };
  return (
    <div
      style={{
        border: '2px solid #6366f1',
        borderRadius: 12,
        padding: '10px 14px',
        background: 'linear-gradient(180deg,#eef2ff,#fff)',
        fontFamily: 'system-ui',
        minWidth: 140,
        textAlign: 'center',
      }}
    >
      <Handle type="target" position={Position.Top} />
      <div style={{ fontSize: 12, color: '#6366f1', fontWeight: 700 }}>{d.label}</div>
      {d.metric && <div style={{ fontSize: 22, fontWeight: 800 }}>{d.metric}</div>}
      <Handle type="source" position={Position.Bottom} />
    </div>
  );
}

const KPI_GRAPH: iFlowGraph = {
  id: 'kpi',
  name: 'KPIs',
  direction: 'LR',
  nodes: [
    { id: 'v', label: 'Visits', type: 'action', data: { metric: '12.4k' } },
    { id: 's', label: 'Signups', type: 'action', data: { metric: '1.1k' } },
    { id: 'p', label: 'Paid', type: 'action', data: { metric: '218' } },
  ],
  edges: [
    { id: 'e0', from: 'v', to: 's', type: 'happy' },
    { id: 'e1', from: 's', to: 'p', type: 'happy' },
  ],
};

/**
 * Replace the rendering of any node type with your own React component via the `nodeTypes`
 * registry. The `data.data` payload you put on a node flows straight through to your component.
 * Here every `action` node is rendered as a custom KPI card — your component, our layout + edges.
 */
export const CustomNodeComponents: Story = {
  args: { graph: KPI_GRAPH, height: 320, nodeTypes: { action: KpiNode }, showPathDrawer: false },
  ...doc('The `action` type is overridden with a bespoke KPI card component via `nodeTypes`.'),
};

/**
 * All colors are CSS custom properties (`--fc-node-*`, `--fc-edge-*`), so theming is pure CSS —
 * no props, no JS. Wrap the chart in any element that sets the variables (here a dark theme).
 */
export const ThemingWithTokens: Story = {
  render: (args) => (
    <div
      style={
        {
          '--fc-node-bg': '#1e1b2e',
          '--fc-node-text': '#e9e7f5',
          '--fc-node-action': '#8b5cf6',
          '--fc-node-start': '#22d3ee',
          '--fc-node-end': '#34d399',
          '--fc-node-decision': '#fbbf24',
          '--fc-drawer-bg': '#17141f',
          '--fc-drawer-text': '#e9e7f5',
          '--fc-drawer-border': '#3b3550',
          background: '#0f0d17',
          padding: 12,
        } as CSSProperties
      }
    >
      <FlowChart {...args} />
    </div>
  ),
  args: { chart: CHECKOUT, height: 520 },
  ...doc('A dark theme applied by overriding the `--fc-*` CSS variables on a wrapper — zero JS.'),
};

/* ─────────────────────────  DRAWER PLACEMENT  ───────────────────────── */

/**
 * The path drawer can sit on any side. Use `top`/`bottom` for wide, short diagrams and
 * `left`/`right` for tall ones.
 */
export const DrawerOnBottom: Story = {
  args: { chart: PIPELINE, pathDrawerPosition: 'bottom', height: 420 },
  ...doc('`pathDrawerPosition="bottom"` — good for left-to-right pipelines.'),
};

/* ─────────────────────────  REAL-WORLD EXAMPLES  ───────────────────────── */

/**
 * A user-authentication flow — email/password + social, with verification and error branches.
 * This is the kind of decision-heavy diagram the semantic path model shines on.
 */
export const RealWorldAuthFlow: Story = {
  args: {
    height: 620,
    chart: `flowchart TD
  a([Visit login]) --> m{Method?}
  m -->|email| cred[Enter credentials]
  m -->|social| oauth[Redirect to provider]
  cred --> ok{Valid?}
  ok ==>|no| err[Show error]:::error
  err --> cred
  ok -->|yes| ver{Email verified?}
  oauth --> back[Provider callback]
  back --> ver
  ver -.->|no| send[Send verify email]:::warning
  send --> wait([Awaiting verification])
  ver -->|yes| sess[Create session]
  sess --> dash([Dashboard])`,
  },
  ...doc('A production-shaped auth flow with email + social paths, verification, and error loops.'),
};

/**
 * An incident-response runbook. Warning (dotted) and error (thick) edges make the severity of
 * each branch legible at a glance, and the path drawer lets responders isolate one route.
 */
export const RealWorldIncidentRunbook: Story = {
  args: {
    height: 600,
    chart: `flowchart TD
  a([Alert fires]) --> t{Triage severity}
  t ==>|SEV1| page[Page on-call]:::error
  t -.->|SEV2| ticket[Open ticket]:::warning
  t -->|SEV3| log[Log for later]
  page --> mit[Mitigate]
  mit --> ok{Resolved?}
  ok ==>|no| esc[Escalate]:::error
  esc --> mit
  ok -->|yes| pm[Write post-mortem]
  ticket --> pm
  log --> pm
  pm --> done([Close incident])`,
  },
  ...doc('An on-call runbook. Severity reads directly from edge style (thick=SEV1, dotted=SEV2).'),
};

/* ─────────────────────────  ERROR HANDLING  ───────────────────────── */

/**
 * Malformed diagram text never crashes your app — the component renders an inline, styled error
 * box with the exact line and reason. (Headless, `parseFlowchart` throws a typed
 * `FlowchartParseError { line, column, reason }` you can catch.)
 */
export const ParseErrorHandling: Story = {
  args: { chart: 'this is missing a header --> nowhere', height: 220, showPathDrawer: false },
  ...doc('A chart with no `flowchart <DIR>` header → a friendly error box instead of a crash.'),
};
