// Blast-radius helper. For a given slice path, returns the set of files

// ────────────────────────────────────────────────────────────────
// DO NOT EDIT THIS FILE.
//
// COPY of source-of-truth at
//   ~/.claude/standards/scripts/lib/blast-radius.mjs
//
// Local edits will be overwritten the next time
//   bash ~/.claude/standards/scripts/install-slice-gates.sh
// runs. Edit the ORIGINAL and re-install.
// ────────────────────────────────────────────────────────────────
// that the slice's changes "affect" — the direct callers, direct callees,
// tests that exercise any of those files, and __specs__/spec.yaml entries
// that reference them.
//
// Pure Node + grep. No TS-compiler invocation; an import-statement scan
// is good enough for the slice-on-commit verifier's targeting need.

import { execFileSync } from "node:child_process";
import { readFileSync, readdirSync, statSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";

/**
 * Recursively walk `root` returning every .ts / .tsx file (no node_modules,
 * no .next).
 *
 * @param {string} root absolute path
 * @returns {string[]} absolute file paths
 */
export function listSourceFiles(root) {
  /** @type {string[]} */
  const out = [];
  const skip = new Set(["node_modules", ".next", ".git", "dist", "build"]);
  /** @param {string} dir */
  function walk(dir) {
    let entries;
    try {
      entries = readdirSync(dir);
    } catch {
      return;
    }
    for (const e of entries) {
      if (skip.has(e)) continue;
      const full = join(dir, e);
      let st;
      try {
        st = statSync(full);
      } catch {
        continue;
      }
      if (st.isDirectory()) {
        walk(full);
      } else if (/\.tsx?$/.test(e)) {
        out.push(full);
      }
    }
  }
  walk(root);
  return out;
}

/**
 * Return only the `.ts`/`.tsx` source files inside `sliceAbs` that are
 * NOT under `__tests__/` or `__specs__/`. These are the slice's
 * "primary" source files.
 *
 * @param {string} sliceAbs
 * @returns {string[]} absolute paths
 */
export function listSliceSourceFiles(sliceAbs) {
  return listSourceFiles(sliceAbs).filter(
    (p) => !p.includes("/__tests__/") && !p.includes("/__specs__/"),
  );
}

/**
 * Return the slice's own test files (`__tests__/*.test.ts`).
 *
 * @param {string} sliceAbs
 * @returns {string[]}
 */
export function listSliceTestFiles(sliceAbs) {
  return listSourceFiles(sliceAbs).filter((p) => /\/__tests__\/.+\.test\.tsx?$/.test(p));
}

/**
 * Parse an import statement from a source file's contents. Returns the
 * raw module specifiers used in `import ... from "<spec>"` and
 * `import("<spec>")` calls.
 *
 * @param {string} contents
 * @returns {string[]}
 */
export function extractImportSpecs(contents) {
  /** @type {string[]} */
  const out = [];
  const re = /(?:^|\n)\s*import\s+(?:[^"'\n]*?\s+from\s+)?["']([^"']+)["']/g;
  let m;
  while ((m = re.exec(contents)) !== null) {
    out.push(m[1]);
  }
  const dyn = /import\(\s*["']([^"']+)["']\s*\)/g;
  while ((m = dyn.exec(contents)) !== null) {
    out.push(m[1]);
  }
  return out;
}

/**
 * Resolve an import specifier from a source file to an absolute path.
 * Returns null when the specifier is a non-relative non-aliased package
 * (e.g., `next`, `react`), the path doesn't resolve to a .ts/.tsx file,
 * or any other reason.
 *
 * Supports the project's two import shapes:
 *   - relative ("./foo", "../foo/bar")
 *   - "@/..." alias rooted at `<repoRoot>/src/`
 *
 * @param {string} importer absolute path of the file doing the import
 * @param {string} spec the import specifier
 * @param {string} repoRoot absolute path to the project root (code/web)
 * @returns {string | null}
 */
export function resolveImport(importer, spec, repoRoot) {
  /** @type {string | null} */
  let candidate = null;
  if (spec.startsWith(".")) {
    candidate = resolve(dirname(importer), spec);
  } else if (spec.startsWith("@/")) {
    candidate = resolve(repoRoot, "src", spec.slice(2));
  } else {
    return null;
  }
  // Try variants: <c>.ts, <c>.tsx, <c>/index.ts, <c>/index.tsx
  for (const ext of [".ts", ".tsx", "/index.ts", "/index.tsx"]) {
    const p = candidate + ext;
    try {
      const st = statSync(p);
      if (st.isFile()) return p;
    } catch {
      /* try next */
    }
  }
  // Also try the candidate as-is in case the spec already includes .ts/.tsx
  try {
    const st = statSync(candidate);
    if (st.isFile()) return candidate;
  } catch {
    /* nothing */
  }
  return null;
}

/**
 * Direct callees of a single source file: every locally-resolved import
 * target (relative or "@/...") that points to an existing .ts/.tsx file
 * inside the repo.
 *
 * @param {string} fileAbs
 * @param {string} repoRoot
 * @param {{ readFile?: (p: string) => string }} [io]
 * @returns {string[]}
 */
export function directCallees(fileAbs, repoRoot, io = {}) {
  const readFile = io.readFile ?? ((p) => readFileSync(p, "utf8"));
  /** @type {string[]} */
  let contents;
  try {
    contents = [readFile(fileAbs)];
  } catch {
    return [];
  }
  /** @type {Set<string>} */
  const out = new Set();
  for (const c of contents) {
    for (const spec of extractImportSpecs(c)) {
      const r = resolveImport(fileAbs, spec, repoRoot);
      if (r !== null) out.add(r);
    }
  }
  return [...out];
}

/**
 * Direct callers of the slice's source files: any .ts/.tsx file in
 * `repoSrc` whose import statements resolve back to a file inside the
 * slice.
 *
 * Uses grep over the slice's relative path as a coarse first-pass
 * filter, then verifies with the resolver. Files inside the slice itself
 * are NOT considered callers (they're already in scope).
 *
 * @param {string} sliceAbs
 * @param {string} repoRoot
 * @param {{ spawn?: typeof execFileSync, readFile?: (p: string) => string }} [io]
 * @returns {string[]}
 */
export function findCallers(sliceAbs, repoRoot, io = {}) {
  const spawn = io.spawn ?? execFileSync;
  const readFile = io.readFile ?? ((p) => readFileSync(p, "utf8"));
  const srcRoot = resolve(repoRoot, "src");
  const sliceRel = relative(srcRoot, sliceAbs);
  // Coarse grep: any file under src/ that mentions either the slice's
  // relative path OR the slice's basename in an import-like context.
  const patterns = [];
  if (sliceRel && !sliceRel.startsWith("..")) {
    patterns.push(`from\\s+["'][^"']*${sliceRel.replace(/[.[\]/]/g, "\\$&")}`);
  }
  /** @type {Set<string>} */
  const candidates = new Set();
  for (const pat of patterns) {
    try {
      const out = spawn(
        "grep",
        ["-rlE", "--include=*.ts", "--include=*.tsx", pat, srcRoot],
        { encoding: "utf8" },
      );
      for (const line of String(out).split("\n")) {
        const trimmed = line.trim();
        if (trimmed.length === 0) continue;
        if (trimmed.startsWith(sliceAbs)) continue;
        candidates.add(trimmed);
      }
    } catch {
      // grep returns non-zero when no matches — that's fine
    }
  }
  // Verify each candidate by re-resolving its imports
  /** @type {string[]} */
  const confirmed = [];
  for (const cand of candidates) {
    /** @type {string} */
    let contents;
    try {
      contents = readFile(cand);
    } catch {
      continue;
    }
    for (const spec of extractImportSpecs(contents)) {
      const resolved = resolveImport(cand, spec, repoRoot);
      if (resolved !== null && resolved.startsWith(sliceAbs)) {
        confirmed.push(cand);
        break;
      }
    }
  }
  return confirmed.sort();
}

/**
 * Compute the blast radius for a slice. Returns five disjoint sets of
 * absolute paths:
 *   - sliceSources: .ts/.tsx in slice (excluding __tests__ / __specs__)
 *   - sliceTests:   __tests__/*.test.ts in slice
 *   - callers:      .ts/.tsx outside the slice that import from inside it
 *   - callees:      .ts/.tsx inside the repo imported by sliceSources
 *   - callerTests:  __tests__/*.test.ts that import the slice OR a caller
 *
 * @param {string} sliceAbs
 * @param {string} repoRoot
 * @param {{ spawn?: typeof execFileSync, readFile?: (p: string) => string }} [io]
 * @returns {{
 *   sliceSources: string[],
 *   sliceTests: string[],
 *   callers: string[],
 *   callees: string[],
 *   callerTests: string[],
 * }}
 */
export function blastRadius(sliceAbs, repoRoot, io = {}) {
  const sliceSources = listSliceSourceFiles(sliceAbs);
  const sliceTests = listSliceTestFiles(sliceAbs);
  const callers = findCallers(sliceAbs, repoRoot, io);
  /** @type {Set<string>} */
  const callees = new Set();
  for (const s of sliceSources) {
    for (const c of directCallees(s, repoRoot, io)) {
      if (!c.startsWith(sliceAbs)) callees.add(c);
    }
  }
  // Tests that import a caller (excluding the slice's own tests)
  /** @type {string[]} */
  const callerTests = [];
  for (const caller of callers) {
    if (/\/__tests__\/.+\.test\.tsx?$/.test(caller)) callerTests.push(caller);
  }
  return {
    sliceSources,
    sliceTests,
    callers: callers.filter((p) => !/\/__tests__\//.test(p)),
    callees: [...callees].sort(),
    callerTests: callerTests.sort(),
  };
}
