// Git-diff helper for the scope-aware `pnpm verify --scope`

// ────────────────────────────────────────────────────────────────
// DO NOT EDIT THIS FILE.
//
// COPY of source-of-truth at
//   ~/.claude/standards/scripts/lib/changed-paths.mjs
//
// Local edits will be overwritten the next time
//   bash ~/.claude/standards/scripts/install-slice-gates.sh
// runs. Edit the ORIGINAL and re-install.
// ────────────────────────────────────────────────────────────────
// orchestrator. Pure Node + zero external dependencies. The helper shells
// out to `git diff --name-only --diff-filter=ACMRT <baseRef> -- <cwd>` and
// returns absolute paths.
//
// Failure-tolerant by design: when git is missing, the base ref is
// unknown, the repo is detached, or any other error fires, the helper
// returns an empty list rather than throwing. The caller (the verify
// orchestrator) treats an empty list as "scope mode unavailable" and
// degrades to a full run with a one-line note.

import { spawnSync } from "node:child_process";
import { resolve } from "node:path";

/**
 * Default IO port for `spawnSync`. Broken out so the test suite can
 * inject a stub without touching `node:child_process` directly.
 *
 * @param {string} command
 * @param {ReadonlyArray<string>} args
 * @param {{ cwd?: string, encoding?: BufferEncoding }} [options]
 * @returns {{ status: number | null, stdout: string, stderr: string, error?: Error }}
 */
export function defaultSpawnSync(command, args, options = {}) {
  const res = spawnSync(command, args, {
    cwd: options.cwd,
    encoding: options.encoding ?? "utf8",
  });
  return {
    status: res.status,
    stdout: typeof res.stdout === "string" ? res.stdout : "",
    stderr: typeof res.stderr === "string" ? res.stderr : "",
    error: res.error,
  };
}

/**
 * Returns the list of absolute paths that differ between `baseRef` and
 * the working tree (added / copied / modified / renamed / type-changed
 * files relative to `cwd`), PLUS any untracked files that `git status`
 * reports under `cwd`. Untracked files are part of the working tree's
 * "changed" set from a verify-orchestrator perspective even though
 * `git diff` itself ignores them.
 *
 * The git invocations are:
 *   git diff --name-only --diff-filter=ACMRT <baseRef> -- <cwd>
 *   git ls-files --others --exclude-standard -- <cwd>
 *
 * Failure modes that return an empty list:
 *   - git binary missing (spawn error)
 *   - non-zero exit on the diff call (unknown ref, detached HEAD, etc.)
 *   - any other I/O failure
 *
 * @param {string} [baseRef]
 * @param {{
 *   cwd?: string,
 *   spawn?: typeof defaultSpawnSync,
 * }} [io]
 * @returns {string[]} absolute paths
 */
export function getChangedPaths(baseRef = "origin/master", io = {}) {
  const cwd = io.cwd ?? process.cwd();
  const spawn = io.spawn ?? defaultSpawnSync;
  const diffRes = spawn("git", [
    "diff",
    "--name-only",
    "--diff-filter=ACMRT",
    baseRef,
    "--",
    cwd,
  ], { cwd, encoding: "utf8" });
  if (diffRes.error) return [];
  if (diffRes.status !== 0) return [];
  const diffPaths = diffRes.stdout.split("\n").map((s) => s.trim()).filter((s) => s.length > 0);

  // Add untracked files (status reports them; ls-files --others is
  // the canonical machine-readable list). A failure here degrades
  // gracefully — we keep the diff list and skip the untracked set.
  /** @type {string[]} */
  let untrackedPaths = [];
  const lsRes = spawn(
    "git",
    ["ls-files", "--others", "--exclude-standard", "--", cwd],
    { cwd, encoding: "utf8" },
  );
  if (!lsRes.error && lsRes.status === 0) {
    untrackedPaths = lsRes.stdout
      .split("\n")
      .map((s) => s.trim())
      .filter((s) => s.length > 0);
  }

  // git prints paths relative to the repo root; resolve against the
  // repo root so every path the caller sees is absolute.
  const repoRoot = findRepoRoot(cwd, spawn);
  /** @type {string[]} */
  const out = [];
  for (const rel of [...diffPaths, ...untrackedPaths]) {
    if (repoRoot === null) {
      out.push(resolve(cwd, rel));
    } else {
      out.push(resolve(repoRoot, rel));
    }
  }
  return out;
}

/**
 * Locate the git repo root for `cwd` via `git rev-parse --show-toplevel`.
 * Returns null on any failure (no git, not a repo, etc.).
 *
 * @param {string} cwd
 * @param {typeof defaultSpawnSync} spawn
 * @returns {string | null}
 */
export function findRepoRoot(cwd, spawn) {
  const res = spawn("git", ["rev-parse", "--show-toplevel"], { cwd, encoding: "utf8" });
  if (res.error) return null;
  if (res.status !== 0) return null;
  const out = res.stdout.trim();
  return out.length > 0 ? out : null;
}
