// Resolves "where does the design mockup for <flow>/<state> live?" to the

// ────────────────────────────────────────────────────────────────
// DO NOT EDIT THIS FILE.
//
// COPY of source-of-truth at
//   ~/.claude/standards/scripts/lib/design-source.mjs
//
// Local edits will be overwritten the next time
//   bash ~/.claude/standards/scripts/install-slice-gates.sh
// runs. Edit the ORIGINAL and re-install.
// ────────────────────────────────────────────────────────────────
// PNG bytes on disk.
//
// Design source: the user exports the mockup from a design tool (e.g.,
// Claude Design's "Export as PNG") and drops it at
// `<__specs__-dir>/ui/<flow>.design-<state>.png`. The gate reads it
// directly. No remote fetch, no API integration — the user controls
// when designs land in the repo.
//
// Pure Node + zero external dependencies.

import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";

/**
 * @typedef {object} DesignResolution
 * @property {"png-bytes"|"not-found"} kind
 * @property {Buffer|null} bytes        PNG content when kind=png-bytes; null otherwise
 * @property {string} location          repo-relative path the resolver consulted
 * @property {string|null} reason       human-readable reason when kind != png-bytes
 */

/**
 * Resolves a design PNG for a (flow, state) pair.
 *
 * @param {string} specsDir   path to the feature's __specs__ directory
 * @param {string} flow       flow base-name (matches flows/<flow>.flow.yaml)
 * @param {string} state      state name (matches manual.yaml's states key)
 * @returns {DesignResolution}
 */
export function resolveDesign(specsDir, flow, state) {
  const fileName = `${flow}.design-${state}.png`;
  const absPath = join(specsDir, "ui", fileName);
  if (!existsSync(absPath)) {
    return {
      kind: "not-found",
      bytes: null,
      location: absPath,
      reason: `expected design PNG at ${absPath} — export from your design tool as PNG, drop here with the matching <flow>.design-<state>.png filename`,
    };
  }
  return {
    kind: "png-bytes",
    bytes: readFileSync(absPath),
    location: absPath,
    reason: null,
  };
}
