// Extract exported "behavior" symbols (top-level functions + public

// ────────────────────────────────────────────────────────────────
// DO NOT EDIT THIS FILE.
//
// COPY of source-of-truth at
//   ~/.claude/standards/scripts/lib/exports.mjs
//
// Local edits will be overwritten the next time
//   bash ~/.claude/standards/scripts/install-slice-gates.sh
// runs. Edit the ORIGINAL and re-install.
// ────────────────────────────────────────────────────────────────
// class methods) from a TypeScript source file using regex parsing.
// Per-class brace-depth tracking; the method-line filter skips
// JavaScript keywords so flow-yaml-schema and source-coverage gates
// see only real exported behavior.
//
// Regex-based extraction. Known limitation: may miss exports using rare
// TS syntax (e.g. `export { x as y } from './z'`, `export default
// function foo` without a name, decorators on class methods, complex
// generics that span lines). Add a real parser (@typescript-eslint/parser)
// only when the regex actually breaks — the install-size trade-off is
// not worth it today.

import { readFileSync } from "node:fs";

/**
 * @typedef {object} ExportedBehavior
 * @property {string} name      identifier as it appears in source
 * @property {"function"|"method"} kind
 * @property {string} className name of the enclosing class (empty when kind=function)
 */

const JS_RESERVED_AT_LINE_START = new Set([
  "if", "else", "for", "while", "do", "switch", "case", "default",
  "return", "throw", "try", "catch", "finally", "break", "continue",
  "async", "await", "new", "typeof", "instanceof", "in", "of", "as",
  "function", "class", "const", "let", "var", "this", "super", "import",
  "export", "from", "yield", "void", "delete", "with",
]);

/**
 * Reads `filePath` and returns every exported "behavior" symbol.
 *
 * @param {string} filePath absolute path
 * @returns {ExportedBehavior[]}
 */
export function listExportedBehaviors(filePath) {
  const src = readFileSync(filePath, "utf8");
  return listExportedBehaviorsFromSource(src);
}

/**
 * Same as `listExportedBehaviors` but accepts the source string directly
 * (testing convenience).
 *
 * @param {string} src
 * @returns {ExportedBehavior[]}
 */
export function listExportedBehaviorsFromSource(src) {
  /** @type {ExportedBehavior[]} */
  const out = [];

  // 1) Exported standalone functions.
  for (const m of src.matchAll(
    /^export\s+(?:async\s+)?function\s+([A-Za-z_$][\w$]*)/gm,
  )) {
    out.push({ name: m[1], kind: "function", className: "" });
  }

  // 2) Exported const arrow / function expressions.
  for (const m of src.matchAll(
    /^export\s+const\s+([A-Za-z_$][\w$]*)\s*(?::[^=]+)?\s*=\s*(?:async\s*)?(?:\(|function\b)/gm,
  )) {
    out.push({ name: m[1], kind: "function", className: "" });
  }

  // 3) Public methods of exported classes.
  const classDeclRe = /^export\s+(?:abstract\s+)?class\s+([A-Za-z_$][\w$]*)/gm;
  for (const classMatch of src.matchAll(classDeclRe)) {
    const className = classMatch[1];
    const bodyStart = src.indexOf("{", classMatch.index);
    if (bodyStart === -1) continue;
    let depth = 1;
    let i = bodyStart + 1;
    while (i < src.length && depth > 0) {
      const ch = src[i];
      if (ch === "{") depth += 1;
      else if (ch === "}") depth -= 1;
      i += 1;
    }
    const bodyEnd = i - 1;
    const body = src.slice(bodyStart + 1, bodyEnd);

    let d = 0;
    let lineStart = 0;
    let lineStartDepth = 0;
    for (let k = 0; k <= body.length; k += 1) {
      const ch = body[k] ?? "\n";
      if (ch === "{") d += 1;
      else if (ch === "}") d -= 1;
      if (ch === "\n" || k === body.length) {
        const line = body.slice(lineStart, k);
        lineStart = k + 1;
        const depthAtLineStart = lineStartDepth;
        lineStartDepth = d;
        if (depthAtLineStart !== 0) continue;
        const trimmed = line.trim();
        if (trimmed.startsWith("//")) continue;
        if (trimmed.startsWith("*")) continue;
        if (trimmed.startsWith("/*")) continue;
        if (trimmed.startsWith("constructor")) continue;
        if (trimmed.startsWith("private ")) continue;
        if (trimmed.startsWith("private\t")) continue;
        if (trimmed.startsWith("protected ")) continue;
        if (trimmed.startsWith("protected\t")) continue;
        const methodMatch = trimmed.match(
          /^(?:public\s+|protected\s+|async\s+|static\s+){0,3}([A-Za-z_$][\w$]*)\s*(?:<[^>]*>)?\s*\(/,
        );
        if (methodMatch) {
          const methodName = methodMatch[1];
          if (JS_RESERVED_AT_LINE_START.has(methodName)) continue;
          out.push({ name: methodName, kind: "method", className });
        }
      }
    }
  }

  return out;
}
