// Kebab-case helper that maps a TypeScript identifier to its

// ────────────────────────────────────────────────────────────────
// DO NOT EDIT THIS FILE.
//
// COPY of source-of-truth at
//   ~/.claude/standards/scripts/lib/kebab.mjs
//
// Local edits will be overwritten the next time
//   bash ~/.claude/standards/scripts/install-slice-gates.sh
// runs. Edit the ORIGINAL and re-install.
// ────────────────────────────────────────────────────────────────
// flow-doc / file basename. ACRONYMS_GLUED extensibility intentionally
// kept simple — extend the list when a new identifier appears that the
// file system uses a glued form for.
//
// Rules observed in the codebases this helper has been exercised against:
//   getDb                          → get-db
//   getAllPermissionKeys           → get-all-permission-keys
//   seedFoundation                 → seed-foundation
//   __resetDbCacheForTests         → reset-db-cache-for-tests  (strip leading underscores)
//   registerOpenAPI                → register-openapi          (acronym `OpenAPI` is one word)
//   buildOpenAPIDocument           → build-openapi-document
//   POST                           → post
//   createSuperAdmin               → create-super-admin
//   assignRoleToUser               → assign-role-to-user
//
// Algorithm (toKebabStrict):
//   1. Strip leading underscores.
//   2. Insert a hyphen at every boundary:
//        a) between [a-z|digit] and [A-Z]
//        b) between an acronym run [A-Z]{2,} and a following [A-Z][a-z]
//   3. Lowercase.
//
// `toKebabCandidates` also yields collapsed-acronym variants (e.g.
// "register-open-api" → "register-openapi") so callers can match either
// shape on disk.

const ACRONYMS_GLUED = ["openapi"];

/**
 * Strict camelCase splitter — every CamelCase boundary becomes a hyphen.
 *
 * @param {string} name
 * @returns {string}
 */
export function toKebabStrict(name) {
  let s = name;
  while (s.startsWith("_")) s = s.slice(1);
  return s
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/([A-Z]+)([A-Z][a-z])/g, "$1-$2")
    .toLowerCase();
}

/**
 * Returns all plausible kebab-case candidates for `name`. The strict form
 * is always first; collapsed-acronym forms follow.
 *
 * @param {string} name
 * @returns {string[]}
 */
export function toKebabCandidates(name) {
  const strict = toKebabStrict(name);
  const out = new Set([strict]);
  for (const glued of ACRONYMS_GLUED) {
    if (glued === "openapi") {
      const collapsed = strict.replace(
        /(^|-)open-api(-|$)/g,
        (_, pre, post) => `${pre}openapi${post}`,
      );
      if (collapsed !== strict) out.add(collapsed);
    }
  }
  return [...out];
}

/**
 * Convenience: pick the (strict) kebab form.
 *
 * @param {string} name
 * @returns {string}
 */
export function toKebab(name) {
  return toKebabStrict(name);
}
