// load-spec.mjs — dual-format loader for the __specs__ artifacts.

// ────────────────────────────────────────────────────────────────
// DO NOT EDIT THIS FILE.
//
// COPY of source-of-truth at
//   ~/.claude/standards/scripts/lib/load-spec.mjs
//
// Local edits will be overwritten the next time
//   bash ~/.claude/standards/scripts/install-slice-gates.sh
// runs. Edit the ORIGINAL and re-install.
// ────────────────────────────────────────────────────────────────
//
// Reads Markdown-with-a-fenced-machine-block (the new agent-facing form) OR the
// legacy .yaml, so the spec YAML→Markdown migration proceeds per-project without
// breaking any gate mid-flight. Every verifier that parses spec/lock/flow data
// routes through here.
//
//   loadSpec(dir)  → dir/spec.md fenced ```yaml block, else dir/spec.yaml       → parsed object
//   loadLock(dir)  → dir/standards-compliance.md fenced block, else .yaml       → flat key/value map
//   loadFlow(base) → base.flow.md fenced block, else base.flow.yaml             → parsed object
//
// Each returns { ok, value, source: 'md'|'yaml'|null, path }.

import fs from "node:fs";
import path from "node:path";
import { createRequire } from "node:module";

/** The consuming project's `yaml` package (verifiers run inside a project). null if absent. */
function projectYaml() {
  try {
    return createRequire(process.cwd() + "/")("yaml");
  } catch {
    return null;
  }
}

/** Extract the first fenced ```yaml (or bare ```) block's body from Markdown; null if none. */
export function extractFencedYaml(md) {
  const m = md.match(/```(?:ya?ml)?[ \t]*\r?\n([\s\S]*?)\r?\n```/);
  return m ? m[1] : null;
}

function stripQuotes(v) {
  if ((v.startsWith('"') && v.endsWith('"')) || (v.startsWith("'") && v.endsWith("'"))) {
    return v.slice(1, -1);
  }
  return v;
}

/**
 * Dep-free flat lock/scalar-map parser (promoted verbatim from
 * verify-standards-compliance). Grammar: `key: value` scalars and `key:` +
 * `  - item` lists. Returns { ok, value } | { ok:false, error }.
 */
export function parseLockFile(contents) {
  if (typeof contents !== "string") return { ok: false, error: "contents must be a string" };
  const out = {};
  const lines = contents.split(/\r?\n/);
  let activeListKey = null;
  for (let i = 0; i < lines.length; i += 1) {
    const trimmed = lines[i].trim();
    if (trimmed === "") { activeListKey = null; continue; }
    if (trimmed.startsWith("#")) continue;
    if (trimmed.startsWith("- ") || trimmed === "-") {
      if (activeListKey === null) return { ok: false, error: `line ${i + 1}: list-item with no preceding 'key:' line` };
      const item = trimmed.startsWith("- ") ? stripQuotes(trimmed.slice(2).trim()) : "";
      out[activeListKey].push(item);
      continue;
    }
    activeListKey = null;
    const colon = trimmed.indexOf(":");
    if (colon === -1) return { ok: false, error: `line ${i + 1}: expected '<key>: <value>'` };
    const key = trimmed.slice(0, colon).trim();
    let value = trimmed.slice(colon + 1).trim();
    if (!value.startsWith('"') && !value.startsWith("'")) {
      const hashIdx = value.indexOf("#");
      if (hashIdx !== -1) value = value.slice(0, hashIdx).trim();
    }
    value = stripQuotes(value);
    if (key === "") return { ok: false, error: `line ${i + 1}: empty key` };
    if (value === "") { out[key] = []; activeListKey = key; } else { out[key] = value; }
  }
  return { ok: true, value: out };
}

/** Pick the machine text from a dual-format pair: .md fenced block wins, else legacy .yaml. */
function readDual(mdPath, yamlPath) {
  if (fs.existsSync(mdPath)) {
    const block = extractFencedYaml(fs.readFileSync(mdPath, "utf8"));
    if (block != null) return { text: block, source: "md", path: mdPath };
  }
  if (fs.existsSync(yamlPath)) return { text: fs.readFileSync(yamlPath, "utf8"), source: "yaml", path: yamlPath };
  return null;
}

function parseStructured(picked) {
  const y = projectYaml();
  if (!y) return { ok: false, value: null, source: picked.source, path: picked.path, error: "yaml package not available in project" };
  try {
    return { ok: true, value: y.parse(picked.text), source: picked.source, path: picked.path };
  } catch (e) {
    return { ok: false, value: null, source: picked.source, path: picked.path, error: `parse error: ${e.message}` };
  }
}

/** Load a feature spec (dir/spec.md fenced block, else dir/spec.yaml) → parsed object. */
export function loadSpec(dir) {
  const picked = readDual(path.join(dir, "spec.md"), path.join(dir, "spec.yaml"));
  if (!picked) return { ok: false, value: null, source: null, path: path.join(dir, "spec.{md,yaml}"), error: "no spec.md or spec.yaml" };
  return parseStructured(picked);
}

/** Load a lock/stamp file (dir/standards-compliance.md fenced block, else .yaml) → flat map. */
export function loadLock(dir) {
  const picked = readDual(path.join(dir, "standards-compliance.md"), path.join(dir, "standards-compliance.yaml"));
  if (!picked) return { ok: false, value: null, source: null, path: path.join(dir, "standards-compliance.{md,yaml}"), error: "no standards-compliance.md or .yaml" };
  const parsed = parseLockFile(picked.text);
  return parsed.ok
    ? { ok: true, value: parsed.value, source: picked.source, path: picked.path }
    : { ok: false, value: null, source: picked.source, path: picked.path, error: parsed.error };
}

/**
 * Resolve the on-disk spec file for a __specs__ dir: `spec.md` if it exists,
 * else `spec.yaml` (the default used for presence checks + message labels even
 * when neither exists).
 */
export function resolveSpecFile(specsDir) {
  const md = path.join(specsDir, "spec.md");
  return fs.existsSync(md) ? md : path.join(specsDir, "spec.yaml");
}

/**
 * Resolve the on-disk lock/stamp file for a __specs__ dir:
 * `standards-compliance.md` if it exists, else `standards-compliance.yaml`.
 */
export function resolveLockFile(specsDir) {
  const md = path.join(specsDir, "standards-compliance.md");
  return fs.existsSync(md) ? md : path.join(specsDir, "standards-compliance.yaml");
}

/**
 * Resolve the on-disk flow file for a base path WITHOUT extension
 * (e.g. .../flows/main): `<base>.flow.md` if it exists, else `<base>.flow.yaml`.
 */
export function resolveFlowFile(baseNoExt) {
  const stripped = baseNoExt.replace(/\.flow\.(md|yaml)$/, "").replace(/\.(md|yaml)$/, "");
  const md = `${stripped}.flow.md`;
  return fs.existsSync(md) ? md : `${stripped}.flow.yaml`;
}

/** True when a spec exists in either format (spec.md fenced form OR legacy spec.yaml). */
export function specFileExists(specsDir) {
  return fs.existsSync(path.join(specsDir, "spec.md")) || fs.existsSync(path.join(specsDir, "spec.yaml"));
}

/** Load a flow file given its base path WITHOUT extension (e.g. .../flows/main). */
export function loadFlow(base) {
  const stripped = base.replace(/\.flow\.(md|yaml)$/, "").replace(/\.(md|yaml)$/, "");
  const picked = readDual(`${stripped}.flow.md`, `${stripped}.flow.yaml`);
  if (!picked) return { ok: false, value: null, source: null, path: `${stripped}.flow.{md,yaml}`, error: "no .flow.md or .flow.yaml" };
  return parseStructured(picked);
}
