// Shared lock + freshness helpers — the single source consumed by the

// ────────────────────────────────────────────────────────────────
// DO NOT EDIT THIS FILE.
//
// COPY of source-of-truth at
//   ~/.claude/standards/scripts/lib/locks.mjs
//
// Local edits will be overwritten the next time
//   bash ~/.claude/standards/scripts/install-slice-gates.sh
// runs. Edit the ORIGINAL and re-install.
// ────────────────────────────────────────────────────────────────
// verifier-mode dispatcher (scripts/verify/verify-mode.mjs) AND the net-pinned
// standalone gates (verify-standards-compliance — its shape/presence/mtime
// checks plus the deep git-history freshness pass under `--full` — and
// verify-commit-stamp).
//
// Every lock-shape parse, git-history freshness comparison, changed-path →
// slice/lock resolution, whole-repo lock walk, and lock stamp/unlock lives
// here so the modes never copy-paste the logic among themselves.

import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const LIB_DIR = dirname(__filename);
// scripts/lib → up2 = the repo/web root (same as every gate's ROOT).
const REPO_ROOT = resolve(LIB_DIR, "..", "..");

/**
 * Strict ISO-8601 UTC matcher: YYYY-MM-DDTHH:MM:SS(.sss)?Z. Anchored so a
 * string with trailing garbage doesn't sneak through; the Z suffix is
 * required — lock files are UTC per UTC_TIMESTAMPS.yaml.timestamps.
 * @type {RegExp}
 */
export const ISO_UTC_RE =
  /^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}(?:\.[0-9]+)?Z$/;

/**
 * Grace window applied when comparing the latest git-commit date to
 * `last_validated`. A developer/agent writes `last_validated = now()` in the
 * YAML, then iterates / runs hooks / runs `git commit`; the commit's
 * author-date is recorded AFTER the YAML value was set. 30 minutes covers the
 * iteration cycles observed in practice; real drift (forgetting to re-stamp
 * across days/weeks) is far outside this window, so the signal is preserved.
 * @type {number}
 */
export const SAME_COMMIT_GRACE_MS = 30 * 60 * 1000;

const SKIP_DIRS = new Set([
  "node_modules",
  ".next",
  ".git",
  "storybook-static",
  "coverage",
  "dist",
  "build",
]);

/**
 * Parse a lock file's flat key/value fields. Multi-line and list values are
 * ignored — the mode gates only need status / verified / last_validated, all
 * scalars.
 * @param {string} contents
 * @returns {Record<string, string>}
 */
export function parseScalarFields(contents) {
  /** @type {Record<string, string>} */
  const out = {};
  for (const line of contents.split(/\r?\n/)) {
    const m = line.match(/^([a-z_]+):\s*(.*)$/);
    if (m === null) continue;
    const [, k, vRaw] = m;
    const v = vRaw.replace(/^["']|["']$/g, "").trim();
    out[k] = v;
  }
  return out;
}

/**
 * Assert the shape of a single lock file. Returns the per-lock verdict along
 * with the parsed `last_validated` epoch ms (consumed by the freshness gate).
 * @param {string} lockPath absolute
 * @param {{ readFile?: (p: string) => string }} [io]
 * @returns {{ ok: true, lastValidatedMs: number } | { ok: false, reason: string }}
 */
export function checkLockShape(lockPath, io = {}) {
  const readFile = io.readFile ?? ((p) => readFileSync(p, "utf8"));
  /** @type {string} */
  let contents;
  try {
    contents = readFile(lockPath);
  } catch (err) {
    return { ok: false, reason: `cannot read: ${err instanceof Error ? err.message : String(err)}` };
  }
  const fields = parseScalarFields(contents);
  if (fields["status"] !== "locked") {
    return { ok: false, reason: `status='${fields["status"] ?? ""}'; expected 'locked'` };
  }
  if (fields["verified"] !== "100%") {
    return { ok: false, reason: `verified='${fields["verified"] ?? ""}'; expected '100%'` };
  }
  const stamp = fields["last_validated"] ?? "";
  if (!ISO_UTC_RE.test(stamp)) {
    return { ok: false, reason: `last_validated='${stamp}'; expected ISO-8601 UTC` };
  }
  const stampMs = Date.parse(stamp);
  if (Number.isNaN(stampMs)) {
    return { ok: false, reason: `last_validated='${stamp}' did not parse as Date` };
  }
  return { ok: true, lastValidatedMs: stampMs };
}

/**
 * Walk up from `startAbs` toward `rootAbs` to find the nearest ancestor that
 * contains `__specs__/standards-compliance.yaml`. Returns the absolute lock
 * path, or null when no ancestor has one.
 * @param {string} startAbs
 * @param {string} rootAbs
 * @returns {string | null}
 */
export function findSliceLock(startAbs, rootAbs) {
  let cur = startAbs;
  while (cur.length > rootAbs.length) {
    const lock = join(cur, "__specs__", "standards-compliance.yaml");
    if (existsSync(lock)) return lock;
    const parent = dirname(cur);
    if (parent === cur) break;
    cur = parent;
  }
  return null;
}

/**
 * From a list of changed absolute paths, return the unique sorted set of lock
 * files to check. Paths outside any spec'd slice are dropped.
 * @param {readonly string[]} changedPaths
 * @param {string} rootAbs
 * @returns {string[]}
 */
export function locksFromChangedPaths(changedPaths, rootAbs) {
  /** @type {Set<string>} */
  const out = new Set();
  for (const p of changedPaths) {
    const lock = findSliceLock(p, rootAbs);
    if (lock !== null) out.add(lock);
  }
  return [...out].sort();
}

/**
 * Walk up from a changed path to the folder that owns its lock — that folder
 * IS the slice. Returns null when no ancestor has a lock.
 * @param {string} startAbs
 * @param {string} rootAbs
 * @returns {string | null}
 */
export function findSliceRoot(startAbs, rootAbs) {
  let cur = startAbs;
  while (cur.length > rootAbs.length) {
    const lock = join(cur, "__specs__", "standards-compliance.yaml");
    if (existsSync(lock)) return cur;
    const parent = dirname(cur);
    if (parent === cur) break;
    cur = parent;
  }
  return null;
}

/**
 * From changed absolute paths, return the unique sorted set of slice roots.
 * @param {readonly string[]} changedPaths
 * @param {string} rootAbs
 * @returns {string[]}
 */
export function slicesFromChangedPaths(changedPaths, rootAbs) {
  /** @type {Set<string>} */
  const slices = new Set();
  for (const p of changedPaths) {
    const slice = findSliceRoot(p, rootAbs);
    if (slice !== null) slices.add(slice);
  }
  return [...slices].sort();
}

/**
 * Convert lock paths (`<slice>/__specs__/standards-compliance.yaml`) into
 * unique sorted slice roots (`<slice>`).
 * @param {readonly string[]} lockPaths absolute
 * @returns {string[]}
 */
export function slicesFromLocks(lockPaths) {
  /** @type {string[]} */
  const slices = [];
  for (const lock of lockPaths) {
    const specsDir = dirname(lock);
    slices.push(dirname(specsDir));
  }
  return [...new Set(slices)].sort();
}

/**
 * Walk `rootDir`; return absolute paths of every
 * `<...>/__specs__/standards-compliance.yaml`, sorted.
 * @param {string} rootDir
 * @param {{ readDir?: (dir: string) => Array<{ name: string, isDirectory: () => boolean }>, statFile?: (p: string) => unknown }} [io]
 * @returns {string[]}
 */
export function findAllLocks(rootDir, io = {}) {
  const readDir =
    io.readDir ?? ((dir) => readdirSync(dir, { withFileTypes: true }));
  const statFile = io.statFile ?? statSync;
  /** @type {string[]} */
  const locks = [];
  /** @param {string} dir */
  function walk(dir) {
    /** @type {Array<{ name: string, isDirectory: () => boolean }>} */
    let entries;
    try {
      entries = readDir(dir);
    } catch {
      return;
    }
    for (const entry of entries) {
      if (SKIP_DIRS.has(entry.name)) continue;
      if (!entry.isDirectory()) continue;
      const full = join(dir, entry.name);
      if (entry.name === "__specs__") {
        const lock = join(full, "standards-compliance.yaml");
        try {
          statFile(lock);
          locks.push(lock);
        } catch {
          // no lock in this __specs__ — skip
        }
      } else {
        walk(full);
      }
    }
  }
  walk(rootDir);
  return locks.sort();
}

/**
 * Default git-history adapter: ISO-8601 date of the most recent commit that
 * touched any file in `folder`, EXCLUDING the lock file itself (re-stamping
 * the lock would otherwise always look like a fresh change). Returns null when
 * the folder has no commits yet, git is unavailable, or cwd is not a repo —
 * callers treat null as "fresh" (a git-environment problem is not a violation).
 * Uses `execFileSync` (not shell) so paths can't be injected.
 * @param {string} folder absolute path to the feature folder
 * @param {string} lockFile absolute path to the lock file inside `folder/__specs__/`
 * @returns {string | null}
 */
export const defaultGitLastCommit = (
  /** @type {string} */ folder,
  /** @type {string} */ lockFile,
) => {
  try {
    const lockRel = relative(folder, lockFile);
    const out = execFileSync(
      "git",
      ["log", "-1", "--format=%aI", "--", ".", `:(exclude)${lockRel}`],
      { encoding: "utf8", cwd: folder, stdio: ["ignore", "pipe", "ignore"] },
    ).trim();
    return out === "" ? null : out;
  } catch {
    return null;
  }
};

/**
 * Freshness verdict for a single lock file. Stale = the folder's most recent
 * commit (other than the lock file itself) has an ISO-8601 author date strictly
 * greater than `lastValidatedMs + SAME_COMMIT_GRACE_MS`.
 * @param {string} lockFileAbs absolute path to the lock file
 * @param {number} lastValidatedMs epoch ms of the lock's last_validated
 * @param {{ gitLastCommit?: (folder: string, lockFile: string) => string | null }} [injected]
 * @returns {{ ok: true } | { ok: false, reason: string, detail: string }}
 */
export function checkFreshness(lockFileAbs, lastValidatedMs, injected = {}) {
  const gitLastCommit = injected.gitLastCommit ?? defaultGitLastCommit;
  const specsDir = dirname(lockFileAbs);
  const featureDir = dirname(specsDir);

  const lastCommitIso = gitLastCommit(featureDir, lockFileAbs);
  if (lastCommitIso === null) {
    return { ok: true };
  }

  const commitMs = Date.parse(lastCommitIso);
  if (Number.isNaN(commitMs)) {
    return {
      ok: false,
      reason: "git log returned unparseable date",
      detail: `'${lastCommitIso}' did not parse as a Date`,
    };
  }

  if (commitMs <= lastValidatedMs + SAME_COMMIT_GRACE_MS) {
    return { ok: true };
  }

  const stamped = new Date(lastValidatedMs).toISOString();
  return {
    ok: false,
    reason: "folder modified after last_validated",
    detail: `last_validated=${stamped}; last git commit touching ${relative(REPO_ROOT, featureDir)}=${lastCommitIso}`,
  };
}

/**
 * Flip the lock's `status:` field to `unlocked`. Used at the start of Mode A
 * before running gates — an interrupt mid-gates leaves the slice unlocked,
 * the correct signal that the slice was not re-validated.
 * @param {string} lockPath
 * @param {{ readFile?: (p: string) => string, writeFile?: (p: string, c: string) => void }} [io]
 * @returns {void}
 */
export function unlockLock(lockPath, io = {}) {
  const readFile = io.readFile ?? ((p) => readFileSync(p, "utf8"));
  const writeFile = io.writeFile ?? ((p, c) => writeFileSync(p, c, "utf8"));
  const contents = readFile(lockPath);
  const next = contents.replace(/^status:\s*.*$/m, "status: unlocked");
  writeFile(lockPath, next);
}

/**
 * Stamp the lock with the current UTC time AND flip `status:` → `locked`.
 * Called by Mode A on a successful gate pass — completes the unlock→relock
 * state machine. `verified:` is normalized to `"100%"`.
 * @param {string} lockPath
 * @param {{ readFile?: (p: string) => string, writeFile?: (p: string, c: string) => void, now?: () => Date }} [io]
 * @returns {string} the new last_validated value
 */
export function stampLock(lockPath, io = {}) {
  const readFile = io.readFile ?? ((p) => readFileSync(p, "utf8"));
  const writeFile = io.writeFile ?? ((p, c) => writeFileSync(p, c, "utf8"));
  const now = io.now ?? (() => new Date());
  const iso = now().toISOString().replace(/\.\d+Z$/, "Z");
  const contents = readFile(lockPath);
  let next = contents.replace(/^status:\s*.*$/m, "status: locked");
  next = next.replace(/^verified:\s*.*$/m, 'verified: "100%"');
  next = next.replace(/^last_validated:\s*.*$/m, `last_validated: ${iso}`);
  writeFile(lockPath, next);
  return iso;
}
