// Shared filesystem walker for the verification scripts. Pure Node

// ────────────────────────────────────────────────────────────────
// DO NOT EDIT THIS FILE.
//
// COPY of source-of-truth at
//   ~/.claude/standards/scripts/lib/walk.mjs
//
// Local edits will be overwritten the next time
//   bash ~/.claude/standards/scripts/install-slice-gates.sh
// runs. Edit the ORIGINAL and re-install.
// ────────────────────────────────────────────────────────────────
// built-ins, zero external dependencies.
//
// Default `skipDirs` set covers Node + Next.js + tooling output folders:
// node_modules, .next, .turbo, .git, coverage, test-results,
// playwright-report, dist, build, out. Each entry point accepts an
// override so a specific gate can scope differently.

import { readdirSync, statSync } from "node:fs";
import { join } from "node:path";

/**
 * Default directory names to skip across the codebase. Each verify
 * script can pass its own set to override.
 *
 * @type {ReadonlySet<string>}
 */
export const DEFAULT_SKIP_DIRS = new Set([
  "node_modules",
  ".next",
  ".turbo",
  "coverage",
  "test-results",
  "playwright-report",
  ".git",
  "dist",
  "build",
  "out",
]);

/**
 * Recursively walks `root` and yields every file path (absolute).
 *
 * @param {string} root absolute path to walk
 * @param {{ skipDirs?: ReadonlySet<string> }} [options]
 * @returns {string[]} list of absolute file paths
 */
export function listAllFiles(root, options = {}) {
  const skipDirs = options.skipDirs ?? DEFAULT_SKIP_DIRS;
  const out = [];
  const stack = [root];
  while (stack.length > 0) {
    const dir = stack.pop();
    let entries;
    try {
      entries = readdirSync(dir);
    } catch {
      continue;
    }
    for (const entry of entries) {
      const full = join(dir, entry);
      let stat;
      try {
        stat = statSync(full);
      } catch {
        continue;
      }
      if (stat.isDirectory()) {
        if (skipDirs.has(entry)) continue;
        stack.push(full);
      } else if (stat.isFile()) {
        out.push(full);
      }
    }
  }
  return out;
}

/**
 * Recursively walks `root` and yields every directory path (absolute,
 * INCLUDING `root` itself).
 *
 * @param {string} root absolute path to walk
 * @param {{ skipDirs?: ReadonlySet<string> }} [options]
 * @returns {string[]} list of absolute directory paths
 */
export function listAllDirs(root, options = {}) {
  const skipDirs = options.skipDirs ?? DEFAULT_SKIP_DIRS;
  const out = [root];
  const stack = [root];
  while (stack.length > 0) {
    const dir = stack.pop();
    let entries;
    try {
      entries = readdirSync(dir);
    } catch {
      continue;
    }
    for (const entry of entries) {
      const full = join(dir, entry);
      let stat;
      try {
        stat = statSync(full);
      } catch {
        continue;
      }
      if (stat.isDirectory()) {
        if (skipDirs.has(entry)) continue;
        out.push(full);
        stack.push(full);
      }
    }
  }
  return out;
}
